### ISSUE TITLE
Titan mitts in a place where you need Titan mitts 

### ISSUE THREAD

**Issue by timmon123** [Dessyreqt/alttprandomizer#1]
Hi

Seed: C0514404 
[cave-056] Dark World Death Mountain - cave under boulder [bottom left chest].............Titan's Mitt

Without major gltiches not possible to get there.

Greeting 
timmon

[ALttP Random - C0514404.sfc.spoilers.txt](https://github.com/Dessyreqt/alttprandomizer/files/288597/ALttP.Random.-.C0514404.sfc.spoilers.txt)

[ALttP Random - C0514404.sfc.spoilers.txt](https://github.com/Dessyreqt/alttprandomizer/files/288597/ALttP.Random.-.C0514404.sfc.spoilers.txt)

**Comment by Dessyreqt** [comment]
This was because of a simple oversight... forgot there was a dark block in front of the portal! This is now fixed in the code.
