### ISSUE TITLE
Bombs not automatically selected

### ISSUE THREAD

**Issue by BlueViper85** [Dessyreqt/alttprandomizer#100]
Seed C9465876

A minor inconvenience, but bombs were in the chest in Link's house.  When picked up they were not automatically set as the Y item.  I had to pause to bring up the menu at which point they became selected and usable. 

See attached screenshot showing 3 bombs in my inventory at the top of the HUD but nothing in the item box.  This was corrected once I got the sword + shield from the uncle.

![2016-08-20](https://cloud.githubusercontent.com/assets/12190332/17832589/57bd9ada-66cc-11e6-8a78-701f78f187fe.png)

**Comment by ChristosOwen** [comment]
This isn't just an issue with Bombs, but a bigger 'issue' affecting a group of items and events which trigger auto-selection to happen. Have enquired in Discord to see if we can find a resolution.

**Comment by KatDevsGames** [comment]
I already did this for bottles. I will add a change for this.

**Comment by ChristosOwen** [comment]
Added to the doc, closing here. Good spot!

**Comment by ChristosOwen** [comment]
Leaving open as Karkat seems to want things here as reminders :+1:

**Comment by ChristosOwen** [comment]
This has been resolved and will be fixed in the next version.
