### ISSUE TITLE
Mothula + Lv. 4 Sword

### ISSUE THREAD

**Issue by Dessyreqt** [Dessyreqt/alttprandomizer#102]
Submitter: Pyro767
Email: cocodabunda@hotmail.com
Now, I know this is a thing in the original game too but, would it be possible for you guys to make Mothula vulnerable to Lv. 4 Sword swings and spins and possible Lv. 3 spins or is it not possible/requires too much work? I ask this because in randomizer is pretty easy to get said swords before doing Skull Woods or any other DW dungeons (except for 5, and 6 for Lv. 4 sword obviously) for that matter.

Thank you guys for this awesome project it really helps getting into this game again after having played it God knows how many times.

**Comment by ChristosOwen** [comment]
This is in fact already planned! In future crystals will be randomized between dark world dungeons and swords may be randomized between themselves (excluding Uncle) so it will become more likely Gold Sword is available before Mothula. So we will be fixing sword damage for this fight.
