### ISSUE TITLE
Suggestion: Load spoilers into Fortune Teller dialogue

### ISSUE THREAD

**Issue by TonyTheTGR** [Dessyreqt/alttprandomizer#109]
About the only thing that might be tricky is controlling the order they appear in; since regular conditions that progress the original plot are what changes the dialogue. But if a person is stuck finding an item they need to enter their next respective dungeon, it's a neat way to give them a pointer without them having to open the spoiler text. It's also a way to make all of those rupee treasures worthwhile.

**Comment by ChristosOwen** [comment]
I think directly leading people to the location of items is both hard to implement and too big of a giveaway. However, a compromise could be to have fortune tellers, Sahasrahla telepathic tiles and the other NPC's which you can pay for hints in the dark world give generic hints, about features unique to the randomizer (toggling items in the menu, caping through Agahnim's barrier, etc) as well as unusual locations to check (east dark world death mountain, "did you know there are 8 chests in Swamp Palace?", etc).

**Comment by TonyTheTGR** [comment]
The Sahsrahla tiles would be great for the general hints, or dungeon/boss specific stuff, in case you can't damage it in the typical way. I had to take out Grand Jelectro with Hammer Time!

**Comment by ChristosOwen** [comment]
I've added a note to look to include this in a future version of randomizer. Thanks for your suggestion :)
