### ISSUE TITLE
Overhaul Download Page

### ISSUE THREAD

**Issue by BlueViper85** [Dessyreqt/alttprandomizer#110]
Would it be possible in some future version to have the sick kid say something that indicates You need a bottle for him to give you his item?  Alternatively take that requirement away?

While this is something the most familiar people would know, I've seen some people talk to him and not realize why he didn't give the item the first time.

Not a problem if not, but seems like something that would be worth noting and thought I would inquire.

**Comment by ChristosOwen** [comment]
I would really not like to alter his behaviour. It's a part of the natural game and should stay that way. The goal of this randomizer isn't to coddle people not familiar with the game; but rather to optimise the randomization of item/key distributions for racing. As per Dessy's into on his download page:

"This is a simple program that moves around items in the Legend of Zelda: A Link to the Past (ALttP). It is used for racing the game."

Generally speaking, any change which alters anything without improving randomization I'm likely to dislike, as for me it's not the spirit of this project. It's already babying people way too much for my liking!

**Comment by BlueViper85** [comment]
That's fair. But alternatively given the exposure this thing has gotten and the fact that current seeds are classified as "casual" I figured inquiring wouldn't be harmful. Additionally I'd then vote to change the "difficulty" to a different name altogether to be more fitting with the racing theme.

**Comment by Dessyreqt** [comment]
I'm actually quite okay with having the sick kid say something like "Please find a bottle" or something to that effect if you don't have one; seasoned players aren't going to visit him unless they have one, so it shouldn't impact the runners.

**Comment by ChristosOwen** [comment]
I just re-read your first message and I glossed over there were two suggestions in there (sorry!) - altering his behaviour I don't like; adding text to say you need a bottle, sure thing.

As for the name, I'll leave that to Dessy. I've disliked the "casual" name from the get-go, since for some reason everyone then panicked we weren't being generous enough to an unknown subset of people who mostly hadn't even complained about anything? Unless there's something I don't know about.

The best thing for me would be to have 2 versions; one accounting for major glitches (excluding EG and semi-EG) and one completable without any major glitches (the current version). I don't think a "speedrunner" version is either in demand or worth the effort, nor would it be that different from the current version ultimately? What do we think?

**Comment by KatDevsGames** [comment]
I think at this stage that this (Christos' suggestion) may be preferable.

On August 25, 2016 8:50:38 AM EDT, ChristosOwen notifications@github.com wrote:

> I just re-read your first message and I glossed over there were two
> suggestions in there (sorry!) - altering his behaviour I don't like;
> adding text to say you need a bottle, sure thing.
> 
> As for the name, I'll leave that to Dessy. I've disliked the "casual"
> name from the get-go, since for some reason everyone then panicked we
> weren't being generous enough to an unknown subset of people who mostly
> hadn't even complained about anything? Unless there's something I don't
> know about.
> 
> The best thing for me would be to have 2 versions; one accounting for
> major glitches (excluding EG and semi-EG) and one completable without
> any major glitches (the current version). I don't think a "speedrunner"
> version is either in demand or worth the effort, nor would it be that
> different from the current version ultimately? What do we think?
> 
> ## 
> 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/Dessyreqt/alttprandomizer/issues/110#issuecomment-242374232

## 

Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by BlueViper85** [comment]
I agree with Chris' comment on the versioning both here and otherwise recently.  Two versions seems sufficient.

I'll close this "issue" for now, but if we want to continue any discussion on this here feel free to re-open this.

Thanks, guys!

**Comment by BlueViper85** [comment]
Ok, if we plan to add text to the Sick Kid I should probably leave this open... my bad

**Comment by KatDevsGames** [comment]
I'll forget if it's not open.

**Comment by ChristosOwen** [comment]
Can we add an image of a bottle instead of text (or in the text box)? Perhaps this is more in keeping with all the text being removed? Just thinking otherwise it's a random bit of English in an otherwise Japanese based ROM (except uncle and any hint tiles we choose to add, if any)? But English text is good if this is a horrible idea!

**Comment by ChristosOwen** [comment]
This has been resolved and will be in the next update

**Comment by KatDevsGames** [comment]
We actually can do this. The game even already has a mechanism for 
putting item icons in text boxes. Recall the waterfall of wishing.

**Comment by SmashManiac** [comment]
In case this affects the discussion, here are some more potentially-confusing spawns from the original game that haven't been mentioned yet:
- Magic powder
- Super bomb
- Level 3 sword
- Purple chest

Not sure if you prefer to manage those as separate issues or not.

**Comment by BlueViper85** [comment]
The main page for the randomizer mentions that Mushroom/Powder as well as the purple chest are randomized.  The only thing special about the Level 3 sword (Tempered Sword) is that you can't Save and Quit and keep the frog, which is also mentioned.

The super bomb is not randomized as of right now, so there's not much need to make a note for that. If something changes in regards to that the patch notes will be updated to cover that situation.

**Comment by darkmagician1184** [comment]
I think Smash is referring to the NPCs 'requirements' for those items.  A casual wouldn't know about the desert thief, or understand why they can't get the big bomb, or why the witch's hut doesn't have an item.  I'm not sure of the level 3 sword, perhaps the dwarf says something like, "find my brother and I'll temper your sword".

On top of that, maybe something for Shash as well, especially if we are going to randomize pendants/required pendant.

I think saying, in japanese, "do you have [X]?" would work fine, english speakers would understand "[X]?" and it leaves english text out of an otherwise japanese filled game.

**Comment by BlueViper85** [comment]
While I agree, asking for verification of the concern held more value.

I disagree with the sentiment of the Tempered Sword/Dwarf "concern."  The game isn't generally beatable without the tempered sword.

When crystals are randomized I'd say that maybe adding a note about 5/6 being necessary for Gold Sword would be important.  Until then just knowing it's accessible late in the game should be sufficient.  Since it generally isn't available until essentially the end of the game as it is.

Similarly, I agree with having a similar note for Sahasralah for the Pendant of Courage would be good when those are randomized.

The purple chest, I'm on the fence on.  I don't know of a great way to say, succinctly, where to take it.  Could maybe make the thief mention Purple Chest similar to the sick kid mentioning a bottle.

Mushroom / Powder seems on-par with the Sick Kid.  Maybe worth having the Witch mention the Mushroom in the same vain as the Sick Kid with the bottle.

**Comment by KatDevsGames** [comment]
I'm not too worried about English vs Japanese text. I'm going to use icons where needed and English text elsewhere. All Japanese text is coming out. The few small bits of dialog I'm not removing will be simplified and translated.

Powder and mushroom are not happening. Does the vanilla game even tell you a bottle is needed?

On September 6, 2016 11:25:29 AM EDT, darkmagician1184 notifications@github.com wrote:

> I think Smash is referring to the NPCs 'requirements' for those items. 
> A casual wouldn't know about the desert thief, or understand why they
> can't get the big bomb, or why the witch's hut doesn't have an item. 
> I'm not sure of the level 3 sword, perhaps the dwarf says something
> like, "find my brother and I'll temper your sword".
> 
> On top of that, maybe something for Shash as well, especially if we are
> going to randomize pendants/required pendant.
> 
> I think saying, in japanese, "do you have [X]?" would work fine,
> english speakers would understand "[X]?" and it leaves english text out
> of an otherwise japanese filled game.
> 
> ## 
> 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/Dessyreqt/alttprandomizer/issues/110#issuecomment-244987687

## 

Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by BlueViper85** [comment]
I don't recall the original game ever telling you out right that the kid requires a bottle.  He simply doesn't wake up if I remember correctly.  There's a guy who mentions him elsewhere in town, but I don't recall him mentioning the bottle either.

**Comment by darkmagician1184** [comment]
The sick boy does not wake up, but if you walk up to his bed and try to talk to him, a text box opens.  According to google, it says, "Have a bottle to put Gohogoho B brother insects? ... So, of you do not have Gohotsu".

And I know Shash says, "you need to prove you have courage, retrieve the pendant from The Eastern Palace" roughly remembered.

**Comment by ChristosOwen** [comment]
Haha nice translation! Yeah if you speak to the sick kid he tells you to get a bottle so you can keep stuff in, in the regular game. With the removal of all text, I wouldn't mind if English text with icons got added.
- Sick kid when you don't have a bottle; bottle (image with text)
- Witch, anytime; mushroom (image with text)
- Desert thief when you don't have a follower; purple chest icon (if possible) otherwise a description
- Bomb shop guy; crystal 5+6 (images with text or just text)
- Sashrahla when you don't have pendant; green pendant (image with text)
- Master Sword pedastal readable tile (without requiring book); 3 pendants (image with text)
- Dwarf in hut before you rescue his buddy; "please find my partner, he might be a frog" or whatever
- Powder statue when you talk to it; powder (image with text)
- King Zora; "please pay me 500 rupees" or whatever

Pretty sure that covers everything any casual could be confused about. Don't have to add all of them, or even any of them, but it's what I could think of!

**Comment by BlueViper85** [comment]
Given that the Sick Kid does tell you he requires a bottle in the vanilla version, I'd say it is as much for debate as all the rest of these.  As is made obvious by the original submission and my earlier comment, I completely failed to remember that he says it.

At this point I think it comes down to how much do we cater to the less-informed.  Perhaps we can take Chris's list and make it a note somewhere (perhaps even just here?) and not modify the game at all to accommodate?

I know there's several other things on the page already, and I hate to add more to it, especially since it's not always read.  Perhaps any notes like this could be put into a Readme file included with the application, or perhaps better yet we do something along these lines:

-Add a "Help" menu to to the application via the MenuBar tool
-Move the "Report an issue" button to this menu
-Add a menu option above that like "FAQ" or something that opens a window with these details

Again, this can be executed through a number of means beyond a Help menu, maybe just put the FAQ right above the form that opens when you click "Report an issue" (while this does lengthen the page, it does improve visibility before an issue is submitted)

Thoughts?

**Comment by ChristosOwen** [comment]
Putting those on the download page works. Then the risk is people don't read it and submit bogus reports, but I doubt many people would.

The ones I suggested, the way I suggested them would never lose time by telling you useless info if you have the item/do the correct action, so it's harmless adding them all into the game itself.

I really don't care enough either way so happy with whatever!

**Comment by KatDevsGames** [comment]
I still think the software should make you read a thing at least once 
before it lets you submit reports.

**Comment by ChristosOwen** [comment]
Happy with that solution too!

**Comment by darkmagician1184** [comment]
I believe the medallion pedestals also tell you stuff, or maybe they just say it in Hylian, like desert does.  I don't remember how you find out you need a higher level sword to work them, tbh.

But yes, I think you've covered most everything from vanilla, as far as NPCs requesting prerequisites.

**Comment by SmashManiac** [comment]
To clarify my previous comment, with the more obscure requirements IMO in bold:
- To get magic powder: use mushroom on witch, **leave screen**, go back, **enter shop**
- To get super bomb: **beat Ice Palace, beat Misery Mire, save smithy**, go to bomb shop, pay 100 rupees
- To get level 3 sword: save smithy, **leave forge**, go back, pay 10 rupees, leave forge again, **leave screen**, go back in forge, talk to smithy
- To get purple chest bottle: **save smithy**, pick up purple chest, use magic mirror, walk all the way to desert thief, talk to desert thief

**Comment by BlueViper85** [comment]
After further discussion on discord, a few ideas have come up that should help with the issue of certain features and changes being missed:
- Overhaul the Download Page for clarity and user-friendliness
- Change the "Report an issue" button to a "I need help" button that opens a FAQ or help page (a web-page embedded into the windows form)
- This FAQ/Help page would then have the option to report an issue.

**Comment by ChristosOwen** [comment]
This has been done/Dessy updated the client in his last release.
