### ISSUE TITLE
Bug: Vanishing pendants

### ISSUE THREAD

**Issue by TonyTheTGR** [Dessyreqt/alttprandomizer#111]
Loading a saved game doesn't seem to recall the pendants I've collected, even though it DOES remember that I've killed the bosses. So I have to rejourney through each dungeon to recollect whatever pendants I found. Not sure if it applies to collected crystals, yet.

**Comment by KatDevsGames** [comment]
Duplicate of #8. This is fixed in trunk. Will be available as part of v7.

Stay away from big (not great) fairies and your pendants will be safe.

**Comment by KatDevsGames** [comment]
Actually not #8 but it's in there somewhere. It's fixed at any rate.

Avoid big fairies.

**Comment by TonyTheTGR** [comment]
Okay, cool. Thank you for the heads up.
