### ISSUE TITLE
urg

### ISSUE THREAD

**Issue by Dessyreqt** [Dessyreqt/alttprandomizer#112]
Submitter: logan
Email: logan.livingston2005@gmail.com
[v6]
I cant play the game

**Comment by BlueViper85** [comment]
Responded to the specified email address with the following:

Additional details are needed to determine the problem. 

Generically speaking:

Download the Randomizer and click Create. It will create and SFC file you need to open in any SNES emulator. SNES9x or BSNES would be recommended.

If that doesn't address your concern please provide more details at 

https://github.com/Dessyreqt/alttprandomizer/issues/112

Thanks,

BlueViper85
