### ISSUE TITLE
Potential Soft-Lock Issue To Address

### ISSUE THREAD

**Issue by MayDonutLover** [Dessyreqt/alttprandomizer#114]
The hammer should never spawn in Dark World Death Mountain.  This is a soft-lock issue because the only way to get IN to those spots is WITH the hammer.
To get to caves 56, 57, and 58, the only way in is to warp in from Turtle Rock.  There are no other Dark World teleporters on East Death Mountain.
It also can't spawn in Cave 55 because you require the hammer to get through the cave to get what would normally be the Staff of Byrna.

I have also had spawns to where the Magic Mirror spawns in a Light World cave you have to warp in from the Dark World to get to.  Or, the Moon Pearl spawns in a Dark World location.  These are also soft-lock issues.

Last, I've also had it to where the Lamp and Bombos also get Soft-Locked.  You cannot finish the Desert Palace without fire to light the torches.

**Comment by BlueViper85** [comment]
If you can, please provide seed numbers so we can validate the locations of the items to determine what soft locks exist and why they happened.  They have happened here and there, but we need to know the specific location of various items to confirm why it happened.

For example, In some cases you may not be able to beat all the Light World dungeons, but the cape can be accessed.  In those instances you can use the cape to walk through the barrier to Agahnim's tower which gets you to the dark world. As a result the moon pearl could be on the Pyramid in the dark world (but shouldn't appear in any dungeons in the dark world)

**Comment by MayDonutLover** [comment]
Unfortunately, I didn't write those seeds down, but I will inform you when those happen again.

As far as the current seed I'm on, the Hammer is currently SoftLocked in this seed:
C6938576

**Comment by Dessyreqt** [comment]
If you still have the roms, the seeds can be found within those files. It should display as part of the game name when you load it in SNES9x. We will take a look at the seed you provided.

**Comment by BlueViper85** [comment]
Hammer is accessible in seed C6938576.  Need the hookshot, titan's mitts.  When you get to the mountain walk all the way right on the lower level and hookshot across the bridge.  On that side of the bridge is a dark stone that takes you to Dark World, you can then climb a cave to get to the top of the DW mountain and into that cave.

Hookshot can then be used to access the chests, including the one with the hammer.

**Comment by MayDonutLover** [comment]
I didn't, sadly.  I wish I had (because I had JUST found this site; a friend e-mailed me the randomizer).
I will say, though, that I LOVE the work you've done.  I'm just hoping to help you refine it.

**Comment by MayDonutLover** [comment]
...I feel SO dumb.  I didn't know that was there, BlueViper!  Thank you!

**Comment by BlueViper85** [comment]
Glad to help. If you have any other problems please report them. If they turn out to be like this at least we checked and know. Good luck and have fun!
