### ISSUE TITLE
application error

### ISSUE THREAD

**Issue by jsmith21220** [Dessyreqt/alttprandomizer#116]
the application failed to initialize properly (0xc000007b)

**Comment by BlueViper85** [comment]
Does this appear when launching the Randomizer executable or when launching the ROM it generates after?

If it's the randomizer, can you tell us what OS you're using (windows 7 / 8 / 8.1 /10)?

**Comment by jsmith21220** [comment]
as soon as i click on the randomizer it displays that and i have windows vista ultimate, i just installed .net framework but that did not fix it

**Comment by BlueViper85** [comment]
Do you know which version of the .NET Framework you installed?

**Comment by jsmith21220** [comment]
dotnetfx35setup
which im assuming to be 3.5

**Comment by Dessyreqt** [comment]
It requires .NET Framework 4.5.2

**Comment by jsmith21220** [comment]
@Dessyreqt thank you that fixed it =)

**Comment by KatDevsGames** [comment]
I have an innoscript for automatically running the .net 4.5.2 installer if needed if we want to create an installer.

On August 25, 2016 5:31:04 PM EDT, jsmith21220 notifications@github.com wrote:

> @Dessyreqt thank you that fixed it =)
> 
> ## 
> 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/Dessyreqt/alttprandomizer/issues/116#issuecomment-242547472

## 

Sent from my Android device with K-9 Mail. Please excuse my brevity.
