### ISSUE TITLE
Future thinking (not immediately related, but no idea where else to put/discuss this)...

### ISSUE THREAD

**Issue by TonyTheTGR** [Dessyreqt/alttprandomizer#117]
I know there's really no point in randomizing vanilla DKC - anyone that can perform that game from start to finish can do so with anything mixed up in it too; and mixing things within the levels would only hurt the game design, rather than flourish it.

BUT!!

What about shuffling the level order for DKC _Championship Edition_? Since it's a score-based, timed, one-shot version of the game that trims out the nonessential stuff (map screens, bosses), and I've never seen anyone get further than Orangutan Gang in it... randomizing the level order of THAT particular ROM could lead to significantly funner races and performances. Maybe hacking in a couple more fan favorites like Barrel Cannon Canyon, Vulture Culture, Tree Top Town, Oil Drum Alley, Manic Mincers, or Platform Perils, even?

And depending on whether or not the timer bonuses are tampered with (maybe you get them for the game's equivalents of 1ups, or anytime you complete a level), it may become possible-but-still-highly-challenging to complete it as well...

PS: It's criminal that you've only got 9 followers here.

**Comment by KatDevsGames** [comment]
I can't speak as to whether or not this is a good idea, that's up to dessyreqt what he builds but, unfortunately, this is the bug tracker for ALTTP randomizer and I really, really do need this tracker organized.

I'm not trying to be rude or shut down this idea. I'll make sure dessyreqt reads it but, as it's not actually an ALTTP randomizer issue, I have to mark this as closed/offtopic.

**Comment by TonyTheTGR** [comment]
Fair enough. I just... really didn't know where else to go with this.

**Comment by Niamek** [comment]
Basially, every games could get a randomizer. I believe the important question is: If it's randomized, is the game significantly different?

**Comment by KatDevsGames** [comment]
It depends on the game and how it's made. ALTTP is actually quite unstable and very easy to softlock under randomization. A large number of games would need an ASM dev just to stop the game from melting.

I'm not sure what games the randomizer concept would work with. For most games, no amount of randomization is going to change a whole ton. Maybe it would work GBA Zelda, Metroid and Castlevania games... perhaps?

**Comment by TonyTheTGR** [comment]
GBA Zeldas are _waaay_ too structured and meticulous with their item use and order of acquizition. A lot of games really are tough to mix up, or totally inconsequencial to do so (IE: vanilla DKC)... it's only the racing/scoring aspect of CE that makes this even a thing.

La Mulana or Cave Story with items shuffled, on the other hand? THAT could be THE THING.
