### ISSUE TITLE
Graphical Glitches (Compass/Blue Shield/L4 Sword)

### ISSUE THREAD

**Issue by WizzrobeZC** [Dessyreqt/alttprandomizer#119]
Added the above mentioned items as overworld items (replacing stationary heartpieces) and they look weird. Compass is cut in half, Small Shield has half a heartpiece attached to it and the sword is some kind of blue mishmash.

**Comment by KatDevsGames** [comment]
That makes sense these got missed since they NEVER show up in normal randomizer.

**Comment by KatDevsGames** [comment]
As close as it's going to get for now, fixed in trunk rom. Colors for sword not perfect due to pallette issues.
