### ISSUE TITLE
Seed C0566010 [v6] impossible to win.

### ISSUE THREAD

**Issue by MidnightWonko** [Dessyreqt/alttprandomizer#121]
My friend recently tried this seed, and came across an unwinnable situation.

This seed places the Power Glove with the hobo under the bridge, and the Titan's Mitt in the big chest for the Tower of Hera.  It also places the Lamp in the bumper cave in the dark world, and the Fire Rod in the cave in the northeast corner of the desert.

This means that, to get either the Lamp or the Fire Rod, he would need either the Power Glove or the Titan's Mitt, respectively.

Since the Power Glove is with the hobo, he needs the Flippers to reach it.  However, the Flipper's are in the Thieves' Town, which ALSO requires the Power Glove to reach.  So he needs the Power Glove to get the Flippers, and the Flippers to get the Power Glove.

Since the Titan's Mitt is in the big chest in the Tower of Hera, he needs the big key to get it.  The big key is in the 1st floor chest, which requires lighting four torches.

So he needs the Fire Rod or the Lamp to get the Titan's Mitt, and he needs the Titan's Mitt to get the Fire Rod or the Lamp (the Power Glove was previously discovered to be impossible to get).

**Comment by Dessyreqt** [comment]
You should be able to defeat Agahnim and then use the hookshot to get to Thieves' Town (which I'm pretty sure doesn't require the Power Glove to open) and then get the Power Glove.

**Comment by BlueViper85** [comment]
To confirm, defeat Agahnim (may need to use the cape to get past the barrier for his tower without the master sword).  If you have he hammer, once you are on the pyramid go right then up and follow the path until you see a small break in the barrier. Use the hook shot to grab a hold of some skulls on the other side that are off screen.

**Comment by MidnightWonko** [comment]
You can pass through the electric barrier using the cape?!?  0_o  That changes everything if it works!  I'm asking my friend to try that now.  If he can pass that barrier with the cape, I'm closing this thread and declaring it a non-issue!

EDIT: Yeah, turns out he can slide right on through that electric barrier using the cape.  Which he has.  Then he can get to the Thieves' Town using the hookshot.  Which he has.

So color this subject closed.  Thanks, guys!
