### ISSUE TITLE
Sahasrala item bug

### ISSUE THREAD

**Issue by Dessyreqt** [Dessyreqt/alttprandomizer#126]
Submitter: MabhFox
Email: mabhfox@hotmail.com
Hello!

First let me congratulate you for this amazing experience you have brought to the zelda community, it is really a great work you have done here...

It seems that the item you get from Sahasrala (replacing the boots) is not available if you forget to talk to him when you are supposed to, if you talk to him after that you don´t get the item, he just talks (i guess about the 3 pendants). I don't know if this issue can be corrected but i hope you can fix it, thanks.

**Comment by ChristosOwen** [comment]
You did talk to him after collecting the first pendant, right? He will do nothing if you don't have the pendant. If you do have it, he should always give you his item, even if it's junk or a downgrade of an item you already have. What was the seed number? Also, do you have a vod at all? 

Also, did you visit any Big/Great Faeries? There's a known bug that they can remove the pendants if so. However you should be able to go back to the Armos boss room and collect another if that's the case and then get the Sashrahla item?

**Comment by BlueViper85** [comment]
Uncertain if the submitter would have received a notice of this issue I sent them an email with a link to this issue and the notes from ChristosOwen above to ensure it was seen.

**Comment by MabhFox** [comment]
Hi, MabhFox here, so i followed the advice, went to the temple, got the first pendant again and immediately talked to him for the "missing" item.
I totally forgot to pay him a visit right after the dungeon until after i got the master sword, at that point he only talked to me without giving me anything, so getting the pendant fixed everything, thanks to everyone!

**Comment by ChristosOwen** [comment]
Think this was a simple case of not having the pendant, so going to close
