### ISSUE TITLE
[V6] gtower big key randomization

### ISSUE THREAD

**Issue by crusso109** [Dessyreqt/alttprandomizer#128]
[11:35 PM] josh: someone who knows github better than I do  and has an account
[11:36 PM] josh: please submit a report regarding big key in gtower
[11:36 PM] josh: 99.99% sure something is wrong with its randomization
[11:44 PM] Mishrak: i'll report it
[11:44 PM] Mishrak: do you have something more specific?
[11:45 PM] Mishrak: is it always spawning in the west wing chest behind the bomb spot?
[11:45 PM] Mishrak: @josh
[11:45 PM] josh: always spawns in either the warp maze bombwall room, above ice armos, and after ice armos
[11:46 PM] josh: *or not and lol

**Comment by BlueViper85** [comment]
Agreed. I have kept every ROM and spoiler log for every ROM I've generated, which is now 8 for v6. 7 of those have the big key in the room west of the teleport room and 1 is the room right above Armos.

**Comment by crusso109** [comment]
That's been my experience as well.  I haven't seen one in East side since v3 I think and they've pretty much all been west behind the bomb wall room or around ice armos.

**Comment by KatDevsGames** [comment]
Same here.

**Comment by ChristosOwen** [comment]
+1

**Comment by churine** [comment]
more specifically
west of teleport room [top right chest]
north of Armos room [left chest]
above Armos

it might be worth noting above ice armos seems to be rarer, happening to me only once out of like 10-20 seeds I checked

**Comment by KatDevsGames** [comment]
I get it in west of teleport room almost 50% of the time.

On September 2, 2016 6:28:27 PM EDT, zilarch notifications@github.com wrote:

> more specifically
> west of teleport room [top right chest]
> north of Armos room [left chest]
> 
> it might be worth noting above ice armos seems to be rarer, happening
> to me only once
> 
> ## 
> 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/Dessyreqt/alttprandomizer/issues/128#issuecomment-244501824

## 

Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by ChristosOwen** [comment]
This had been addressed and will be working correctly in v7.
