### ISSUE TITLE
[V6] Seed 1235467 Unbeatable

### ISSUE THREAD

**Issue by Straevaras** [Dessyreqt/alttprandomizer#131]
Bow is in PoD Big Chest and first key chest to the left contains Compass (also humorously both mitts are in PoD as well).

**Comment by It-s-Me** [comment]
I think you meant C1234567, where the bow is in the big key room.  But, yeah, the bow appears to be stuck behind [an area where you need the bow to continue](http://www.zeldadungeon.net/wiki/images/3/3f/Goriya-ALTTP.png).

**Comment by ChristosOwen** [comment]
Yep we know about this one and it'll be fixed in the next version - thanks guys and sorry for the oversight :(! This is logged already so going to close.
