### ISSUE TITLE
1/4 Magic not applied correctly with Cape

### ISSUE THREAD

**Issue by SmashManiac** [Dessyreqt/alttprandomizer#133]
When using the cape with 1/4 magic, the rate at which magic is consumed is 1/2 instead.

For example, in the Cane of Byrna cavern, there's only enough time to get to the other side with a full magic charge. It should be possible to get back to the entrance with the same charge.

Reproduced on V6 with seed C0414613.

**Comment by BlueViper85** [comment]
Timed how long it took to empty the magic meter using the cape:

-Unmodified magic: 8.5 seconds,
-1/2 Magic: 17 seconds.
-1/4 magic 17 seconds.  

This seems to confirm the existence of this bug.

I also timed with the Cane of Byrna:

-Unmodified magic: 12 seconds
-1/2 magic: 25 seconds
-1/4 magic: 50.5 seconds

All times were rounded down to the nearest half-second to accommodate for any human error on my part with starting/stopping the timer and item use.

Additionally all times were taken in Link's house with a full magic meter from under the first pot in Link's house. To ensure a consistent "test environment"

**Comment by KatDevsGames** [comment]
I'll modify the magic consumption of the cape to behave as one would normally expect. I've already located the byte in question.

**Comment by KatDevsGames** [comment]
Byte actually patched in trunk rom.
