### ISSUE TITLE
Dark Palace Big Key chest may contain small key

### ISSUE THREAD

**Issue by SmashManiac** [Dessyreqt/alttprandomizer#134]
It's possible that a small key is randomized inside the chest that normally contains the Big Key in the Dark Palace.

The problem is that a small key is required in order to reach this chest by unlocking the stairs door on the floor underneath. If all the other small keys have already been used, that chest is no longer reachable. Note that this doesn't prevent beating the game, but does prevent acquiring everything in the game.

Reproduced on V6 with seed C0414613.

**Comment by BlueViper85** [comment]
Key logic for PoD is already going to be updated for the next update which should solve any key locks in PoD.

**Comment by KatDevsGames** [comment]
All PoD issues moved to #123. Duplicate.

**Comment by BlueViper85** [comment]
Note, while this was referenced in issue #164, beyond the similar subject matter the two should be treated separately.
