### ISSUE TITLE
Suggestion: Configurable Agahnim "blue balls" attack

### ISSUE THREAD

**Issue by SmashManiac** [Dessyreqt/alttprandomizer#135]
The readme currently states the following:

> Some bugs that wouldn't crop up in normal play have been fixed:
> [...]
> - Occasionally Agahnim will attack you with particles that can't be reflected back at him. In randomizer, this doesn't happen.

First of all, I believe this patch should be in the enhancements list of the readme, not the bugs list. (It was even left in the GBA version.)

But more importantly, while I understand that encountering this attack is frustrating for speedrunning, it also makes Agahnim trivial for casual play, and consequently less fun in my opinion.

Therefore, I suggest disabling Agahnim's "blue balls" attack being an optional patch instead of a required one, either controlled by an independent setting or integrated as a separate "Speedrun" randomizer mode.

**Comment by BlueViper85** [comment]
Agahnim will not be updated to include Blue Balls.  It provides nothing of significant value to a Randomizer play through except unnecessarily adding time to the fight, especially if an important item is on the pyramid that allows you to progress.  Even with Blue Balls the fight is still fairly trivial if you stand far enough away from him and dodge them.

Nevermind that having hammer or moon pearl on the Pyramid and dying to Agahnim would be quite frustrating for someone, especially if you're in a hurry (speed runner or not).  Adding blue balls increases the chances of that, again without any positive benefit.

**Comment by KatDevsGames** [comment]
Issue already discussed and decided on during planning session in June. Not a bug.

**Comment by SmashManiac** [comment]
I believe your opinion is biased from your speedrunning experience. By the same logic, you could argue that Agahnim shouldn't even be in the game, or that all enemies and bosses should only have 1 HP because it takes too long to fight them. It would certainly be an interesting game, but it's arguable if it would be a better game.

I'm not sure what you consider valuable in a randomizer playthrough, but for me, it's playing the same game with a new challenge and some unexpected outcomes. Removing part of the challenge is not what I'm looking for, even if it's not much. And yes, it is an additional challenge, considering that dodging an unexpected unblockable attack requires more skill and strategy than just standing right in front of the guy and mashing the B button.

That said, I completely understand if you don't want to change this. I just wanted to share my point of view on the matter to ensure that you considered it.

**Comment by BlueViper85** [comment]
This isn't going to be changed either way. Thank you for your feedback!
