### ISSUE TITLE
[v6] Dark World - Temple 1 - Blackout Rooms

### ISSUE THREAD

**Issue by Dessyreqt** [Dessyreqt/alttprandomizer#136]
Submitter: Polymus
Email: polymus@live.com
[v6]
There are two particular rooms in this temple that go pitch black when you enter them, and the random light in front of you keeps not appear, making navigating them a pain. I did one round of randomizer where these rooms were not an issue, but most of the time this happens. Is this a glitch, or is there are particular reason?

**Comment by BlueViper85** [comment]
The light in dark rooms only appears if you have the Lantern item. In the light world it will always appear. With that in mind, the lantern will never be in a place that requires you to navigate a dark room to access. Keep looking and you should be able to find it and navigate the room more safely/easily.
