### ISSUE TITLE
Hammer and Titan's Mitt unreachable

### ISSUE THREAD

**Issue by Uiraya** [Dessyreqt/alttprandomizer#139]
Seed C19830827

 I absolutely adore this mod; thank you so much for making it. However, my first playthrough got me all the way up to the dark palace without finding either the hammer or the titan's mitt. 

Relevant part of the spoiler:
[cave-018] Graveyard - top right grave....................................................Hammer
[cave-073] cave northeast of swamp palace [bottom chest]..................................Lamp
[dungeon-D3-B1] Skull Woods - east of Fire Rod room.......................................Titan's Mitt
[cave-062] C-shaped house.................................................................Ocarina

As we all know, I can't access any of the warps due to needing either the hammer or mitt (or both), and I can't access the rest of the dark world without the hammer. I'm pretty sure I can DMD into the graveyard and get things going that way but that feels like a fairly unintuitive glitch that shouldn't be necessary. Am I missing something else? Thanks!

**Comment by BlueViper85** [comment]
Glad to hear you're enjoying Randomizer!

I've looked at the spoiler log and this seed does IS beatable.

I'll leave this more generic for you, if you want to know where individual items are you can check the spoiler log or I'll be happy to tell you if you ask;

The cape, hookshot, and mirror are easily accessible.  By the looks of it you can access everything you need o get to the dark world by beating Agahnim.  All items are available to beat the three Light World dungeons OR you can use the cape to get past the barrier to Agahnim's Tower. 

So once you've beat Agahnim's Tower, walk down the pyramid and go right one screen, then follow the path up.  After you pass the broken bridge you'll see a spot with some rocks you can lift (or a peg you can hit with the hammer).  Right above that is a small break in the barrier along the water's edge.  Use the hookshot here (facing left) and it will take you across the river.

Once you're across the river walk up and follow the path to the grave yard.  The cave where the hammer is can be accessed by destroying a bush (you have to walk behind a statue, but I guarantee you can get there).  Alternatively you can keep walking to get to Skull Woods at this point and get the Titan's Mitt from that dungeon.

Hopefully this helps!  If you need any clarification please comment here and I'll be happy to help!

**Comment by Uiraya** [comment]
Had no idea you could hookshot there. That was it. Thanks!

**Comment by BlueViper85** [comment]
Excellent!  Hope you continue to have fun with it!
