### ISSUE TITLE
Don't think Seed C7057498 V6 is beatable without glitches.

### ISSUE THREAD

**Issue by ShittyCumSquats** [Dessyreqt/alttprandomizer#142]
[cave-057-1F] Dark World Death Mountain - cave from top to bottom [top chest].............Hammer

A quick search shows me that Cave 57 happens to be this cave: http://www.zeldaeurope.de/galerie/albums/gallery/Z3A/maps/normal_cave-057-1F.png which is after the ring of pegs to the right of the Tower of Hera IIRC.

**Comment by BlueViper85** [comment]
Checked the spoiler log to confirm complete-ability.  The Mirror, Hookshot, Titan's Mitts, and Moon Pearl are all accessible without the Hammer which means you can access the hammer.  Go to Death Mountain, walk to the east side of the lower portion and you will find a broken bridge.  Hookshot across the bridge, and there is a dark rock towards the bottom of this area that you can lift (with the Titan's Mitts) and it will take you to the dark world.  In this area are a series of caves which will allow you to access the Hammer.
