### ISSUE TITLE
broken seed C0000777

### ISSUE THREAD

**Issue by Dessyreqt** [Dessyreqt/alttprandomizer#144]
Submitter: Cronofighter
Email: paraptor@web.de
the bow in this seed in the dark palace behind a key door. but to get a key you must kill a red rat that can only be killed with bow

**Comment by ChristosOwen** [comment]
Same issue as #123 which is already logged and the fix known.

Sorry Cronofighter, we're aware of this and it will be fixed for the next release! Thanks for letting us know, hopefully you won't run into anymore issues until then. Happy gaming :)
