### ISSUE TITLE
[v6] Missing Medallion? (C4987198)

### ISSUE THREAD

**Issue by kishprime** [Dessyreqt/alttprandomizer#145]
Thanks so much for this amazing mod!

To start with, the Hobo chest is the chest you take to the hobo, right? My seed spoiler says that the Bombos medallion was in that chest (I can't remember what it was though I do remember doing it swordless), yet it is not in my inventory and I see no chest (the save state is at the Blacksmith's in Dark World). I need it to progress since the Fire Rod is in the Ice Palace.

Am I crazy or did the medallion disappear somehow, or did I get a different item from the chest? Thanks for all you guys are doing with this, having a great time.

[ALttP Random - C4987198.zip](https://github.com/Dessyreqt/alttprandomizer/files/465741/ALttP.Random.-.C4987198.zip)

**Comment by KatDevsGames** [comment]
There is no chest you take to the hobo. You take the purple chest to the 
desert thief, not the hobo. Please clarify.

**Comment by kishprime** [comment]
Well that was my mistake then.  Which is the hobo?

Sorry, did extensive google searching and he was the only one that came up.

**Comment by KatDevsGames** [comment]
The hobo is at this location: 
http://www.zeldadungeon.net/Zelda03/Bottles/03.png

The bridge you are under in this screenshot is the same bridge that 
would have hammer pegs in the DW version. Go under it in the LW (swim 
under it from the right) and you'll meet the hobo.

**Comment by kishprime** [comment]
Got it. Sorry for reporting! Figured it was something stupid on my part. :)

**Comment by BlueViper85** [comment]
The "Hobo" is the guy who lives under the Bridge in Light World, where you would normally get a bottle.  Swim to him from Lake Hylia.

The chest that you took to the lockpicking thief will appear in the spoiler log as "Purple Chest."

[Edit: You all move quickly :) ]

**Comment by KatDevsGames** [comment]
Thanks for playing and we hope you keep enjoying randomizer.
