### ISSUE TITLE
Seed C2847439 not beatable

### ISSUE THREAD

**Issue by Agrahnax** [Dessyreqt/alttprandomizer#148]
Hey,
I've been playing this seed and it was quite enjoyable up to the point where I got stuck and ran out of ideas where to get new items from. So I took a look at the spoiler-log and I think I can't get the boots and the bow as they seem to exclude each other.
The bow is west of the cathedral under x-block and the boots are in the spike-room of dark palace and I need to kill the red rat in order to get there. This might be related to a similar problem which others posted where the bow was inside dark palace but I decided to let you know anyways.

**Comment by Myramong** [comment]
This issue is already known, ChristosOwen talks about the fix [at the end of issue #123](https://github.com/Dessyreqt/alttprandomizer/issues/123)

Thanks for the report.

**Comment by BlueViper85** [comment]
As mentioned, this is part of the other issue, and will be tracked there.  Closing this issue.
