### ISSUE TITLE
Seed C4190546 possibly not beatable?

### ISSUE THREAD

**Issue by ghost** [Dessyreqt/alttprandomizer#149]
I haven't had any problems until getting walled by dungeon 6 and 7 (Misery Mire and Turtle Rock). The problem is that I can't find the Cane of Somaria anywhere. I've been extremely thorough about chest/item locations, but I can't find it anywhere. And of course, the cane of somaria is completely necessary to progress in dungeons 6 and 7.

If someone could tell me whether or not the seed is beatable, I would appreciate it.

**Comment by BlueViper85** [comment]
You can generate a spoiler log when you generate the ROM (and you can re-generate it and the ROM without issue if you didn't when you first created the ROM).

That being said, I looked at the spoiler log for this seed and the Cane of Somaria is accessible by talking to Sahasrahla after beating Eastern Palace and getting the Pendant of Courage.
