### ISSUE TITLE
[v6] game break

### ISSUE THREAD

**Issue by Dessyreqt** [Dessyreqt/alttprandomizer#150]
Submitter: Tantalus-X
Email: Tantalus-X@hotmail.de
hello have problem i cane not to dark world

 i can not to hammer titensglove or powerglove

[cave-018] Graveyard - top right grave....................................................Hammer   < most have Power glove or hammer  enter dark world
[dungeon-A2-1F] Ganon's Tower - west of teleport room [top right chest]...................Power Glove < most have all 7 jewels ^^
Piece of Heart (Lumberjack Tree)..........................................................Titan's Mitt < problem Lumberjack block me ^^

Ps: in Ganon's Tower and dungeon 6 have end 1 key not used is normal have all door and rooms completed

sorry for bad englisch
## A Link to the Past Randomizer Log

Version: 6
Creation Date: 15.09.2016 14:35:20
Seed: C491501716
## Generated Item Order

[cave-050] cave southwest of Lake Hylia [top right chest].................................Ocarina
Old mountain man..........................................................................Bottle (Bee)
[cave-050] cave southwest of Lake Hylia [bottom right chest]..............................Hookshot
[cave-022-B1] Thief's hut [top chest].....................................................Pegasus Boots
[cave-009-1F] Death Mountain - wall of caves - right cave [top left middle chest].........Cape
Piece of Heart (Lumberjack Tree)..........................................................Titan's Mitt
[cave-018] Graveyard - top right grave....................................................Hammer
[cave-021] Kakariko well [bottom chest]...................................................Flippers
[dungeon-C-B1] Escape - final basement room [left chest]..................................Book of Mudora
King Zora.................................................................................Magic Mirror
[cave-009-1F] Death Mountain - wall of caves - right cave [top right middle chest]........Mushroom
[dungeon-L1-1F] Eastern Palace - big chest................................................Shovel
[dungeon-C-B1] Escape - final basement room [right chest].................................Bow
[cave-009-1F] Death Mountain - wall of caves - right cave [top left chest]................Fire Rod
Hobo......................................................................................Moon Pearl
Piece of Heart (Death Mountain - floating island).........................................Lamp
[cave-056] Dark World Death Mountain - cave under boulder [bottom right chest]............Bombos
[dungeon-D6-B1] Misery Mire - big chest...................................................Cane of Somaria
[cave-073] cave northeast of swamp palace [bottom middle chest]...........................Ice Rod
## Light World

[cave-009-1F] Death Mountain - wall of caves - right cave [bottom chest]..................20 Rupees
[cave-009-1F] Death Mountain - wall of caves - right cave [top left chest]................Fire Rod
[cave-009-1F] Death Mountain - wall of caves - right cave [top left middle chest].........Cape
[cave-009-1F] Death Mountain - wall of caves - right cave [top right chest]...............300 Rupees
[cave-009-1F] Death Mountain - wall of caves - right cave [top right middle chest]........Mushroom
[cave-009-B1] Death Mountain - wall of caves - right cave [left chest]....................3 Bombs
[cave-009-B1] Death Mountain - wall of caves - right cave [right chest]...................Ether
[cave-012-1F] Death Mountain - wall of caves - left cave..................................1 Rupee
[cave-013] Mimic cave (from Turtle Rock)..................................................Piece of Heart
[cave-016] cave under rocks west of Santuary..............................................10 Arrows
[cave-018] Graveyard - top right grave....................................................Hammer
[cave-021] Kakariko well [bottom chest]...................................................Flippers
[cave-021] Kakariko well [center chest row of 3]..........................................20 Rupees
[cave-021] Kakariko well [left chest row of 3]............................................Piece of Heart
[cave-021] Kakariko well [right chest row of 3]...........................................100 Rupees
[cave-021] Kakariko well [top chest]......................................................20 Rupees
[cave-022-B1] Thief's hut [bottom left chest].............................................3 Bombs
[cave-022-B1] Thief's hut [bottom right chest]............................................Piece of Heart
[cave-022-B1] Thief's hut [top chest].....................................................Pegasus Boots
[cave-022-B1] Thief's hut [top left chest]................................................Piece of Heart
[cave-022-B1] Thief's hut [top right chest]...............................................Blue Mail
[cave-026] chicken house..................................................................3 Bombs
[cave-031] Tavern.........................................................................100 Rupees
[cave-034] Hyrule Castle secret entrance..................................................100 Rupees
[cave-035] Sahasrahla's Hut [center chest]................................................3 Bombs
[cave-035] Sahasrahla's Hut [left chest]..................................................50 Rupees
[cave-035] Sahasrahla's Hut [right chest].................................................20 Rupees
[cave-040] Link's House...................................................................20 Rupees
[cave-044] Aginah's cave..................................................................10 Arrows
[cave-047] Dam............................................................................Red Boomerang
[cave-050] cave southwest of Lake Hylia - generous guy....................................20 Rupees
[cave-050] cave southwest of Lake Hylia [bottom left chest]...............................50 Rupees
[cave-050] cave southwest of Lake Hylia [bottom right chest]..............................Hookshot
[cave-050] cave southwest of Lake Hylia [top left chest]..................................Quake
[cave-050] cave southwest of Lake Hylia [top right chest].................................Ocarina
[cave-051] Ice Cave.......................................................................Piece of Heart
Bombos....................................................................................3 Bombs
Bottle Vendor.............................................................................20 Rupees
Ether.....................................................................................Staff of Byrna
Haunted Grove item........................................................................Bottle (Red Potion)
Hobo......................................................................................Moon Pearl
King Zora.................................................................................Magic Mirror
Library...................................................................................20 Rupees
Mushroom..................................................................................3 Bombs
Old mountain man..........................................................................Bottle (Bee)
Piece of Heart (Dam)......................................................................50 Rupees
Piece of Heart (Death Mountain - floating island).........................................Lamp
Piece of Heart (Desert - northeast corner)................................................20 Rupees
Piece of Heart (Desert - west side).......................................................Bug-Catching Net
Piece of Heart (Graveyard)................................................................3 Bombs
Piece of Heart (Lake Hylia)...............................................................Piece of Heart
Piece of Heart (Lumberjack Tree)..........................................................Titan's Mitt
Piece of Heart (Maze Race)................................................................20 Rupees
Piece of Heart (south of Haunted Grove)...................................................3 Bombs
Piece of Heart (Spectacle Rock Cave)......................................................Piece of Heart
Piece of Heart (Spectacle Rock)...........................................................20 Rupees
Piece of Heart (Thieves' Forest Hideout)..................................................3 Bombs
Piece of Heart (Zora's River).............................................................Piece of Heart
Purple Chest..............................................................................Boomerang
Sahasrahla................................................................................Heart Container
Sick Kid..................................................................................Piece of Heart
Witch.....................................................................................Piece of Heart
## Dark World

[cave-055] Spike cave.....................................................................50 Rupees
[cave-056] Dark World Death Mountain - cave under boulder [bottom left chest].............10 Arrows
[cave-056] Dark World Death Mountain - cave under boulder [bottom right chest]............Bombos
[cave-056] Dark World Death Mountain - cave under boulder [top left chest]................10 Arrows
[cave-056] Dark World Death Mountain - cave under boulder [top right chest]...............Piece of Heart
[cave-057-1F] Dark World Death Mountain - cave from top to bottom [bottom chest]..........50 Rupees
[cave-057-1F] Dark World Death Mountain - cave from top to bottom [top chest].............50 Rupees
[cave-062] C-shaped house.................................................................10 Arrows
[cave-063] doorless hut...................................................................3 Bombs
[cave-071] Misery Mire west area [left chest].............................................100 Rupees
[cave-071] Misery Mire west area [right chest]............................................10 Arrows
[cave-073] cave northeast of swamp palace - generous guy..................................1 Arrow
[cave-073] cave northeast of swamp palace [bottom chest]..................................20 Rupees
[cave-073] cave northeast of swamp palace [bottom middle chest]...........................Ice Rod
[cave-073] cave northeast of swamp palace [top chest].....................................Red Mail
[cave-073] cave northeast of swamp palace [top middle chest]..............................10 Arrows
Catfish...................................................................................Piece of Heart
Flute Boy.................................................................................10 Arrows
Piece of Heart (Dark World - bumper cave).................................................Bottle (Green Potion)
Piece of Heart (Dark World blacksmith pegs)...............................................3 Bombs
Piece of Heart (Digging Game).............................................................3 Bombs
Piece of Heart (Pyramid)..................................................................20 Rupees
Piece of Heart (Treasure Chest Game)......................................................300 Rupees
## Hyrule Castle Escape

[dungeon-C-1F] Sanctuary..................................................................3 Bombs
[dungeon-C-B1] Escape - final basement room [left chest]..................................Book of Mudora
[dungeon-C-B1] Escape - final basement room [middle chest]................................300 Rupees
[dungeon-C-B1] Escape - final basement room [right chest].................................Bow
[dungeon-C-B1] Escape - first B1 room.....................................................Map
[dungeon-C-B1] Hyrule Castle - boomerang room.............................................3 Bombs
[dungeon-C-B1] Hyrule Castle - map room...................................................3 Bombs
[dungeon-C-B3] Hyrule Castle - next to Zelda..............................................Key
## Eastern Palace

[dungeon-L1-1F] Eastern Palace - big ball room............................................Map
[dungeon-L1-1F] Eastern Palace - big chest................................................Shovel
[dungeon-L1-1F] Eastern Palace - Big key..................................................20 Rupees
[dungeon-L1-1F] Eastern Palace - compass room.............................................Compass
[dungeon-L1-1F] Eastern Palace - map room.................................................Big Key
## Desert Palace

[dungeon-L2-B1] Desert Palace - big chest.................................................Map
[dungeon-L2-B1] Desert Palace - Big key room..............................................Compass
[dungeon-L2-B1] Desert Palace - compass room..............................................Piece of Heart
[dungeon-L2-B1] Desert Palace - Map room..................................................Big Key
## Tower of Hera

[dungeon-L3-1F] Tower of Hera - first floor...............................................Map
[dungeon-L3-2F] Tower of Hera - Entrance..................................................Big Key
[dungeon-L3-4F] Tower of Hera - 4F [small chest]..........................................20 Rupees
[dungeon-L3-4F] Tower of Hera - big chest.................................................Compass
## Hyrule Castle Tower

[dungeon-A1-2F] Hyrule Castle Tower - 2 knife guys room...................................Key
[dungeon-A1-3F] Hyrule Castle Tower - maze room...........................................Key
## Dark Palace

[dungeon-D1-1F] Dark Palace - big chest...................................................Compass
[dungeon-D1-1F] Dark Palace - big key room................................................Key
[dungeon-D1-1F] Dark Palace - compass room................................................Piece of Heart
[dungeon-D1-1F] Dark Palace - jump room [left chest]......................................Key
[dungeon-D1-1F] Dark Palace - jump room [right chest].....................................Map
[dungeon-D1-1F] Dark Palace - maze room [bottom chest]....................................Key
[dungeon-D1-1F] Dark Palace - maze room [top chest].......................................Big Key
[dungeon-D1-1F] Dark Palace - spike statue room...........................................20 Rupees
[dungeon-D1-1F] Dark Palace - statue push room............................................Key
[dungeon-D1-B1] Dark Palace - room leading to Helmasaur [left chest]......................20 Rupees
[dungeon-D1-B1] Dark Palace - room leading to Helmasaur [right chest].....................Piece of Heart
[dungeon-D1-B1] Dark Palace - shooter room................................................Key
[dungeon-D1-B1] Dark Palace - turtle stalfos room.........................................Key
## Swamp Palace

[dungeon-D2-1F] Swamp Palace - first room.................................................Key
[dungeon-D2-B1] Swamp Palace - big chest..................................................20 Rupees
[dungeon-D2-B1] Swamp Palace - big key room...............................................300 Rupees
[dungeon-D2-B1] Swamp Palace - map room...................................................20 Rupees
[dungeon-D2-B1] Swamp Palace - push 4 blocks room.........................................Map
[dungeon-D2-B1] Swamp Palace - south of hookshot room.....................................1 Rupee
[dungeon-D2-B2] Swamp Palace - flooded room [left chest]..................................Big Key
[dungeon-D2-B2] Swamp Palace - flooded room [right chest].................................20 Rupees
[dungeon-D2-B2] Swamp Palace - hidden waterfall door room.................................Compass
## Skull Woods

[dungeon-D3-B1] Skull Woods - big chest...................................................Compass
[dungeon-D3-B1] Skull Woods - Big Key room................................................Piece of Heart
[dungeon-D3-B1] Skull Woods - Compass room................................................Key
[dungeon-D3-B1] Skull Woods - east of Fire Rod room.......................................Key
[dungeon-D3-B1] Skull Woods - Entrance to part 2..........................................Map
[dungeon-D3-B1] Skull Woods - Gibdo/Stalfos room..........................................Big Key
[dungeon-D3-B1] Skull Woods - south of Fire Rod room......................................Key
## Thieves Town

[dungeon-D4-1F] Thieves' Town - Room above boss...........................................Piece of Heart
[dungeon-D4-B1] Thieves' Town - Bottom left of huge room [bottom right chest].............Big Key
[dungeon-D4-B1] Thieves' Town - Bottom left of huge room [top left chest].................Key
[dungeon-D4-B1] Thieves' Town - Bottom right of huge room.................................Piece of Heart
[dungeon-D4-B1] Thieves' Town - Top left of huge room.....................................Compass
[dungeon-D4-B2] Thieves' Town - big chest.................................................Map
[dungeon-D4-B2] Thieves' Town - next to Blind.............................................50 Rupees
## Ice Palace

[dungeon-D5-B1] Ice Palace - Big Key room.................................................100 Rupees
[dungeon-D5-B1] Ice Palace - compass room.................................................Big Key
[dungeon-D5-B2] Ice Palace - map room.....................................................Key
[dungeon-D5-B3] Ice Palace - spike room...................................................Key
[dungeon-D5-B4] Ice Palace - above Blue Mail room.........................................Map
[dungeon-D5-B5] Ice Palace - b5 up staircase..............................................Piece of Heart
[dungeon-D5-B5] Ice Palace - big chest....................................................Compass
## Misery Mire

[dungeon-D6-B1] Misery Mire - big chest...................................................Cane of Somaria
[dungeon-D6-B1] Misery Mire - big hub room................................................Key
[dungeon-D6-B1] Misery Mire - big key.....................................................Key
[dungeon-D6-B1] Misery Mire - compass.....................................................Compass
[dungeon-D6-B1] Misery Mire - end of bridge...............................................Big Key
[dungeon-D6-B1] Misery Mire - map room....................................................Key
[dungeon-D6-B1] Misery Mire - spike room..................................................Map
## Turtle Rock

[dungeon-D7-1F] Turtle Rock - Chain chomp room............................................Big Key
[dungeon-D7-1F] Turtle Rock - compass room................................................Map
[dungeon-D7-1F] Turtle Rock - Map room [left chest].......................................Key
[dungeon-D7-1F] Turtle Rock - Map room [right chest]......................................Key
[dungeon-D7-B1] Turtle Rock - big chest...................................................Compass
[dungeon-D7-B1] Turtle Rock - big key room................................................Key
[dungeon-D7-B1] Turtle Rock - Roller switch room..........................................Piece of Heart
[dungeon-D7-B2] Turtle Rock - Eye bridge room [bottom left chest].........................10 Arrows
[dungeon-D7-B2] Turtle Rock - Eye bridge room [bottom right chest]........................20 Rupees
[dungeon-D7-B2] Turtle Rock - Eye bridge room [top left chest]............................Piece of Heart
[dungeon-D7-B2] Turtle Rock - Eye bridge room [top right chest]...........................Key
## Ganon's Tower

[dungeon-A2-1F] Ganon's Tower - above Armos...............................................Big Key
[dungeon-A2-1F] Ganon's Tower - big chest.................................................3 Bombs
[dungeon-A2-1F] Ganon's Tower - compass room [bottom left chest]..........................100 Rupees
[dungeon-A2-1F] Ganon's Tower - compass room [bottom right chest].........................20 Rupees
[dungeon-A2-1F] Ganon's Tower - compass room [top left chest].............................Bottle (Blue Potion)
[dungeon-A2-1F] Ganon's Tower - compass room [top right chest]............................20 Rupees
[dungeon-A2-1F] Ganon's Tower - down right staircase from entrance [left chest]...........Magic Powder
[dungeon-A2-1F] Ganon's Tower - down right staircase from entrance [right chest]..........Map
[dungeon-A2-1F] Ganon's Tower - east of down right staircase from entrace.................3 Bombs
[dungeon-A2-1F] Ganon's Tower - map room..................................................Key
[dungeon-A2-1F] Ganon's Tower - north of gap room [bottom left chest].....................Compass
[dungeon-A2-1F] Ganon's Tower - north of gap room [bottom right chest]....................Key
[dungeon-A2-1F] Ganon's Tower - north of gap room [top left chest]........................10 Arrows
[dungeon-A2-1F] Ganon's Tower - north of gap room [top right chest].......................Red Shield
[dungeon-A2-1F] Ganon's Tower - north of teleport room....................................Piece of Heart
[dungeon-A2-1F] Ganon's Tower - west of teleport room [bottom left chest].................5 Rupees
[dungeon-A2-1F] Ganon's Tower - west of teleport room [bottom right chest]................20 Rupees
[dungeon-A2-1F] Ganon's Tower - west of teleport room [top left chest]....................Piece of Heart
[dungeon-A2-1F] Ganon's Tower - west of teleport room [top right chest]...................Power Glove
[dungeon-A2-6F] Ganon's Tower - before Moldorm............................................5 Rupees
[dungeon-A2-6F] Ganon's Tower - Moldorm room..............................................10 Arrows
[dungeon-A2-6F] Ganon's Tower - north of falling floor four torches [top left chest]......20 Rupees
[dungeon-A2-6F] Ganon's Tower - north of falling floor four torches [top right chest].....20 Rupees
[dungeon-A2-B1] Ganon's Tower - north of Armos room [bottom chest]........................Piece of Heart
[dungeon-A2-B1] Ganon's Tower - north of Armos room [left chest]..........................Mirror Shield
[dungeon-A2-B1] Ganon's Tower - north of Armos room [right chest].........................Key
## Special Locations

Magic Bat.................................................................................1/4 Magic
Misery Mire Required Medallion............................................................Bombos
Pyramid Bottle Item.......................................................................Bottle (Bee)
Turtle Rock Required Medallion............................................................Bombos
Waterfall Bottle Item.....................................................................Bottle (Gold Bee)

**Comment by BlueViper85** [comment]
Thanks for providing the full spoiler log, it makes this all a lot easier. Hope you're enjoying Randomizer!

You are not stuck. You will need to use the cape to bypass the barrier to enter Agahnim's tower. Once you defeat Agahnim you can access the Titan's Mitts. You can ignore the Power Gloves.

As for the keys in Ganon's Tower and Misery Mire? Both had useless key doors removed making it much more likely that you will have an extra key. This is known and expected.

Thanks!

**Comment by Chidsuey** [comment]
If you can get to the Dark World, you can also get under the top right grave. Go there in the Dark World, and use the magic mirror in that closed off area. Charged up your sword, facing the grave, and back up against the titan blocks. This will give you enough room to dash with the boots and open.

What's more concerning about this seed to me is the hobo with the moon pearl. You can't swim as a bunny so I don't know how the moon pearl would be obtainable.

**Comment by BlueViper85** [comment]
The hobo is in the light world under the bridge, the moon pearl is not necessary to get to him at all.

**Comment by Chidsuey** [comment]
But the designed method to get there is to go to the dark world, jump down into the water, and use the magic mirror to get back to the light world. How is it obtainable only using the light world?

**Comment by BlueViper85** [comment]
There isn't a single designed method.  You can swim there from Lake Hylia.

**Comment by Chidsuey** [comment]
Son of a...

You can. Man this project is great. I'm learning new things all the time. Thanks!

**Comment by meteormage** [comment]
You can use the infinite flipper glitch to get there without flippers
