### ISSUE TITLE
Seed C8257595 unbeatable 

### ISSUE THREAD

**Issue by dorsey43** [Dessyreqt/alttprandomizer#152]
It seems that this seed is unbeatable; The Titan's Mitt is in the cave NE of the Swamp Palace which requires the Hammer (or the mitt itself) and the Hammer is under a bolder on dark world Death Mountain, requiring the Mitt. Am I missing something?

Cheers, and thanks

**Comment by BlueViper85** [comment]
This seed is beatable.  Presuming that you've gained access to the dark world at this point, if you go to the Pyramid and then walk one screen right, then follow the path up until you reach an area with some rocks and a hammer peg (just north of the bridge).  With the power gloves you can lift one of these rocks.  Just after that area you'll see a small break in the barrier next to the river.  While you can't see it, you can use the hookshot to grab ahold of some skulls on the other side. This gives you access to the rest of Dark World.

Unfortunately this does mean you essentially have to walk all the way around the map just to get the hammer, but rest assured, it is do-able and there's plenty of other things to do on the way the way (dungeons, chests, etc...)

All of the items I mentioned here are accessible to you, but I opted not to say where specifically things are.  But if you need additional info, please respond here or check the spoiler log.

Thanks, and hope you continue to have fun with Randomizer!
