### ISSUE TITLE
Shovel Dashing

### ISSUE THREAD

**Issue by MinoWizard** [Dessyreqt/alttprandomizer#153]
I'm not sure if this is a bug or a suggestion, but I figured I'd post it here anyway.

So, using the item dash glitch has some interesting effects. Including the shovel. I find it personally a bit amusing how you can leave a trail of holes dug behind you in an instant as you breeze by.

Although, at this point, it's not good for much else besides amusement, since you don't actually get anything from it.

I was also wondering if it could somehow be used to quickly dig out 15 holes in the digging minigame, but it seems to not count towards the digging game at all, and I wasn't able to get anything.

I know it's not a very critical bug, so it wouldn't surprise me if it wasn't fixed, but since the item dash is here, and the addition to make digging useful in different areas with random treasure rewards, it'd make sense to have the two synergize. That's ultimately up to you guys though.

**Comment by KatDevsGames** [comment]
I'm not sure if it's a bug or a suggestion either? It's something to be discussed. It's like this in vanilla alttp if you hold on to the shovel. Item dashing with the shovel could certainly be fixed. Whether or we actually should is a different question. Personally, I'm not sure either way.

**Comment by MinoWizard** [comment]
Thing is, thinking about it from a racing perspective, I can only think of one case I'd find it helpful, and that's shovel dashing to the ocarina spot. 

The previously mentioned digging game still has a timer on it, but I'm pretty sure you could leave early.

See, I normally wouldn't have considered this, however, adding normal dig spots in the game to give the shovel more utility, leads me to believe that since the standard item behavior is changed, maybe the dashing behavior should as well.

Though, now I'm curious if this does bring up a different bug. If the item digging game doesn't pull up anything with an item dash, what about the ocarina spot itself? I wonder if that could potentially make it unobtainable. Unlikely, but I'll start a new file to try and test it

EDIT: Well, I found a pretty lucky seed when using the randomizer. Here it is if you're interested. C6037076

Just complete hyrule castle, then go to Kakariko, down the well. Open the 4 chests, and bomb the wall. You should get a few bombs, 300 rupees, and the shovel, then in the bombed wall, you get an empty bottle, so you can talk to the sick kid who has the boots.

Turns out, there's a giant tree in the way, so much for item dashing the ocarina spot. You might as well walk the 4 tiles around it. You don't get the item itself by dashing the spot from the side though. So, if this was changed, it'd either be to make resource gathering for things like bombs or arrows be easier in the early game, though, I do recall seeing another issue of infinitely diggable spots that was a concern for balance, so maybe the shovel isn't the best of ideas. Like I said, the only time saver I can reasonably think of it the shovel digging minigame which also doesn't work, and just leaving early after getting the item.

**Comment by KatDevsGames** [comment]
I believe if you shovel dash the flute spot it will simply not spawn until you reload the screen and dig it up normally.

On September 16, 2016 8:12:00 AM EDT, RainyKitsune notifications@github.com wrote:

> Thing is, thinking about it from a racing perspective, I can only think
> of one case I'd find it helpful, and that's shovel dashing to the
> ocarina spot. 
> 
> The previously mentioned digging game still has a timer on it, but I'm
> pretty sure you could leave early.
> 
> See, I normally wouldn't have considered this, however, adding normal
> dig spots in the game to give the shovel more utility, leads me to
> believe that since the standard item behavior is changed, maybe the
> dashing behavior should as well.
> 
> Though, now I'm curious if this does bring up a different bug. If the
> item digging game doesn't pull up anything with an item dash, what
> about the ocarina spot itself? I wonder if that could potentially make
> it unobtainable. Unlikely, but I'll start a new file to try and test it
> 
> ## 
> 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/Dessyreqt/alttprandomizer/issues/153#issuecomment-247585252

## 

Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by MinoWizard** [comment]
Yeah. I tested that and edited the comment appropriately. That's exactly what happened. I'll go ahead and repaste the edit I made.

EDIT: Well, I found a pretty lucky seed when using the randomizer. Here it is if you're interested. C6037076

Just complete hyrule castle, then go to Kakariko, down the well. Open the 4 chests, and bomb the wall. You should get a few bombs, 300 rupees, and the shovel, then in the bombed wall, you get an empty bottle, so you can talk to the sick kid who has the boots.

Turns out, there's a giant tree in the way, so much for item dashing the ocarina spot. You might as well walk the 4 tiles around it. You don't get the item itself by dashing the spot from the side though. So, if this was changed, it'd either be to make resource gathering for things like bombs or arrows be easier in the early game, though, I do recall seeing another issue of infinitely diggable spots that was a concern for balance, so maybe the shovel isn't the best of ideas. Like I said, the only time saver I can reasonably think of is the digging minigame, and just leaving early after getting the item.

**Comment by BlueViper85** [comment]
While not exactly crucial, with the addition of being able to dig up various items on the overworld with Randomizer, there is some additional benefit to digging long stretches if you're looking for specific items.

Otherwise, the digging game is fairly short already.  I don't see this adding a lot of tangible value to "correcting" this item dash myself.

**Comment by ChristosOwen** [comment]
Pros: makes digging game slightly faster, allows you to quickly dig up rupees, bombs, magic, health, arrows, etc

Cons: makes bomb/arrow/rupee management less crucial, potential to cause a lot of lag?

I feel like it would be too "powerful" to simply shovel dash a huge stretch and hoard everything, personally, since it takes away from management of your resources. If you manage them poorly and want to use the shovel to try and replenish your items, it should be the standard dig speed from vanilla.

That said, I'm not hugely fussed either way as it is pretty cool.

**Comment by SmashManiac** [comment]
I'm personally against the idea of updating the core gameplay of ALttP by doing a change like this, considering this issue is completely independent of the randomization. Item dash was removed in later revisions of the game, so making it more powerful goes completely against the intent of the original game designers. For me, this is more important than making gameplay faster for speedrunning's sake.

That said, I would be OK with having such a change implemented, but I would really appreciate if speedrun-related changes like this would be optional, as I previously suggested in issue #135.

**Comment by MinoWizard** [comment]
I'm not quite certain myself. In the base game, the shovel only digs up that spot, and the digging game. Otherwise, there's no loot in the original game.

The shovel dash in the normal game already doesnt' do anything, because it was never really meant to. It was suppoused to be used for that quest primarily and only, aside from the digging game.

That's why shovel dashing doesn't do anything normally.

However, since the behavior has changed to allow the shovel to spawn items in normal play, the question now becomes if the shovel dash is needed to spawn items. It'd be interesting.

**Comment by ChristosOwen** [comment]
Decided not to implement this - too different from vanilla.
