### ISSUE TITLE
[V6] Seed C6969835 Unbeatable?

### ISSUE THREAD

**Issue by Eppy37** [Dessyreqt/alttprandomizer#156]
My friend managed to stumble upon another interesting most likely broken seed. 

The Magic Mirror and Bow are the main problems with this one. 

The Magic Mirror spawns in the Dark Palace Big Key room. The problem here is that the only chest you can reach has the Big Key, and you're blocked by a lock door when heading to the big key area and the path that leads to more chests are blocked by enemies that need the bow to kill(Unless it's possible to kill those red enemies with something other than the bow.)

The Bow spawns in the Swamp Palace which requires the Magic Mirror to get past the first room.

**Comment by BlueViper85** [comment]
This appears to be related to known issues with the logic for Palace of Darkness where the bow is not properly considered as a requirement in these kinds of situations. This will be fixed as part of issue #123.  I'm closing this issue to prevent duplicates.

Thanks for your feedback, we appreciate it. Please let us know if you have any questions or see anything else out of the oridinary or unexpected. Hope you continue to enjoy randomizer!
