### ISSUE TITLE
Truly unbeatable seed - C3842333

### ISSUE THREAD

**Issue by IgiariValkyr** [Dessyreqt/alttprandomizer#157]
## A Link to the Past Randomizer Log

Version: 6
Creation Date: 9/16/2016 2:27:07 PM
Seed: C3842333
## Generated Item Order

[dungeon-L1-1F] Eastern Palace - map room.................................................Bottle (Gold Bee)
[cave-021] Kakariko well [left chest row of 3]............................................Bow
[cave-050] cave southwest of Lake Hylia [top right chest].................................Power Glove
[cave-050] cave southwest of Lake Hylia [bottom left chest]...............................Pegasus Boots
King Zora.................................................................................Hammer
[cave-026] chicken house..................................................................Moon Pearl
Catfish...................................................................................Titan's Mitt
[dungeon-D4-B1] Thieves' Town - Bottom left of huge room [top left chest].................Flippers
[dungeon-C-B1] Escape - final basement room [right chest].................................Mushroom
[cave-035] Sahasrahla's Hut [left chest]..................................................Bombos
Piece of Heart (Pyramid)..................................................................Lamp
[cave-073] cave northeast of swamp palace [top middle chest]..............................Ocarina
[dungeon-D1-B1] Dark Palace - room leading to Helmasaur [left chest]......................Cape
Flute Boy.................................................................................Ether
Sick Kid..................................................................................Shovel
[dungeon-C-B1] Escape - final basement room [middle chest]................................Hookshot
[cave-009-1F] Death Mountain - wall of caves - right cave [top right chest]...............Magic Mirror
Piece of Heart (Dark World - bumper cave).................................................Book of Mudora
Piece of Heart (south of Haunted Grove)...................................................Fire Rod
[dungeon-L2-B1] Desert Palace - Big key room..............................................Quake
[cave-073] cave northeast of swamp palace [bottom chest]..................................Cane of Somaria
[cave-056] Dark World Death Mountain - cave under boulder [top right chest]...............Ice Rod
## Light World

[cave-009-1F] Death Mountain - wall of caves - right cave [bottom chest]..................10 Arrows
[cave-009-1F] Death Mountain - wall of caves - right cave [top left chest]................3 Bombs
[cave-009-1F] Death Mountain - wall of caves - right cave [top left middle chest].........3 Bombs
[cave-009-1F] Death Mountain - wall of caves - right cave [top right chest]...............Magic Mirror
[cave-009-1F] Death Mountain - wall of caves - right cave [top right middle chest]........Piece of Heart
[cave-009-B1] Death Mountain - wall of caves - right cave [left chest]....................Piece of Heart
[cave-009-B1] Death Mountain - wall of caves - right cave [right chest]...................Red Boomerang
[cave-012-1F] Death Mountain - wall of caves - left cave..................................Piece of Heart
[cave-013] Mimic cave (from Turtle Rock)..................................................20 Rupees
[cave-016] cave under rocks west of Santuary..............................................50 Rupees
[cave-018] Graveyard - top right grave....................................................50 Rupees
[cave-021] Kakariko well [bottom chest]...................................................100 Rupees
[cave-021] Kakariko well [center chest row of 3]..........................................1 Rupee
[cave-021] Kakariko well [left chest row of 3]............................................Bow
[cave-021] Kakariko well [right chest row of 3]...........................................20 Rupees
[cave-021] Kakariko well [top chest]......................................................20 Rupees
[cave-022-B1] Thief's hut [bottom left chest].............................................Piece of Heart
[cave-022-B1] Thief's hut [bottom right chest]............................................Piece of Heart
[cave-022-B1] Thief's hut [top chest].....................................................20 Rupees
[cave-022-B1] Thief's hut [top left chest]................................................Piece of Heart
[cave-022-B1] Thief's hut [top right chest]...............................................20 Rupees
[cave-026] chicken house..................................................................Moon Pearl
[cave-031] Tavern.........................................................................20 Rupees
[cave-034] Hyrule Castle secret entrance..................................................Bottle (Gold Bee)
[cave-035] Sahasrahla's Hut [center chest]................................................3 Bombs
[cave-035] Sahasrahla's Hut [left chest]..................................................Bombos
[cave-035] Sahasrahla's Hut [right chest].................................................Boomerang
[cave-040] Link's House...................................................................20 Rupees
[cave-044] Aginah's cave..................................................................20 Rupees
[cave-047] Dam............................................................................20 Rupees
[cave-050] cave southwest of Lake Hylia - generous guy....................................3 Bombs
[cave-050] cave southwest of Lake Hylia [bottom left chest]...............................Pegasus Boots
[cave-050] cave southwest of Lake Hylia [bottom right chest]..............................5 Rupees
[cave-050] cave southwest of Lake Hylia [top left chest]..................................100 Rupees
[cave-050] cave southwest of Lake Hylia [top right chest].................................Power Glove
[cave-051] Ice Cave.......................................................................Piece of Heart
Bombos....................................................................................10 Arrows
Bottle Vendor.............................................................................10 Arrows
Ether.....................................................................................20 Rupees
Haunted Grove item........................................................................50 Rupees
Hobo......................................................................................Heart Container
King Zora.................................................................................Hammer
Library...................................................................................20 Rupees
Mushroom..................................................................................3 Bombs
Old mountain man..........................................................................3 Bombs
Piece of Heart (Dam)......................................................................10 Arrows
Piece of Heart (Death Mountain - floating island).........................................3 Bombs
Piece of Heart (Desert - northeast corner)................................................Piece of Heart
Piece of Heart (Desert - west side).......................................................50 Rupees
Piece of Heart (Graveyard)................................................................Piece of Heart
Piece of Heart (Lake Hylia)...............................................................20 Rupees
Piece of Heart (Lumberjack Tree)..........................................................Piece of Heart
Piece of Heart (Maze Race)................................................................10 Arrows
Piece of Heart (south of Haunted Grove)...................................................Fire Rod
Piece of Heart (Spectacle Rock Cave)......................................................20 Rupees
Piece of Heart (Spectacle Rock)...........................................................50 Rupees
Piece of Heart (Thieves' Forest Hideout)..................................................3 Bombs
Piece of Heart (Zora's River).............................................................3 Bombs
Purple Chest..............................................................................Piece of Heart
Sahasrahla................................................................................Bottle (Gold Bee)
Sick Kid..................................................................................Shovel
Witch.....................................................................................10 Arrows
## Dark World

[cave-055] Spike cave.....................................................................20 Rupees
[cave-056] Dark World Death Mountain - cave under boulder [bottom left chest].............Piece of Heart
[cave-056] Dark World Death Mountain - cave under boulder [bottom right chest]............1 Arrow
[cave-056] Dark World Death Mountain - cave under boulder [top left chest]................Piece of Heart
[cave-056] Dark World Death Mountain - cave under boulder [top right chest]...............Ice Rod
[cave-057-1F] Dark World Death Mountain - cave from top to bottom [bottom chest]..........20 Rupees
[cave-057-1F] Dark World Death Mountain - cave from top to bottom [top chest].............1 Rupee
[cave-062] C-shaped house.................................................................3 Bombs
[cave-063] doorless hut...................................................................20 Rupees
[cave-071] Misery Mire west area [left chest].............................................Piece of Heart
[cave-071] Misery Mire west area [right chest]............................................100 Rupees
[cave-073] cave northeast of swamp palace - generous guy..................................20 Rupees
[cave-073] cave northeast of swamp palace [bottom chest]..................................Cane of Somaria
[cave-073] cave northeast of swamp palace [bottom middle chest]...........................100 Rupees
[cave-073] cave northeast of swamp palace [top chest].....................................3 Bombs
[cave-073] cave northeast of swamp palace [top middle chest]..............................Ocarina
Catfish...................................................................................Titan's Mitt
Flute Boy.................................................................................Ether
Piece of Heart (Dark World - bumper cave).................................................Book of Mudora
Piece of Heart (Dark World blacksmith pegs)...............................................Piece of Heart
Piece of Heart (Digging Game).............................................................Piece of Heart
Piece of Heart (Pyramid)..................................................................Lamp
Piece of Heart (Treasure Chest Game)......................................................20 Rupees
## Hyrule Castle Escape

[dungeon-C-1F] Sanctuary..................................................................Map
[dungeon-C-B1] Escape - final basement room [left chest]..................................10 Arrows
[dungeon-C-B1] Escape - final basement room [middle chest]................................Hookshot
[dungeon-C-B1] Escape - final basement room [right chest].................................Mushroom
[dungeon-C-B1] Escape - first B1 room.....................................................Magic Powder
[dungeon-C-B1] Hyrule Castle - boomerang room.............................................Piece of Heart
[dungeon-C-B1] Hyrule Castle - map room...................................................Key
[dungeon-C-B3] Hyrule Castle - next to Zelda..............................................300 Rupees
## Eastern Palace

[dungeon-L1-1F] Eastern Palace - big ball room............................................Big Key
[dungeon-L1-1F] Eastern Palace - big chest................................................Compass
[dungeon-L1-1F] Eastern Palace - Big key..................................................Map
[dungeon-L1-1F] Eastern Palace - compass room.............................................100 Rupees
[dungeon-L1-1F] Eastern Palace - map room.................................................Bottle (Gold Bee)
## Desert Palace

[dungeon-L2-B1] Desert Palace - big chest.................................................Map
[dungeon-L2-B1] Desert Palace - Big key room..............................................Quake
[dungeon-L2-B1] Desert Palace - compass room..............................................Big Key
[dungeon-L2-B1] Desert Palace - Map room..................................................Compass
## Tower of Hera

[dungeon-L3-1F] Tower of Hera - first floor...............................................Big Key
[dungeon-L3-2F] Tower of Hera - Entrance..................................................Map
[dungeon-L3-4F] Tower of Hera - 4F [small chest]..........................................Piece of Heart
[dungeon-L3-4F] Tower of Hera - big chest.................................................Compass
## Hyrule Castle Tower

[dungeon-A1-2F] Hyrule Castle Tower - 2 knife guys room...................................Key
[dungeon-A1-3F] Hyrule Castle Tower - maze room...........................................Key
## Dark Palace

[dungeon-D1-1F] Dark Palace - big chest...................................................Bug-Catching Net
[dungeon-D1-1F] Dark Palace - big key room................................................Bottle (Fairy)
[dungeon-D1-1F] Dark Palace - compass room................................................Key
[dungeon-D1-1F] Dark Palace - jump room [left chest]......................................Key
[dungeon-D1-1F] Dark Palace - jump room [right chest].....................................Key
[dungeon-D1-1F] Dark Palace - maze room [bottom chest]....................................Key
[dungeon-D1-1F] Dark Palace - maze room [top chest].......................................Compass
[dungeon-D1-1F] Dark Palace - spike statue room...........................................Big Key
[dungeon-D1-1F] Dark Palace - statue push room............................................Map
[dungeon-D1-B1] Dark Palace - room leading to Helmasaur [left chest]......................Cape
[dungeon-D1-B1] Dark Palace - room leading to Helmasaur [right chest].....................10 Arrows
[dungeon-D1-B1] Dark Palace - shooter room................................................Key
[dungeon-D1-B1] Dark Palace - turtle stalfos room.........................................Key
## Swamp Palace

[dungeon-D2-1F] Swamp Palace - first room.................................................Key
[dungeon-D2-B1] Swamp Palace - big chest..................................................20 Rupees
[dungeon-D2-B1] Swamp Palace - big key room...............................................Compass
[dungeon-D2-B1] Swamp Palace - map room...................................................Big Key
[dungeon-D2-B1] Swamp Palace - push 4 blocks room.........................................3 Bombs
[dungeon-D2-B1] Swamp Palace - south of hookshot room.....................................Map
[dungeon-D2-B2] Swamp Palace - flooded room [left chest]..................................300 Rupees
[dungeon-D2-B2] Swamp Palace - flooded room [right chest].................................20 Rupees
[dungeon-D2-B2] Swamp Palace - hidden waterfall door room.................................3 Bombs
## Skull Woods

[dungeon-D3-B1] Skull Woods - big chest...................................................Compass
[dungeon-D3-B1] Skull Woods - Big Key room................................................Map
[dungeon-D3-B1] Skull Woods - Compass room................................................Key
[dungeon-D3-B1] Skull Woods - east of Fire Rod room.......................................Piece of Heart
[dungeon-D3-B1] Skull Woods - Entrance to part 2..........................................Key
[dungeon-D3-B1] Skull Woods - Gibdo/Stalfos room..........................................Big Key
[dungeon-D3-B1] Skull Woods - south of Fire Rod room......................................Key
## Thieves Town

[dungeon-D4-1F] Thieves' Town - Room above boss...........................................50 Rupees
[dungeon-D4-B1] Thieves' Town - Bottom left of huge room [bottom right chest].............Big Key
[dungeon-D4-B1] Thieves' Town - Bottom left of huge room [top left chest].................Flippers
[dungeon-D4-B1] Thieves' Town - Bottom right of huge room.................................Compass
[dungeon-D4-B1] Thieves' Town - Top left of huge room.....................................Map
[dungeon-D4-B2] Thieves' Town - big chest.................................................10 Arrows
[dungeon-D4-B2] Thieves' Town - next to Blind.............................................Key
## Ice Palace

[dungeon-D5-B1] Ice Palace - Big Key room.................................................Key
[dungeon-D5-B1] Ice Palace - compass room.................................................10 Arrows
[dungeon-D5-B2] Ice Palace - map room.....................................................Staff of Byrna
[dungeon-D5-B3] Ice Palace - spike room...................................................Big Key
[dungeon-D5-B4] Ice Palace - above Blue Mail room.........................................Key
[dungeon-D5-B5] Ice Palace - b5 up staircase..............................................Map
[dungeon-D5-B5] Ice Palace - big chest....................................................Compass
## Misery Mire

[dungeon-D6-B1] Misery Mire - big chest...................................................3 Bombs
[dungeon-D6-B1] Misery Mire - big hub room................................................Map
[dungeon-D6-B1] Misery Mire - big key.....................................................Key
[dungeon-D6-B1] Misery Mire - compass.....................................................Big Key
[dungeon-D6-B1] Misery Mire - end of bridge...............................................Compass
[dungeon-D6-B1] Misery Mire - map room....................................................Key
[dungeon-D6-B1] Misery Mire - spike room..................................................Key
## Turtle Rock

[dungeon-D7-1F] Turtle Rock - Chain chomp room............................................Key
[dungeon-D7-1F] Turtle Rock - compass room................................................Big Key
[dungeon-D7-1F] Turtle Rock - Map room [left chest].......................................Key
[dungeon-D7-1F] Turtle Rock - Map room [right chest]......................................Key
[dungeon-D7-B1] Turtle Rock - big chest...................................................Mirror Shield
[dungeon-D7-B1] Turtle Rock - big key room................................................100 Rupees
[dungeon-D7-B1] Turtle Rock - Roller switch room..........................................Map
[dungeon-D7-B2] Turtle Rock - Eye bridge room [bottom left chest].........................5 Rupees
[dungeon-D7-B2] Turtle Rock - Eye bridge room [bottom right chest]........................Compass
[dungeon-D7-B2] Turtle Rock - Eye bridge room [top left chest]............................20 Rupees
[dungeon-D7-B2] Turtle Rock - Eye bridge room [top right chest]...........................Key
## Ganon's Tower

[dungeon-A2-1F] Ganon's Tower - above Armos...............................................Piece of Heart
[dungeon-A2-1F] Ganon's Tower - big chest.................................................3 Bombs
[dungeon-A2-1F] Ganon's Tower - compass room [bottom left chest]..........................3 Bombs
[dungeon-A2-1F] Ganon's Tower - compass room [bottom right chest].........................300 Rupees
[dungeon-A2-1F] Ganon's Tower - compass room [top left chest].............................Piece of Heart
[dungeon-A2-1F] Ganon's Tower - compass room [top right chest]............................20 Rupees
[dungeon-A2-1F] Ganon's Tower - down right staircase from entrance [left chest]...........Piece of Heart
[dungeon-A2-1F] Ganon's Tower - down right staircase from entrance [right chest]..........20 Rupees
[dungeon-A2-1F] Ganon's Tower - east of down right staircase from entrace.................Blue Mail
[dungeon-A2-1F] Ganon's Tower - map room..................................................Piece of Heart
[dungeon-A2-1F] Ganon's Tower - north of gap room [bottom left chest].....................20 Rupees
[dungeon-A2-1F] Ganon's Tower - north of gap room [bottom right chest]....................Map
[dungeon-A2-1F] Ganon's Tower - north of gap room [top left chest]........................Key
[dungeon-A2-1F] Ganon's Tower - north of gap room [top right chest].......................3 Bombs
[dungeon-A2-1F] Ganon's Tower - north of teleport room....................................Key
[dungeon-A2-1F] Ganon's Tower - west of teleport room [bottom left chest].................300 Rupees
[dungeon-A2-1F] Ganon's Tower - west of teleport room [bottom right chest]................20 Rupees
[dungeon-A2-1F] Ganon's Tower - west of teleport room [top left chest]....................Piece of Heart
[dungeon-A2-1F] Ganon's Tower - west of teleport room [top right chest]...................50 Rupees
[dungeon-A2-6F] Ganon's Tower - before Moldorm............................................Red Mail
[dungeon-A2-6F] Ganon's Tower - Moldorm room..............................................10 Arrows
[dungeon-A2-6F] Ganon's Tower - north of falling floor four torches [top left chest]......Red Shield
[dungeon-A2-6F] Ganon's Tower - north of falling floor four torches [top right chest].....Compass
[dungeon-A2-B1] Ganon's Tower - north of Armos room [bottom chest]........................Key
[dungeon-A2-B1] Ganon's Tower - north of Armos room [left chest]..........................20 Rupees
[dungeon-A2-B1] Ganon's Tower - north of Armos room [right chest].........................Big Key
## Special Locations

Magic Bat.................................................................................1/2 Magic
Misery Mire Required Medallion............................................................Ether
Pyramid Bottle Item.......................................................................Bottle (Blue Potion)
Turtle Rock Required Medallion............................................................Quake
Waterfall Bottle Item.....................................................................Bottle (Gold Bee)

**Comment by BlueViper85** [comment]
I don't see anything keeping you from getting the hammer from King Zora. This will give you access to nearly all of the dark world warps allowing you to complete the dark world. Use the warp near Palace of Darkness (south of Eastern Palace) to access the area that provides a path to the catfish.  If memory serves me correctly you can lift all the rocks along the way with just the power gloves.

Please check and confirm.

**Comment by BlueViper85** [comment]
Played through a portion of the seed.  Confirmed all items are obtainable.

You'll need to get the hammer from King Zora which will provide access to most of the dark world portals.  This will give you access to the cape and you can use the Power Gloves to get to the Catfish to get the Titan's Mitts
