### ISSUE TITLE
Question about keys

### ISSUE THREAD

**Issue by dorsey43** [Dessyreqt/alttprandomizer#158]
I am playing seed C7777777 and was wondering if certain dungeons require keys from other dungeons to beat, specifically the swamp palace where it seems there are not enough keys to progress. I'm not even sure if you can keep keys in that sense in this game, I think I heard someone mention it on Youtube once though. Thanks!

**Comment by BlueViper85** [comment]
Keys are not transferable from one dungeon to the next. Swamp Palace  has five keys under pots, one of which requires the hookshot to access. One of them can be flooded over as well if you aren't careful. In that case, leave the dungeon and walk a screen away from the dungeon to reset the water and return to the dungeon (you will need to pull the switch in the light world again). No keys have been removed from Swamp, and the key locations shouldn't allow for a key lock anywhere.

If you can't find your missing key, please provide any additional details you can. A save state or SRM file would be most helpful if you know where your emulator saves them.
