### ISSUE TITLE
[v6] Sword downgrades

### ISSUE THREAD

**Issue by Firehed** [Dessyreqt/alttprandomizer#159]
Preface: I'm using a slightly modified version of the randomizer to allow some item placement changes

When sword upgrades spawn in a chest (rather than are obtained through the normal means within the game), it's possible for them to downgrade the sword currently in your possession.

To really quickly reproduce the issue, generate any random ROM them make the following changes in a hex editor:

0xE971 -> 0x03 ; Golden sword in secret entrance chest
0xEB0C -> 0x02 ; Tempered sword in escape map room

Some other tickets indicated this had been fixed already, but either it didn't happen (or didn't work) or - more likely - only fixes downgrades caused by the normal progression scenario (forest/blacksmith/pyramid).

Also, for what it's worth, if you get L3/L4 sword before rescuing Zelda from the basement, she doesn't spawn at all. But that's probably not worth fixing since it's easy to stop those upgrades from spawning in the four chests that cause this problem. I assume this would also happen with L2 sword but as the code indicates, that crashes the game :)

**Comment by BlueViper85** [comment]
Sword randomization will be added to randomizer in a future update, though current plan is only to have them randomized among each other (excluding the fighter sword). Sword downgrades will be handled appropriately with that release.

Today downgrades are allowed but the upgrades can be completed again in their usual locations, effectively making it a non-issue.

Thank you for your feedback.

[EDIT] To correct my own mistake, I've been informed that there is already downgrade protection when the sword is pulled from the proper location.  However, this does not apply to chests. Current plans only have the swords being randomized amongst themselves as opposed to being part of the chest randomization.  

This may be re-opened if it's something that is chosen to be fixed for these manual modifications. [/EDIT]
