### ISSUE TITLE
[dungeon-D6-B1] Misery Mire - big hub room...Cane of Somaria

### ISSUE THREAD

**Issue by Dessyreqt** [Dessyreqt/alttprandomizer#160]
Submitter: Magnus
Email: mangek@gmail.com
Hello. The spoiler tells me that the Cane of Somaria is in the "big hub room", but which room is this? I've been all over, but I can't find it, and I need it to progress through the later part of the dungeon.

The seed is: C7467233

**Comment by Myramong** [comment]
This is the chest you're looking for: https://puu.sh/rhfl6/4435fc401a.png
It appears when you step on the switch between the blue pegs.

**Comment by BlueViper85** [comment]
The room specified by Myramong is the Big Hub room and that's the only chest in that room. Thanks again, Myramong!
