### ISSUE TITLE
Can you get in the ice dungeon without the Zora's flipper. 

### ISSUE THREAD

**Issue by RogerRabbitt** [Dessyreqt/alttprandomizer#161]
I've been playing for a few hours now and I've been pretty good up until this one point. I can't seem to get the flipper to spawn. I have completed the light world and four of the seven in the dark world. I can't complete the water temple, get into the ice temple, or beat the boss at turtle rock. The ice wand is where the heart piece use to be on the way to get the flipper in the light world. So turtle rock boss can't be completed ( everything up to that point in the dungeon is) can't start the water temple for same reason. But I was doing some dash jumping to get close to the ice temple but that's pretty much as far as I think I can go. Don't wanna say the seed can't be beat, I may have missed a chest somewhere along the lines. But I'm really not sure. But does anyone happen to know a way around the walls for the ice temple entrance until the flipper pops up  Thanks for anyone's time for taking a look at this.

**Comment by RogerRabbitt** [comment]
The seed is "C3248138"

**Comment by Myramong** [comment]
The Flippers are required to get into Ice Palace, I've checked the seed and confirmed the Flippers are obtainable.  Here's your spoiler log if you want to check: http://pastebin.com/iSGzZKfJ

**Comment by BlueViper85** [comment]
Confirmed flippers are accessible via the provided spoiler log. Closing this issue. Thanks, Myramong!
