### ISSUE TITLE
Spoiler Log After Creation

### ISSUE THREAD

**Issue by Chidsuey** [Dessyreqt/alttprandomizer#162]
I'm starting to think I may not be able to complete this seed, but as "spoiler log" is by default unchecked,I don't have one for this go around. Is there some other way to check where things are or the seed number? Thanks.

**Comment by KatDevsGames** [comment]
You can just type the seed number back into randomizer and generate the same seed again and check the spoiler log this time.

If you're stuck and would just like some general hints though... we can do that too.

**Comment by BlueViper85** [comment]
If you have changed (or ever do change) the name of the game file you can see the Seed number when loading it in an emulator.  See #138 for a few screen shots to help with this.

You can then generate the log or give us the seed and we can provide hints if you'd prefer.

**Comment by Chidsuey** [comment]
Thanks for the help! Though I wracked my brain for the solution, there was a part of me that was still sure it the items had to be somewhere obtainable. Cave-009-1F, a place I didn't think I could reach.

I've beaten this game dozens of times but there are so many places I've never been because there was nothing of real value. This has been so much fun.
