### ISSUE TITLE
Pressing Y to switch between items not clear enough

### ISSUE THREAD

**Issue by SmashManiac** [Dessyreqt/alttprandomizer#165]
I've been listening to many YouTubers lately playing this randomizer for the first time. I've watched 4 or so playthroughs so far.

All of them, without exception, thought that they lost their shovel, ocarina, mushroom or magic powder after acquiring another item occupying the same slot, even when that slot was selected in the sub-screen and the "Y" icon flashed in front of them. Most of them tried to backtrack to where they originally found the lost item as an attempt to get it back. I even saw one particular player restart a new game in the middle of a race as a workaround.

I personally did not encounter this situation because I read the documentation beforehand, but based on empirical evidence, it appears most players don't do so. or forget that particular detail.

To counter that, I believe there should be a more obvious clue on the sub-screen as to where those items went.

**Comment by BlueViper85** [comment]
Relevant to issue #110 where it has been discussed of options of getting the player to read the documentation such as making it open to it.

The game has a Y on the screen already it can't get much more obvious without a significant overhaul. The best option may be to make the documentation a little more clear or easily found however people can still skip it.
