### ISSUE TITLE
Seed C7863534 - Dark Palace issue

### ISSUE THREAD

**Issue by Zergei64** [Dessyreqt/alttprandomizer#166]
I accidently locked myself out from the big key, big chest and reaching the boss. In this seed, you can get the hammer on the [dungeon-D1-1F] Dark Palace - spike statue room . If one doesn't go to the dark maze room before using all available keys until that point, then one cannot access the maze room, where the last key and big key are located.

**Comment by BlueViper85** [comment]
This is a known issue with Palace of Darkness and is being tracked in issue #123. Closing this as it would be a duplicate.
