### ISSUE TITLE
[v6] Testing e-mail notifications

### ISSUE THREAD

**Issue by Dessyreqt** [Dessyreqt/alttprandomizer#169]
Submitter: BlueViper85
Email: blueviper85@outlook.com
[v6]

Testing the submit an issue. Since they show up as being generated by Dessy with the actual submitters name and e-mail in the body, I'm not sure whether the original submitter gets any e-mail notifications from GitHub or not.  So I'm using this as a means to find out.

If I do get the e-mails, great. If not, I would have to ask if this is something that can be fixed.  I'll comment with my results and close if e-mails are received.

**Comment by BlueViper85** [comment]
Nothing when submitting, so here's a comment response.

**Comment by bv-testdev** [comment]
Testing a response from a separate account, to ensure it would actually send something,

**Comment by BlueViper85** [comment]
I only got notifications on this resulting from my usual subscriptions, not because I was the submitter.  Is there any way that the Report an Issue page can be set so they would receive e-mails from these issue pages (without forcing them to sign up for GitHub)?

If not, i'm perfectly fine with e-mailing directly, I don't want this to cause a lot more work.  Just had to ask.

**Comment by Dessyreqt** [comment]
We could look into another way to handle anonymous submissions (I'd rather get bug reports with no contact info than not get them) but without forcing users to sign up for GitHub, there's no way to make them get follow-up emails. If there are better ideas to solve this problem, I'm all ears.

**Comment by BlueViper85** [comment]
The anonymous report issue trumps automated notifications to me as well.

The only real method I can think of (assuming that GitHub even could support it) is to put the submitter's e-mail as your own (not updating your account or anything permanent) and if they don't submit anything, keep it as it is today.  But I can only assume that their system wouldn't support changing the e-mail address on the fly like that.

Barring that I don't know that there's much else that can be done short of building a whole manual system which is not at all worth the effort.

**Comment by BlueViper85** [comment]
I don't know that I see any reason to keep this open. Thanks for the discussion!
