### ISSUE TITLE
(V6.0) Item Misplacement (SEED C6343931) [SOLVED]

### ISSUE THREAD

**Issue by Joss-Card** [Dessyreqt/alttprandomizer#171]
Well, this was going smoothly until I neared the end of the Dark World. Finished all dungeons except for Misery Mire, but couldn't find the Quake Medallion to open the dungeon. Sure enough...

[SPOILER LOG]
[dungeon-D2-B1] Swamp Palace - big key room...............................................Quake

Misery Mire Required Medallion............................................................Quake

Can't open the door the dungeon, and save for severely glitching out the game (via some Walk Through Walls glitches or Underworld Roaming glitches) I can't finish the game. 

I don't know if there's a running list of broken seeds or where to find it, but Google sent me here when I looked up "alttp randomizer broken seeds" so I'll just leave this here for the next update.

**Comment by BlueViper85** [comment]
The Quake medallion is in Swamp Palace (bottom middle of the Dark World map / Crystal #2). Misery Mire (the dungeon that requires the quake medallion to open it) is Crystal #6 on the bottom Left side of the map.

The hookshot, mirror, hammer, gloves (and mitts) and moon pearl are all accessible so you can beat the Swamp a palace which also means you can access the Quake medallion.

Judging by this I see no reason you can't access Misery Mire.  You should be able to continue after double-checking Swamp Palace / DW dungeon #2

Thanks!

BlueViper85

Sent from my iPhone

On Sep 25, 2016, at 2:48 PM, Joss-Card <notifications@github.com<mailto:notifications@github.com>> wrote:

Well, this was going smoothly until I neared the end of the Dark World. Finished all dungeons except for Misery Mire, but couldn't find the Quake Medallion to open the dungeon. Sure enough...

[SPOILER LOG]
[dungeon-D2-B1] Swamp Palace - big key room...............................................Quake

Misery Mire Required Medallion............................................................Quake

Can't open the door the dungeon, and save for severely glitching out the game (via some Walk Through Walls glitches or Underworld Roaming glitches) I can't finish the game.

I don't know if there's a running list of broken seeds or where to find it, but Google sent me here when I looked up "alttp randomizer broken seeds" so I'll just leave this here for the next update.

##

**Comment by Joss-Card** [comment]
My face is red... Yeah, I totally confused Misery Mire and Swamp Palace.

**Comment by BlueViper85** [comment]
No problem.  Hope you continue to enjoy randomizer, and thanks for the feedback! If you ever find anything else that seems problematic, please let us know.
