### ISSUE TITLE
[v6] Bow in dark palace

### ISSUE THREAD

**Issue by Dessyreqt** [Dessyreqt/alttprandomizer#174]
Submitter: Matheus Giovanelli
Email: jorumbarashid@gmail.com
[v6] In the seed C6298301 the bow spawned inside the dark palace and the only accessible chest with no bow is in the "shooter room" and that chest did not give me any key, making it impossible to get the bow inside the dark palace and beating the game.

Thanks for the support. Cya.

**Comment by BlueViper85** [comment]
Thanks for the report!  This issue has been reported previously and will be addressed under issue #123 if you care to track it at all.
