### ISSUE TITLE
Agahnim Before Zelda has Unexpected Results

### ISSUE THREAD

**Issue by BlueViper85** [Dessyreqt/alttprandomizer#175]
Copying + Pasting from ChristosOwen in Discord:

ChristosOwen i got cape in the pre-castle chest, and instead of doing escape i went and beat agahnim, then i did escape and this happened
Woodcutters still there at the tree, but tree is bonkable in the post-Aga state
Karkat superskuj this might be something we need to alter for rando

![image](https://cloud.githubusercontent.com/assets/12190332/18999300/7e349e2e-8702-11e6-9c4a-8cb696e11cbf.png)

In general, doing Agahnim and then rescuing Zelda, anything that's affected by that we should consider (and anything that's affected by NOT rescuing Zelda after aga)

**Comment by BlueViper85** [comment]
Going under the bridge before the castle does not warp to Dark World as it should after Agahnim 1 is defeated

**Comment by KatDevsGames** [comment]
Please check if Usain Bolt is present if you have time.

**Comment by KatDevsGames** [comment]
Seriously, someone please check if Usain Bolt (fast red guard near the library) is present or missing after entering the glitched state.

**Comment by Myramong** [comment]
Usain Bolt is not present.
[rom / save state / srm](http://puu.sh/rJvV2/0fc0bb7438.rar)

**Comment by ChristosOwen** [comment]
This had been addressed and will be working correctly in v7.
