### ISSUE TITLE
[V6] key lock

### ISSUE THREAD

**Issue by huwpascoe** [Dessyreqt/alttprandomizer#176]
A friend playing this reported that they were stuck in dark palace because they opened the rooms in the wrong order. Please can you confirm this is possible?

Version: 6
Creation Date: 01/10/2016 18:17:53
Seed: C8765906

[dungeon-D1-1F] Dark Palace - big chest...................................................20 Rupees
[dungeon-D1-1F] Dark Palace - big key room................................................Bombos
[dungeon-D1-1F] Dark Palace - compass room................................................100 Rupees
[dungeon-D1-1F] Dark Palace - jump room [left chest]......................................Key
[dungeon-D1-1F] Dark Palace - jump room [right chest].....................................Key
[dungeon-D1-1F] Dark Palace - maze room [bottom chest]....................................Big Key
[dungeon-D1-1F] Dark Palace - maze room [top chest].......................................Key
[dungeon-D1-1F] Dark Palace - spike statue room...........................................Compass
[dungeon-D1-1F] Dark Palace - statue push room............................................Key
[dungeon-D1-B1] Dark Palace - room leading to Helmasaur [left chest]......................Key
[dungeon-D1-B1] Dark Palace - room leading to Helmasaur [right chest].....................Map
[dungeon-D1-B1] Dark Palace - shooter room................................................50 Rupees
[dungeon-D1-B1] Dark Palace - turtle stalfos room.........................................Key

**Comment by BlueViper85** [comment]
This is possible, assuming they opened the door in the basement leading to Helmasaur.  Since there is no key possible after that door there is a possibility you will Key Lock.  This should be fixed in the next update (v7).

I'm closing thi sissue because it is being tracked as part of issue #123

**Comment by huwpascoe** [comment]
Thank you for the response! I'll pass it on
