### ISSUE TITLE
Dark 5 "Water Dungeon" Unbeatable if keys used in wrong order.

### ISSUE THREAD

**Issue by 1-800-thewolf** [Dessyreqt/alttprandomizer#179]
![alttp 5 soft lock](https://cloud.githubusercontent.com/assets/17304275/19177304/bcc40130-8bfc-11e6-99a8-893899f6fa4b.png)

If you use the hookshot to get the key in the big chest room and use it to go left and fill the hallway with water it will soft lock. The key under the skull will be covered and be unobtainable. 

I'm playing on seed C5345229

**Comment by BlueViper85** [comment]
This situation was specifically addressed in a previous version of the randomizer.  Normally in the game this room would stay flooded and, as you said, you'd be locked out of continuing.  In Randomizer these flooded areas are reset when the water outside gets reset

So when this happens, if you leave the dungeon, walk one screen away, then come back and drain the small pond around the dungeon entrance again you can then get to this pot and grab the key.

Please note that this is also addressed on the download page for the Randomizer.  Specifically this bullet under the "Some bugs that wouldn't crop up in normal play have been fixed:" section.

> If you collect the key in the big chest room in the Swamp Palace (due to having hookshot earlier than normal), then use that key on the top left door of that room, you can cause a soft lock due to being unable to access that key. In randomizer, moving one screen on the overworld away from the entrance to Swamp Palace will reset the water both around Swamp Palace, and the water that would cover those keys.

If you haven't already, it is highly suggested that you read through this section of the page (and the rest of the page if at all possible) to learn about these situations and other things that have been changed or fixed from the normal game.  It's especially important to check this page when new versions are released to track what has been changed from one version to the next.

Thanks for play, hope you continue to enjoy the Randomizer!  If you find that this doesn't reset this room this issue can be reopened.  If you find any other issues or have any questions/suggestions, please let us know!

**Comment by couchinator** [comment]
Hey, I have a similar issue where I used the key I was supposed to use on the top left door, on the top one instead and now I can't get into the top left one. Cant find any more keys anywhere. Am I missing something?

**Comment by couchinator** [comment]
Nevermind. I'm just a dummy
