### ISSUE TITLE
Disable Low Health Alarm

### ISSUE THREAD

**Issue by RenaKunisaki** [Dessyreqt/alttprandomizer#180]
Please for the love of all that is good disable that infernal beeping.

**Comment by KatDevsGames** [comment]
I'll do it for v8 if dessyreqt is OK with having a check box for it.

On October 8, 2016 5:02:19 PM EDT, Rena Kunisaki notifications@github.com wrote:

> Please for the love of all that is good disable that infernal beeping.
> 
> ## 
> 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/Dessyreqt/alttprandomizer/issues/180

## 

Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by SmashManiac** [comment]
If implemented, I agree that it should be optional. It may be annoying, but I find it really useful. (I had a few dumb Game Overs in Skyward Sword because they made the alarm too soft.)

**Comment by Dessyreqt** [comment]
I like this, let's do it (with a checkbox of course)

**Comment by RenaKunisaki** [comment]
Another option would be to make it less frequent, like one beep every few seconds, for people who actually want the audio cue.

**Comment by Dessyreqt** [comment]
Setting is in the master branch now.
