### ISSUE TITLE
Mass Seed Creation

### ISSUE THREAD

**Issue by thatguycore** [Dessyreqt/alttprandomizer#183]
Is it possible to get a feature that allows you to crease new seeds in bulk. So if I choose 5 or 10 in a drop down menu, that menu seeds get made.

**Comment by thejoshwolfe** [comment]
Can you describe the situation where you want to create multiple seeds at once? Perhaps you're going to load them into your sd2snes before going on a long trip? Perhaps you're giving out a different seed to each participant in a (unfair) race?

**Comment by thatguycore** [comment]
The first one you described is pretty much the reason why I asked for the feature. A lot of the time I play my randomizers on a console in the other room instead of my pc. Usually I will create 20 seeds or so at once and would like to skip the step of having to clear out the seed field of the randomizer tool after every generation. That way I can toss them all on an SD card and not have to go back and forth every time I want to generate a new seed.

**Comment by Dessyreqt** [comment]
This will be coming with v7. As a workaround for the moment, you can click Random Spoiler, then Create, and do that until you have enough seeds.

**Comment by Dessyreqt** [comment]
This is in the master branch.
