### ISSUE TITLE
Softlock in Seed C1404868

### ISSUE THREAD

**Issue by tim-burget** [Dessyreqt/alttprandomizer#184]
If you open all locked doors in the Palace of Darkness except for the one leading to the big chest in seed C1404868, you are locked out of getting Zora's Flippers, and can't finish the game without glitches.
ZSNES savestate and SRAM (using first save file):
[C1404868.zip](https://github.com/Dessyreqt/alttprandomizer/files/530165/C1404868.zip)

**Comment by BlueViper85** [comment]
This is a known issue with the logic for Palace of Darkness, and is being tracked issue #123 if you care to follow any updates on the issue you can refer to that issue.

Thanks for letting us know! Hope you continue to enjoy randomizer despite this hiccup, and please let us know if you notice any more problems in the future!

**Comment by tim-burget** [comment]
Yeah, that issue does look similar. Thanks and you're welcome!
