### ISSUE TITLE
Bugs/Concerns after initial V7 Playtest

### ISSUE THREAD

**Issue by BlueViper85** [Dessyreqt/alttprandomizer#185]
A few notes that came up during the V7 PlayTest:
- Turn the new inventory switch (using Y) back on
- Fix Mothula Gold Sword fight
- Fix 1/4 magic preventing bat from giving item (if any additional work is needed, since this was fixed on the fly)
- Should rescuing smith should be a requirement for the Big Bomb?  Since that has other item-based implications (and maybe other issues?)
- Change Triforce text at the end to GG/G.G.

**Comment by ChristosOwen** [comment]
Thanks for capturing. Also fix the Sahasrahla Moon Pearl sprite corruption.

Triforce text as GG would be pretty funny. We could do a pool of text suggestions for the Triforce also, in the same way we do for Uncle? 

For randomizer I think it would be better to **not** have to rescue the smith for the Big Bomb to spawn. This opens up early silver arrows and sword upgrade. Notably visiting the faerie for a sword upgrade could be required if you don't have the necessary items to get all 3 pendants or rescue the smithy, but do need to get Ether/Bombos tablet or defeat Agahnim without the cape. I've written the logic for this already forgetting the Big Bomb is meant to be constrained by rescuing smithy. 

If we don't make this change it means this logic/routing is void, but happy to go with the majority.

**Comment by ChristosOwen** [comment]
These have now all been fixed and verified by test seed B, with the exception of the Triforce text and Moon Pearl sprite corruption, which are both on the Google doc already, so going to close.
