### ISSUE TITLE
[v6] Anonymous Issue - softlock?  

### ISSUE THREAD

**Issue by Dessyreqt** [Dessyreqt/alttprandomizer#186]
Submitter: Garret
[v6] Appears that it is possible to get softlocked as I have most items to continue, but I cannot progress without getting boots to knock the key off of the torch/lamp ion the LW desert palace.  The small key is keeping me from getting the big key in this palace.  I did not create a log, but I think I have hit every chest possible and done as many dungeons as possible-  still havent gotten the moon pearl either, so cannot do any dark world at all.

**Comment by BlueViper85** [comment]
Depending on items available you might be able to get a key from the second half of Desert Palace to use in the first half. Knowing your seed number would go a long way here.  If you load the ROM in SNES9x it will tell you the seed number in the yellow text that loads first.

There's no email address provided and it was submitted via the form so I don't know if this will be seen or not. I'll close this in a week if no response is provided.

**Comment by ChristosOwen** [comment]
No further response was received. Without further information we cannot verify the issue. User can resubmit the issue if it hasn't been resolved.
