### ISSUE TITLE
Pendant Vanish (v6)

### ISSUE THREAD

**Issue by TheBraveHylian** [Dessyreqt/alttprandomizer#189]
Sometimes after collecting a pendant, one or more of the pendants that I have previously collected disappear from my inventory. I have had this happen three times with three different seeds. I don't know all three seed numbers but I do know that one of them is C6720229. On each seed, I fight the boss, collect the Heart Container, collect the pendant, and it exits me from the palace normally. On the seed I mentioned, I collected Sahasralah's item, only to have the pendant required to get that item disappear when I collected the third pendant. Sometimes the pendant will disappear immediately after picking it up.

**Comment by Jaylow7** [comment]
Thanks for the feedback!  I believe this is a known issue that will be fixed in v7.

**Comment by BlueViper85** [comment]
There is a known bug with visiting Great Fairies in v6 where pendants are removed from your inventory when they heal you.  Revisiting the boss room for any completed light world dungeons will drop the pendant again without fighting again.  This will be fixed in the next version of Randomizer.

**Comment by TheBraveHylian** [comment]
Cool, thanks for the quick response.
