### ISSUE TITLE
Unrandomized Seed Functionality

### ISSUE THREAD

**Issue by biohazardtx** [Dessyreqt/alttprandomizer#190]
Feature req: Can you reserve a seed that is totally unrandomized? So you can play the original playthrough with all of the speed running features that have been added?

**Comment by Protoblob** [comment]
It seems to me you can just use the file here (go to the page and click on Download)?
https://github.com/Dessyreqt/alttprandomizer/blob/master/AlttpRandomizer/Resources/alttp.sfc

At least according to its description, checksum and a short playtest this should be what you look for.

**Comment by Dessyreqt** [comment]
Protoblob is correct. Please just use that rom to play if you want to play an unrandomized experience with all the new features.
