### ISSUE TITLE
source code indentation

### ISSUE THREAD

**Issue by thejoshwolfe** [Dessyreqt/alttprandomizer#191]
I was just browsing some source code here in the github interface, and i got to this mess:

https://github.com/Dessyreqt/alttprandomizer/blob/db7fb85eec36f001c9fd560f970320c17aa285e2/AlttpRandomizer/Random/Randomizer.cs#L51-L81

The problem with the indentation is mixing tabs and spaces. I'd be happy to go through all the code and fix the indentation, canonicalizing everything to either tabs or spaces, your choice. Would you be interested in this kind of contribution?

I'd be happy to wait until after v7, since I know that's coming up soon.

**Comment by thejoshwolfe** [comment]
It looks like Visual Studio has a built in formatter. `Ctrl+K` `Ctrl+D` in a file to format all the whitespace. For what it's worth, a fresh installation of Visual Studio chose spaces over tabs by default.

**Comment by KatDevsGames** [comment]
I will be going through the entire project with a full ReSharper analysis in a few weeks which will include normalizing all whitespace.

**Comment by thejoshwolfe** [comment]
great! thanks.
