### ISSUE TITLE
[v6] Impossible Seed

### ISSUE THREAD

**Issue by Dessyreqt** [Dessyreqt/alttprandomizer#192]
Submitter: HyruleHero
Email: theonlyhyrulehero@gmail.com
[v6] Bow in POD  seed:1674391

**Comment by BlueViper85** [comment]
Piece of heart in the shooter room chest, confirms that this Seed is unsolvable and relates to issue #123 I am closing this issue as it will be linked there and all tracking can be found in that issue.
