### ISSUE TITLE
Item Switch On L+R

### ISSUE THREAD

**Issue by Dessyreqt** [Dessyreqt/alttprandomizer#193]
Submitter: Cameron
[v6]

Can you add a way to change your Y weapon from the game without accessing the menu? Like using the L and R buttons in the Mega Man X series?

**Comment by ChristosOwen** [comment]
This may be included in a future version as an option you can select/deselect when generating a seed :)

**Comment by ChristosOwen** [comment]
This is now a feature of the latest version: http://vt.alttp.run/
