### ISSUE TITLE
[v6] Impossible seed C3194162

### ISSUE THREAD

**Issue by the-bacon-sword** [Dessyreqt/alttprandomizer#194]
This is a very interesting one.  C3194162.

The lock itself appears to be the Hookshot requires heavy lift to lift the stone in front of the chest in the spike cave.  The Power Glove requires the shovel, but you can't get to Zora without the PG or TM.  Titan's Mitt requires the big key in Swamp, which requires the hookshot.  Even though flippers are already in possession, can't swim up the waterfall to get up to Zora and bypass the stone.

I could be missing a way to get this unlocked, but I think I covered my bases.

I had to play this through twice to verify a second "issue".  The Bow is in the final basement room of Escape, which is indeed accessible with bombs that early on.  However, if one were to miss it, as a speedrunner typically would without access to bombs/boots until later, they would not be able to get back downstairs.  This could be fine, if nothing more than a MAJOR nuisance (not casual!), if not for the lock below...  This has been a VERY difficult seed (which is fine).

**Comment by biohazardtx** [comment]
Can you take the warp in front of the island in the light world where the ice palace is to go to Zora's Domain?  I think that's the one that takes you to the top without any gloves.

**Comment by jakj** [comment]
That warp goes only to ice palace. You can't jump out from the walled-in area.

**Comment by BlueViper85** [comment]
This is definitely an interesting seed; however, it does seem beatable, but certainly provides a bit more challenge than others.

I can't playtest at the moment to confirm but I'm fairly confident that the block you have to lift in the Cane of Byrna (spike) cave requires the Power Gloves OR the Titan's Mitts.  It does also require the moonpearl, hammer, and some sort of health item (potions, invincibility from cape/cane of byrna, plenty of hearts, fairies, etc...)

Power gloves are in the Haunted Grove which you dig up in the Light World with the Shovel
Shovel is at King Zora

You can access King Zora via the Whirlpool in front of Ice Palace as biohazardtx mentioned it will take you to the area just south of Zora's Domain where you can walk/swim up to Zora by following the shallow water path.

Forgot the hammer.  You'll need the Magic Mirror from the Witch which requires the Mushroom from the well in Kakariko village. The Big Key is accessible in Hera without the lamp or firerod so you should have no issues getting to the big chest with the Hammer.

---

As for the concern about the final basement room in Escape, you can access that room via the top-left gravestone in the cemetery after the fact, provided you have at least the power gloves.

I'll leave this open until you are either able to confirm that this works, or when I can play through this seed to confirm later tonight.

**Comment by the-bacon-sword** [comment]
Son of a gun.  Yep, that water warp did it.  Access to Zora.  The dominoes shall fall. I'll be able to proceed. 

Keep up the great work, guys.

**Comment by BlueViper85** [comment]
Thanks for the follow up!  Let us know if you run into any more issues, questions, concerns, or suggestions!

**Comment by the-bacon-sword** [comment]
I think a suggestion is inbound...I may have a solution to the difficulty setting situation...
