### ISSUE TITLE
Seed C0000727

### ISSUE THREAD

**Issue by txkazzalane** [Dessyreqt/alttprandomizer#198]
Is this unbeatable or am I just not being creative enough?  Thanks. 

A Link to the Past Randomizer Log
---------------------------------
Version: 6
Creation Date: 9/30/2016 5:55:03 PM
Seed: C0000727

Generated Item Order
--------------------
[cave-026] chicken house..................................................................Flippers
[cave-050] cave southwest of Lake Hylia - generous guy....................................Shovel
Haunted Grove item........................................................................Mushroom
[dungeon-C-1F] Sanctuary..................................................................Bottle (Gold Bee)
[cave-021] Kakariko well [center chest row of 3]..........................................Power Glove
Witch.....................................................................................Pegasus Boots
[cave-044] Aginah's cave..................................................................Hookshot
[cave-047] Dam............................................................................Cape
[cave-022-B1] Thief's hut [top right chest]...............................................Moon Pearl
[cave-063] doorless hut...................................................................Titan's Mitt
[cave-009-1F] Death Mountain - wall of caves - right cave [top right chest]...............Fire Rod
Piece of Heart (Maze Race)................................................................Ocarina
[cave-018] Graveyard - top right grave....................................................Book of Mudora
[dungeon-C-B1] Hyrule Castle - map room...................................................Quake
[cave-057-1F] Dark World Death Mountain - cave from top to bottom [bottom chest]..........Magic Mirror
Piece of Heart (Lake Hylia)...............................................................Lamp
[dungeon-D5-B1] Ice Palace - compass room.................................................Hammer
[dungeon-D2-B1] Swamp Palace - map room...................................................Bow
Piece of Heart (Dark World - bumper cave).................................................Ether
Flute Boy.................................................................................Cane of Somaria
[dungeon-D4-B2] Thieves' Town - next to Blind.............................................Ice Rod

**Comment by BlueViper85** [comment]
First glance says this is beatable. Not sure if you're looking for a full solution or not so I'll leave it at that for now.

If you need any hints or have any specific concerns about the seed, just ask!  I'll close this, but if you need more details you can still comment.

**Comment by txkazzalane** [comment]
Ok.... Hmmmm... I think I have all I can get, 
I need the Titans mitt to get to the Swamp palace for the bow, so that is a no go.
I need the mirror to get into the Ice palace for the hammer.
I need the hammer to get to the village to get the Titans mitt.
I need the Titans mitt to get to the dark world on the other side of death mountain to get the mirror.
I need the Titans mitt to get the book.

What am I not thinking about?

**Comment by BlueViper85** [comment]
You have access to the cape, which provides access to Agahnim'a Tower. Beat that to get to the dark world.

You can follow the path from the pyramid up the right side of the river and there's a small gap to hookshot across the river (skull rocks just off screen to grab on to, look for an arrow in the grass)

**Comment by txkazzalane** [comment]
Omg. I am so dumb. Lol. Thanks.

**Comment by BlueViper85** [comment]
Not dumb at all, it's not a common method. I believe that one is documented on the main download page for randomizer though.  Keep an eye on that page for information and tips for things that change with future updates!

Good luck and let us know if you need anything else!
