### ISSUE TITLE
Old man has gloves, no way to get to him

### ISSUE THREAD

**Issue by screevo** [Dessyreqt/alttprandomizer#2]
[ALttP_Random_-_C8563555.sfc.spoilers (1).txt](https://github.com/Dessyreqt/alttprandomizer/files/288795/ALttP_Random_-_C8563555.sfc.spoilers.1.txt)
Broken - Old man has gloves, no way to get to him.

**Comment by Dessyreqt** [comment]
According to the file you uploaded, King Zora has the gloves and the Mountain Man has the Mirror... you should be able to teleport from just below the entrance to Ice to the Zora area.

**Comment by Dessyreqt** [comment]
This is confirmed to be a misreading issue.
