### ISSUE TITLE
Client Update: Turn On/Off Safeties

### ISSUE THREAD

**Issue by Nicholas-Steel** [Dessyreqt/alttprandomizer#201]
It would be an interesting experience if there was no risk of accidentally getting the armour upgrades. (Other things that are super helpful like the Blue Cane and Cape can be toggled by the player after they're found so they're not an issue).

Edit: This report is now used for discussing making the Item Pool configurable to make the game harder. For example the ability to remove (or toggle between in-game) armour, sword and shield upgrades from the game.

**Comment by BlueViper85** [comment]
I can certainly see the appeal of something like this, though I do question how much use it might actually get. Not sure what the general consensus on this thought is though.more comments/feedback welcome.

**Comment by Nicholas-Steel** [comment]
How about an option to make the armour upgrades worsen your defense against enemy attacks? So there'd be 2 booby prizes to discover at random >: )

Good for those that find the current game fairly easy.

**Comment by ChristosOwen** [comment]
I've actually briefly suggested being able to toggle between swords, shields and mails in a future version, so this is something we could perhaps pursue.

Similarly I was thinking it could be good to customize difficulty by giving the user the option over what non-essential items are included in the item pool. For example, one could remove (or limit) the armour upgrades, as well as heart pieces, heart containers, mail/shield/capacity upgrades, bottles etc.

This is something we'll discuss and think about for a future version.

Thanks for your input.

**Comment by BlueViper85** [comment]
As for the concept of downgrading the mails or having new items that make you take more damage:
1. Downgrading mails is explicitly guarded for the fact that it can, and will cause confusion and in some cases frustration in general. Opening that back up opens the window for several new problems.
2. Creating new items to increase damage sort of goes against the idea of Randomizer.  Randomizer is meant to be as close to the original game (with some new features, like toggling between shovel/flute or mushroom/powder).  Creating new items people wouldn't expect to see distances us from that concept and introduces a greater amount of development time that provides little benefit over the previously-mentioned toggling options.

As a side note for #2, though, you may inquire about 1/4 magic.  This was a feature that was already built into the original game but wasn't actually turned on. We simply enabled something that was hidden in the original game.

Sticking with the idea of toggle-able features in future versions seems like the right way to go if something like this were implemented in future versions.

**Comment by KatDevsGames** [comment]
As others have already mentioned, removeable items from the pool as as a custom option is certainly possible. Alternately, downgrades go against one of the main goals of randomizer and are unlikely to appear in a future release.

**Comment by Nicholas-Steel** [comment]
ChrstosOwen, hmm, well, stuff that worsens the difficulty would be optional, deselected by default and maybe have the settings for it presented on its own tab in the Randomizer UI (assuming devs would be okay with a tabbed UI).

The armour and sword upgrades completely wreck the games difficulty lol and with the randomizer you can't avoid them (unless you look up their locations in advance I guess).

**Comment by ChristosOwen** [comment]
Items which have a detrimental effect and aren't in the original game are not something we're looking to implement. 

With the ability to toggle swords/shields/mails, even if you pick up the blue/red mail, or collect the master/tempered/golden sword, you can simply toggle back to green mail and fighter's sword if you want more of a challenge.

**Comment by Nicholas-Steel** [comment]
Yeah toggling them is a fine alternative.

**Comment by ChristosOwen** [comment]
I get where you're coming from as I also love to do challenging things in this game!

There's also a program called plandomizer (planned randomizer) which lets you choose yourself which items go where and is compatible with the randomizer. This would allow you to exclude any/all safeties for a more challenging playthrough. You can find it here: goo.gl/xz0X1b.

Although as I said, in future versions we will add customizability for various things before generating a seed to allow you to set the difficulty to your preferences a lot more easily.

**Comment by ChristosOwen** [comment]
Also you can find the alttp speedrun community, including the randomizer people, on Discord here:

https://discordapp.com/invite/3Bsfnwk

We talk about the development a lot and you can see what's coming up in future releases too.

**Comment by KatDevsGames** [comment]
We need to spec out how we want this to work in terms of buttonpresses/submenus/etc. Any thoughts?

**Comment by Nicholas-Steel** [comment]
Well, we have the Y & X buttons already used for toggling stuff in the submenu and currently no way to move the selection courser over the Armour and Sword. Perhaps you could make Select (or L & R) move the courser to the Armour and Sword area? Then you can make X/Y cycle through them as you hover over 'em just like what happens with mushroom, shovel, bow & arrow, Boomerang etc.

But I thought the general consensus was to not have it functionable in-game?  ie: an option to remove swords/armour's from the game would be a part of the Randomizer application instead of an in-game toggle.

**Comment by ChristosOwen** [comment]
At the moment Select already toggles between pendants/crystals. 

We could change that so Select moves between the 3 relevant sections of the menu (main Y items area, sword/shields/mails area, moon pearl/flippers/gloves/etc area) or perhaps it may be better to use L+R to cycle left and right through these areas.

Then using the already existing X/Y commands for toggling through items, and where relevant, opening a sub-menu. I would probobaly say anything with just 2 items to choose from doesn't get a sub-menu but anything with more does, i.e.

Swords: Sub-menu (4 spaces) + toggling
Shields: Sub-menu (3 spaces) + toggling
Mails: Sub-menu (3 spaces) + toggling
Gloves: toggling only

Although depending on complexity/vram etc I would say prioritising the toggling rather than the sub-menus is a good call. Over to you Karkat :)

**Comment by Nicholas-Steel** [comment]
I don't really see a huge need for a sub-menu for the swords, shields & armour but I guess it would help completionists identify if their missing something? I mean it'd almost certainly be faster for a speed runner to just rapidly tap the Cycle button instead of accessing the sub-menu to select an item.

The sub-menu idea only really works for the Bottles because there are so many of them and they can hold a sizable number of different things, making them fairly complex to manage.

**Comment by Dessyreqt** [comment]
![inv mockup](https://cloud.githubusercontent.com/assets/12574786/21509400/425f6adc-cc4e-11e6-8850-057312a4d1de.png)

Mockup for potential inventory screen change that would free select up.

**Comment by BlueViper85** [comment]
With 4 swords being possible I can see a sub menu for that. Shield and mails i don't see it being as useful. 

Alternatively, if select were freed up, I like the idea of using Select to switch to the equipment section and then X to cycle one direction through the list and Y to cycle the other direction.

I'm not sure I see value in changing the gloves/mitts though?

**Comment by ChristosOwen** [comment]
Combining pendants and crystals seems like a good idea. Using Select to toggle between the areas of the menu also seems like a good idea. Gloves/Mitts toggle was more for completion than anything useful.

Alternatively instead of doing this kind of change, we could simply leave it as it is and let the user choose if they want to remove sword/shield/mail upgrades from the item pool in the client? Could do the same with heart containers, heart pieces, bottles and other safety items too if we wanted.

That may be a cleaner thing to do? Ultimately this menu change doesn't add anything to randomization, the only beneficial thing it does is allow you to toggle sword for Mothula if you have Gold Sword, but we have patched that already.

**Comment by ChristosOwen** [comment]
After thinking on this I actually much prefer having the client allow you to remove safeties if you want to opposed to changing in-game mechanics to toggle between equipment, so this is what we'll do

**Comment by Nicholas-Steel** [comment]
That's what I figured was the consensus we originally came to.

**Comment by nickretallack** [comment]
Removing items from the randomization pool seems trivially easy.

Adding new in-game UI seems pretty difficult.

**Comment by ChristosOwen** [comment]
The original request is now possible via the difficulty settings on the web version: http://vt.alttp.run/

Closing due to being historic
