### ISSUE TITLE
How to contribute?

### ISSUE THREAD

**Issue by thejoshwolfe** [Dessyreqt/alttprandomizer#202]
I'm excited for v7 to come out soon, and I was wondering if more manpower could help the process along.

I'm experienced enough as a programmer, that I know the answer could easily be no. If @Dessyreqt is busy and wants to get it done alone, I can definitely sympathize with that. But in the off chance that there's something I can do to help, I'd be happy to contribute!

When I made #199, I attempted to avoid changing code that I thought was likely to be affected by the v7 changes so that it wouldn't cause any merge conflicts. Are there any changes that are isolated from what @Dessyreqt is working on that I can help out with?

Separately from the v7 road map, I was considering attempting #183, which should be much more approachable with #199 done.

**Comment by Dessyreqt** [comment]
At the moment things are a bit of a mess. I'm still in the old habits of single-person development, which means I have a ton of stuff written locally and none of it is fit to commit at this moment.

#199 looks like a good change, but it will probably conflict with some of the changes I have made. We'll see. Unfortunately I'm just the bottleneck right now. I don't have any projections at this moment, but I'm trying to squeeze as much time as I can from being on the train and so on. Please be patient. I will revamp the process for v8 and higher to be more inclusive to more contributors.

**Comment by thejoshwolfe** [comment]
Ok, no problem.

Hope to see v7 soon! :)
