### ISSUE TITLE
Seed C7753798 Unbeatable?

### ISSUE THREAD

**Issue by DSparil316** [Dessyreqt/alttprandomizer#205]
The mirror and hammer are both located in the same cave:
[cave-056] Dark World Death Mountain - cave under boulder [bottom left chest].............Hammer
[cave-056] Dark World Death Mountain - cave under boulder [top right chest]...............Magic Mirror

I believe the only way to get to this cave is by going through the Turtle Rock teleporter. However, the only way to access this teleporter is by hitting the three stakes on top of Turtle Rock's location in the light world. 
So I basically need the hammer in order to GET the hammer, as well as the mirror? Or is there another way to the top of Death Mountain that doesn't require the hammer or mirror that I'm just unaware of?

**Comment by BlueViper85** [comment]
A quick look at the spoiler log suggests that this is beatable.  You will need at least the following items, which I have confirmed are all accessible:
- Hookshot
- Titan's Mitts
- Moon Pearl

Get to Death Mountain in the light world, whether by walking, or flute, or Save and Quit (if available).  Follow the lower path as far right as you can until you reach the broken bridge.  Hookshot across the bridge.  Follow the path until you can go south.  You will see a dark rock next to a large formation on the mountain.  Lift this up to reveal a portal to the dark world.  Once in the dark world, walk north of there to find two cave entrances next to each other.  Use the left cave entrance, and navigate the cave system (it's a little confusing, but will provide access to two chests as well). Once you find your way through the cave you'll be taken to the top of death mountain right next to the boulder that you have to lift to reveal the cave with the items in question.

I use a slightly different method going through the cave I mentioned, but here's a clip from a run of mine where I use this cave to access this very cave if it will help at all: https://www.twitch.tv/blueviper85/v/96544340?t=01h26m09s

I'm closing this issue, as this is solvable.  However, if you have any remaining questions or concerns you can still comment, and if any bugs are identified it can be reopened at that time (though I don't expect any bugs to stem from this).

Thanks for your feedback, and please let us know if you run into any further troubles!
