### ISSUE TITLE
[v6] Seed C9918066 flippers

### ISSUE THREAD

**Issue by Dessyreqt** [Dessyreqt/alttprandomizer#206]
Submitter: Vincent
[v6]

Hi, i have an issue in the seed C9918066 that's blocking me from advencing any further than the first pendant. In the spoiler it says that the flippers are in the big chest, but in the game they're not there. I'm stuck without the flippers and without the power glove or the titan's mitt, so i don't know what to do but i cannot finish the second pendant donjon and cannot access the mountain.

**Comment by BlueViper85** [comment]
No email provided so I can't provide an answer directly to the submitter. Response is below no less. I will keep this open today for visibility and close tomorrow or late this evening if no response is provided.

The randomizer is often not beatable in the normal dungeon order. You will need to use the items you can find to get access to the chests they allow. This includes early access to the dark world and the ability to beat all dark world dungeons without beating the light world in many cases.

That being said, the spoiler log should always match the chest contents, though it isn't impossible that a bug could cause them to be different.

Can you provide a copy of your ROM file?

**Comment by Nicelink81** [comment]
Where can I find said spoiler log? I am having issues with the Flippers and yes ive been playing it out of order. Doing a lets play and have been stuck for 2 episodes lol

**Comment by BlueViper85** [comment]
On the application you use to generate the ROM there is an option for "Generate Spoiler Log" check that and then click Generate. It will generate both the ROM and a TXT file with the location of all items.

If you already generated the ROM and want the spoiler log for that same seed just type the seed number into the Randomizer before clicking Generate.

The seed number is available in the ROM file name (will start with a C) if you didn't change it or will load in the text that appears on the Emulator when you first load it. If your emulator doesn't show it (some don't) you can provide us with the SFC file and we can get it for you.

If you need any help figuring out how to progress feel free to ask here. A link to your let's play (if it's posted and watchable) will also help us to help you.

**Comment by Nicelink81** [comment]
I have no idea how to do any of that

```
On Saturday, November 19, 2016 9:05 PM, BlueViper85 <notifications@github.com> wrote:
```

 On the application you use to generate the ROM there is an option for "Generate Spoiler Log" check that and then click Generate. It will generate both the ROM and a TXT file with the location of all items.If you already generated the ROM and want the spoiler log for that same seed just type the seed number into the Randomizer before clicking Generate.The seed number is available in the ROM file name (will start with a C) if you didn't change it or will load in the text that appears on the Emulator when you first load it. If your emulator doesn't show it (some don't) you can provide us with the SFC file and we can get it for you.If you need any help figuring out how to progress feel free to ask here. A link to your let's play (if it's posted and watchable) will also help us to help you.—

**Comment by Nicelink81** [comment]
https://www.youtube.com/watch?v=BzLg4 That is my LP. Not really sure how to do all that other stuff :P

**Comment by BlueViper85** [comment]
Open the randomizer and look at the top of the window for the options I mentioned. The rest is dependent on your computer and emulator and I can't help too much there.

**Comment by Nicelink81** [comment]
Open it on the emulator?

**Comment by Nicelink81** [comment]
Nevermind i got it. Thank you for your time and help. also thanks for the cool spin on a great game will give you a shout out in my series finale

**Comment by BlueViper85** [comment]
Awesome. Good luck!  Let us know if you need any more help!

**Comment by ChristosOwen** [comment]
BV is too strong! 👍

**Comment by BlueViper85** [comment]
NiceLink. I assume you found your seed number. But if not, it was on screen at the end of your second video. C2455838.

**Comment by Nicelink81** [comment]
Yes I did. Thank you for watching :) Feel free to sub :D
