### ISSUE TITLE
[v6] Dark Palace softlock

### ISSUE THREAD

**Issue by Dessyreqt** [Dessyreqt/alttprandomizer#207]
Submitter: Michael 
[v6] if a small key and the big key spawns in the maze room in the Dark Palace it is possible to get soft-locked if all other small keys are used before unlocking the door to the maze room.

An example of this can be found in seed C1010111

**Comment by BlueViper85** [comment]
There are known issues with the logic for Palace of Darkness in v6 (including key placements and item requirements) The logic has been fixed and will be included when v7 is complete and ready for release.
