### ISSUE TITLE
Dark Palace Maze Room blocked off, may prevent game from being beatable.

### ISSUE THREAD

**Issue by BHughes0189** [Dessyreqt/alttprandomizer#209]
Seed: C7454627
[dungeon-D1-1F] Dark Palace - maze room [top chest].......................................Fire Rod
[dungeon-D1-1F] Dark Palace - maze room [bottom chest]....................................Key
[dungeon-D1-1F] Dark Palace - big chest...................................................20 Rupees

If entering the Palace of Darkness with the **hammer** already obtained, it's possible to use up five of the six keys found within the dungeon before going into the maze room. Since one of the keys can be found within the maze room, and there's only one entrance to the maze room that requires a key, two of the randomized chests can become inaccessible. Using the seed above, the Fire Rod became unobtainable which is required for the four torch puzzle of Turtle Rock (Dungeon 7, first floor).

**Comment by BlueViper85** [comment]
This is a known issue with the logic for this dungeon. It has been addressed per issue #123 and will be corrected when v7 is released. Until then, s long as the door downstairs isn't unlocked until everything else has been done, you shouldn't have issues.
