### ISSUE TITLE
Cant get moon pearl

### ISSUE THREAD

**Issue by cptnbean** [Dessyreqt/alttprandomizer#210]
I don't know if it is me just being oblivious to the solution or what, but I'm stuck. HELP please

A Link to the Past Randomizer Log
---------------------------------
Version: 6
Creation Date: 22/11/2016 13:57:29
Seed: C3625279

Generated Item Order
--------------------
[cave-021] Kakariko well [top chest]......................................................Cape
[cave-040] Link's House...................................................................Bow
[cave-035] Sahasrahla's Hut [left chest]..................................................Book of Mudora
[cave-022-B1] Thief's hut [bottom right chest]............................................Bottle (Green Potion)
[cave-021] Kakariko well [left chest row of 3]............................................Shovel
Sahasrahla................................................................................Mushroom
Piece of Heart (Dam)......................................................................Ocarina
[cave-021] Kakariko well [bottom chest]...................................................Flippers
[cave-021] Kakariko well [right chest row of 3]...........................................Pegasus Boots
[dungeon-C-B3] Hyrule Castle - next to Zelda..............................................Titan's Mitt
Bottle Vendor.............................................................................Magic Mirror
[cave-050] cave southwest of Lake Hylia [bottom right chest]..............................Fire Rod
Witch.....................................................................................Hookshot
Piece of Heart (Desert - northeast corner)................................................Moon Pearl
[cave-056] Dark World Death Mountain - cave under boulder [top left chest]................Lamp
[cave-056] Dark World Death Mountain - cave under boulder [bottom left chest].............Hammer
[dungeon-D2-B1] Swamp Palace - big chest..................................................Quake
[cave-057-1F] Dark World Death Mountain - cave from top to bottom [top chest].............Cane of Somaria
[cave-013] Mimic cave (from Turtle Rock)..................................................Ice Rod

Light World
-----------
[cave-009-1F] Death Mountain - wall of caves - right cave [bottom chest]..................3 Bombs
[cave-009-1F] Death Mountain - wall of caves - right cave [top left chest]................10 Arrows
[cave-009-1F] Death Mountain - wall of caves - right cave [top left middle chest].........Red Boomerang
[cave-009-1F] Death Mountain - wall of caves - right cave [top right chest]...............20 Rupees
[cave-009-1F] Death Mountain - wall of caves - right cave [top right middle chest]........Piece of Heart
[cave-009-B1] Death Mountain - wall of caves - right cave [left chest]....................Piece of Heart
[cave-009-B1] Death Mountain - wall of caves - right cave [right chest]...................Bug-Catching Net
[cave-012-1F] Death Mountain - wall of caves - left cave..................................Piece of Heart
[cave-013] Mimic cave (from Turtle Rock)..................................................Ice Rod
[cave-016] cave under rocks west of Santuary..............................................3 Bombs
[cave-018] Graveyard - top right grave....................................................3 Bombs
[cave-021] Kakariko well [bottom chest]...................................................Flippers
[cave-021] Kakariko well [center chest row of 3]..........................................20 Rupees
[cave-021] Kakariko well [left chest row of 3]............................................Shovel
[cave-021] Kakariko well [right chest row of 3]...........................................Pegasus Boots
[cave-021] Kakariko well [top chest]......................................................Cape
[cave-022-B1] Thief's hut [bottom left chest].............................................300 Rupees
[cave-022-B1] Thief's hut [bottom right chest]............................................Bottle (Green Potion)
[cave-022-B1] Thief's hut [top chest].....................................................Piece of Heart
[cave-022-B1] Thief's hut [top left chest]................................................5 Rupees
[cave-022-B1] Thief's hut [top right chest]...............................................Piece of Heart
[cave-026] chicken house..................................................................20 Rupees
[cave-031] Tavern.........................................................................Piece of Heart
[cave-034] Hyrule Castle secret entrance..................................................Heart Container
[cave-035] Sahasrahla's Hut [center chest]................................................20 Rupees
[cave-035] Sahasrahla's Hut [left chest]..................................................Book of Mudora
[cave-035] Sahasrahla's Hut [right chest].................................................100 Rupees
[cave-040] Link's House...................................................................Bow
[cave-044] Aginah's cave..................................................................20 Rupees
[cave-047] Dam............................................................................10 Arrows
[cave-050] cave southwest of Lake Hylia - generous guy....................................50 Rupees
[cave-050] cave southwest of Lake Hylia [bottom left chest]...............................100 Rupees
[cave-050] cave southwest of Lake Hylia [bottom right chest]..............................Fire Rod
[cave-050] cave southwest of Lake Hylia [top left chest]..................................Power Glove
[cave-050] cave southwest of Lake Hylia [top right chest].................................1 Arrow
[cave-051] Ice Cave.......................................................................3 Bombs
Bombos....................................................................................50 Rupees
Bottle Vendor.............................................................................Magic Mirror
Ether.....................................................................................50 Rupees
Haunted Grove item........................................................................3 Bombs
Hobo......................................................................................20 Rupees
King Zora.................................................................................10 Arrows
Library...................................................................................Piece of Heart
Mushroom..................................................................................20 Rupees
Old mountain man..........................................................................Red Shield
Piece of Heart (Dam)......................................................................Ocarina
Piece of Heart (Death Mountain - floating island).........................................Piece of Heart
Piece of Heart (Desert - northeast corner)................................................Moon Pearl
Piece of Heart (Desert - west side).......................................................100 Rupees
Piece of Heart (Graveyard)................................................................20 Rupees
Piece of Heart (Lake Hylia)...............................................................10 Arrows
Piece of Heart (Lumberjack Tree)..........................................................3 Bombs
Piece of Heart (Maze Race)................................................................300 Rupees
Piece of Heart (south of Haunted Grove)...................................................5 Rupees
Piece of Heart (Spectacle Rock Cave)......................................................Piece of Heart
Piece of Heart (Spectacle Rock)...........................................................20 Rupees
Piece of Heart (Thieves' Forest Hideout)..................................................1 Rupee
Piece of Heart (Zora's River).............................................................Piece of Heart
Purple Chest..............................................................................20 Rupees
Sahasrahla................................................................................Mushroom
Sick Kid..................................................................................Blue Mail
Witch.....................................................................................Hookshot

Dark World
----------
[cave-055] Spike cave.....................................................................Magic Powder
[cave-056] Dark World Death Mountain - cave under boulder [bottom left chest].............Hammer
[cave-056] Dark World Death Mountain - cave under boulder [bottom right chest]............20 Rupees
[cave-056] Dark World Death Mountain - cave under boulder [top left chest]................Lamp
[cave-056] Dark World Death Mountain - cave under boulder [top right chest]...............20 Rupees
[cave-057-1F] Dark World Death Mountain - cave from top to bottom [bottom chest]..........3 Bombs
[cave-057-1F] Dark World Death Mountain - cave from top to bottom [top chest].............Cane of Somaria
[cave-062] C-shaped house.................................................................Boomerang
[cave-063] doorless hut...................................................................20 Rupees
[cave-071] Misery Mire west area [left chest].............................................10 Arrows
[cave-071] Misery Mire west area [right chest]............................................Bombos
[cave-073] cave northeast of swamp palace - generous guy..................................20 Rupees
[cave-073] cave northeast of swamp palace [bottom chest]..................................300 Rupees
[cave-073] cave northeast of swamp palace [bottom middle chest]...........................100 Rupees
[cave-073] cave northeast of swamp palace [top chest].....................................20 Rupees
[cave-073] cave northeast of swamp palace [top middle chest]..............................Piece of Heart
Catfish...................................................................................Bottle (Blue Potion)
Flute Boy.................................................................................100 Rupees
Piece of Heart (Dark World - bumper cave).................................................3 Bombs
Piece of Heart (Dark World blacksmith pegs)...............................................1 Rupee
Piece of Heart (Digging Game).............................................................20 Rupees
Piece of Heart (Pyramid)..................................................................3 Bombs
Piece of Heart (Treasure Chest Game)......................................................50 Rupees

Hyrule Castle Escape
--------------------
[dungeon-C-1F] Sanctuary..................................................................100 Rupees
[dungeon-C-B1] Escape - final basement room [left chest]..................................Piece of Heart
[dungeon-C-B1] Escape - final basement room [middle chest]................................Bottle (Blue Potion)
[dungeon-C-B1] Escape - final basement room [right chest].................................3 Bombs
[dungeon-C-B1] Escape - first B1 room.....................................................Map
[dungeon-C-B1] Hyrule Castle - boomerang room.............................................Piece of Heart
[dungeon-C-B1] Hyrule Castle - map room...................................................Key
[dungeon-C-B3] Hyrule Castle - next to Zelda..............................................Titan's Mitt

Eastern Palace
--------------
[dungeon-L1-1F] Eastern Palace - big ball room............................................20 Rupees
[dungeon-L1-1F] Eastern Palace - big chest................................................20 Rupees
[dungeon-L1-1F] Eastern Palace - Big key..................................................Map
[dungeon-L1-1F] Eastern Palace - compass room.............................................Big Key
[dungeon-L1-1F] Eastern Palace - map room.................................................Compass

Desert Palace
-------------
[dungeon-L2-B1] Desert Palace - big chest.................................................Piece of Heart
[dungeon-L2-B1] Desert Palace - Big key room..............................................Map
[dungeon-L2-B1] Desert Palace - compass room..............................................Compass
[dungeon-L2-B1] Desert Palace - Map room..................................................Big Key

Tower of Hera
-------------
[dungeon-L3-1F] Tower of Hera - first floor...............................................Big Key
[dungeon-L3-2F] Tower of Hera - Entrance..................................................Compass
[dungeon-L3-4F] Tower of Hera - 4F [small chest]..........................................3 Bombs
[dungeon-L3-4F] Tower of Hera - big chest.................................................Map

Hyrule Castle Tower
-------------------
[dungeon-A1-2F] Hyrule Castle Tower - 2 knife guys room...................................Key
[dungeon-A1-3F] Hyrule Castle Tower - maze room...........................................Key

Dark Palace
-----------
[dungeon-D1-1F] Dark Palace - big chest...................................................Map
[dungeon-D1-1F] Dark Palace - big key room................................................50 Rupees
[dungeon-D1-1F] Dark Palace - compass room................................................3 Bombs
[dungeon-D1-1F] Dark Palace - jump room [left chest]......................................Key
[dungeon-D1-1F] Dark Palace - jump room [right chest].....................................Piece of Heart
[dungeon-D1-1F] Dark Palace - maze room [bottom chest]....................................Piece of Heart
[dungeon-D1-1F] Dark Palace - maze room [top chest].......................................Key
[dungeon-D1-1F] Dark Palace - spike statue room...........................................Compass
[dungeon-D1-1F] Dark Palace - statue push room............................................Key
[dungeon-D1-B1] Dark Palace - room leading to Helmasaur [left chest]......................Big Key
[dungeon-D1-B1] Dark Palace - room leading to Helmasaur [right chest].....................Key
[dungeon-D1-B1] Dark Palace - shooter room................................................Key
[dungeon-D1-B1] Dark Palace - turtle stalfos room.........................................Key

Swamp Palace
------------
[dungeon-D2-1F] Swamp Palace - first room.................................................Key
[dungeon-D2-B1] Swamp Palace - big chest..................................................Quake
[dungeon-D2-B1] Swamp Palace - big key room...............................................Big Key
[dungeon-D2-B1] Swamp Palace - map room...................................................10 Arrows
[dungeon-D2-B1] Swamp Palace - push 4 blocks room.........................................20 Rupees
[dungeon-D2-B1] Swamp Palace - south of hookshot room.....................................Piece of Heart
[dungeon-D2-B2] Swamp Palace - flooded room [left chest]..................................Map
[dungeon-D2-B2] Swamp Palace - flooded room [right chest].................................50 Rupees
[dungeon-D2-B2] Swamp Palace - hidden waterfall door room.................................Compass

Skull Woods
-----------
[dungeon-D3-B1] Skull Woods - big chest...................................................3 Bombs
[dungeon-D3-B1] Skull Woods - Big Key room................................................Big Key
[dungeon-D3-B1] Skull Woods - Compass room................................................Compass
[dungeon-D3-B1] Skull Woods - east of Fire Rod room.......................................Key
[dungeon-D3-B1] Skull Woods - Entrance to part 2..........................................Map
[dungeon-D3-B1] Skull Woods - Gibdo/Stalfos room..........................................Key
[dungeon-D3-B1] Skull Woods - south of Fire Rod room......................................Key

Thieves Town
------------
[dungeon-D4-1F] Thieves' Town - Room above boss...........................................Compass
[dungeon-D4-B1] Thieves' Town - Bottom left of huge room [bottom right chest].............Key
[dungeon-D4-B1] Thieves' Town - Bottom left of huge room [top left chest].................Piece of Heart
[dungeon-D4-B1] Thieves' Town - Bottom right of huge room.................................Big Key
[dungeon-D4-B1] Thieves' Town - Top left of huge room.....................................10 Arrows
[dungeon-D4-B2] Thieves' Town - big chest.................................................Map
[dungeon-D4-B2] Thieves' Town - next to Blind.............................................10 Arrows

Ice Palace
----------
[dungeon-D5-B1] Ice Palace - Big Key room.................................................Big Key
[dungeon-D5-B1] Ice Palace - compass room.................................................Key
[dungeon-D5-B2] Ice Palace - map room.....................................................Key
[dungeon-D5-B3] Ice Palace - spike room...................................................Map
[dungeon-D5-B4] Ice Palace - above Blue Mail room.........................................50 Rupees
[dungeon-D5-B5] Ice Palace - b5 up staircase..............................................Compass
[dungeon-D5-B5] Ice Palace - big chest....................................................20 Rupees

Misery Mire
-----------
[dungeon-D6-B1] Misery Mire - big chest...................................................Map
[dungeon-D6-B1] Misery Mire - big hub room................................................Key
[dungeon-D6-B1] Misery Mire - big key.....................................................Bottle (Gold Bee)
[dungeon-D6-B1] Misery Mire - compass.....................................................Compass
[dungeon-D6-B1] Misery Mire - end of bridge...............................................Key
[dungeon-D6-B1] Misery Mire - map room....................................................Big Key
[dungeon-D6-B1] Misery Mire - spike room..................................................Key

Turtle Rock
-----------
[dungeon-D7-1F] Turtle Rock - Chain chomp room............................................Compass
[dungeon-D7-1F] Turtle Rock - compass room................................................10 Arrows
[dungeon-D7-1F] Turtle Rock - Map room [left chest].......................................Key
[dungeon-D7-1F] Turtle Rock - Map room [right chest]......................................Key
[dungeon-D7-B1] Turtle Rock - big chest...................................................Piece of Heart
[dungeon-D7-B1] Turtle Rock - big key room................................................Big Key
[dungeon-D7-B1] Turtle Rock - Roller switch room..........................................Key
[dungeon-D7-B2] Turtle Rock - Eye bridge room [bottom left chest].........................Key
[dungeon-D7-B2] Turtle Rock - Eye bridge room [bottom right chest]........................Piece of Heart
[dungeon-D7-B2] Turtle Rock - Eye bridge room [top left chest]............................20 Rupees
[dungeon-D7-B2] Turtle Rock - Eye bridge room [top right chest]...........................Map

Ganon's Tower
-------------
[dungeon-A2-1F] Ganon's Tower - above Armos...............................................Piece of Heart
[dungeon-A2-1F] Ganon's Tower - big chest.................................................Piece of Heart
[dungeon-A2-1F] Ganon's Tower - compass room [bottom left chest]..........................Staff of Byrna
[dungeon-A2-1F] Ganon's Tower - compass room [bottom right chest].........................Piece of Heart
[dungeon-A2-1F] Ganon's Tower - compass room [top left chest].............................10 Arrows
[dungeon-A2-1F] Ganon's Tower - compass room [top right chest]............................Key
[dungeon-A2-1F] Ganon's Tower - down right staircase from entrance [left chest]...........Key
[dungeon-A2-1F] Ganon's Tower - down right staircase from entrance [right chest]..........20 Rupees
[dungeon-A2-1F] Ganon's Tower - east of down right staircase from entrace.................300 Rupees
[dungeon-A2-1F] Ganon's Tower - map room..................................................Map
[dungeon-A2-1F] Ganon's Tower - north of gap room [bottom left chest].....................3 Bombs
[dungeon-A2-1F] Ganon's Tower - north of gap room [bottom right chest]....................Red Mail
[dungeon-A2-1F] Ganon's Tower - north of gap room [top left chest]........................Key
[dungeon-A2-1F] Ganon's Tower - north of gap room [top right chest].......................3 Bombs
[dungeon-A2-1F] Ganon's Tower - north of teleport room....................................3 Bombs
[dungeon-A2-1F] Ganon's Tower - west of teleport room [bottom left chest].................Piece of Heart
[dungeon-A2-1F] Ganon's Tower - west of teleport room [bottom right chest]................Compass
[dungeon-A2-1F] Ganon's Tower - west of teleport room [top left chest]....................20 Rupees
[dungeon-A2-1F] Ganon's Tower - west of teleport room [top right chest]...................Big Key
[dungeon-A2-6F] Ganon's Tower - before Moldorm............................................20 Rupees
[dungeon-A2-6F] Ganon's Tower - Moldorm room..............................................Mirror Shield
[dungeon-A2-6F] Ganon's Tower - north of falling floor four torches [top left chest]......20 Rupees
[dungeon-A2-6F] Ganon's Tower - north of falling floor four torches [top right chest].....3 Bombs
[dungeon-A2-B1] Ganon's Tower - north of Armos room [bottom chest]........................20 Rupees
[dungeon-A2-B1] Ganon's Tower - north of Armos room [left chest]..........................10 Arrows
[dungeon-A2-B1] Ganon's Tower - north of Armos room [right chest].........................Ether

Special Locations
-----------------
Magic Bat.................................................................................1/4 Magic
Misery Mire Required Medallion............................................................Quake
Pyramid Bottle Item.......................................................................Bottle (Green Potion)
Turtle Rock Required Medallion............................................................Quake
Waterfall Bottle Item.....................................................................Bottle (Green Potion)

**Comment by BlueViper85** [comment]
You've got a tough one, but it is beatable.  You will need the following, which I've verified are all accessible (anything more than this is better, if you can swing it)

-Titan's Mitts
-Magic Mirror
-Ocarina/Flute (Activated)
-As many hearts, health potions (red/blue), or fairies as you can get
-Maybe a bit of patience

1. Fly to number 6 (The desert)
1. Pickup the rock on the right to warp to the dark world
1. Walk to the north-eastern corner of the swamp
1. Use the mirror to warp to Light World (you can use the mirror as a bunny still)
1. Pick up the rock
1. Enter the cave
1. Pick up the moon pearl

Since you can't beat the dark world dungeons your health will probably be rather low, and you can't swim or slash your sword, so it's probably going to be very easy to die while walking around the swamp of evil, particularly if the bird starts following you.  Shouldn't be too much of a hassle.

Looking at the rest of the item placement, I don't see any soft locks, so once you get the moon pearl this should be be beatable.  I'm closing this issues; however, if you have any additional questions or concerns you will still be able to add comments and we can provide assistance if needed.

Hope you continue to enjoy the randomizer, and please let us know if you come across any more issues!
