### ISSUE TITLE
Keys being eaten

### ISSUE THREAD

**Issue by Dessyreqt** [Dessyreqt/alttprandomizer#211]
Submitter: Gustav
Hello,
First of all, thank you for this wonderful program, I'm having a blast with it. However, as I was playing through the Desert Palace I went and faced the boss while having a key in my inventory, figuring it'd stay with me after I beat it so I could claim whatever was behind that last door, but when I went back in there was no key and it hadn't respawned anywhere within the dungeon, forcing me to revert my save and redo the dungeon to find what I was missing.

Thank you for your time
Gustav

**Comment by BlueViper85** [comment]
Validating this issue with v6

**Comment by BlueViper85** [comment]
-Generated a ROM with seed C3625279
-Gathered the necessary equipment to enter and complete Desert Palace.
-Entered the dungeon
-Grabbed the bonk key
-Grabbed the big key (in the map chest). 
-Left the first half of the dungeon and entered the second (with one key still on-hand)
-Grabbed the first pot key and went through the first locked door. Still had one key after
-Continued until the tall room and grabbed the pot key there and unlocked the second door.  Still had one key after.
-Continued to the third pot key, grabbed it, and unlocked the third (and final) key door.  Still had one key after
-Entered Lanmolas' room and beat the dungeon and obtained the pendant.
-Re-entered the second half of the dungeon and still had one key
-Left and entered the first half again, still had one key
-Validated that this one key still worked on the only remaining locked door, and it did.

No contact information was provided for the submitter to try to obtain additional information.  Without a video recording seeing this in action, I'm going to have to chalk this up to user error.  It is very easy to dash straight through two of the rooms in the second half without stopping to grab the key from either pot.  I am closing this issue, but it can be reopened if necessary.

Gustav, if you see this and have any additional information you are welcome to create a GitHub account and you'll be able to comment on this issue with that information. Two question I'd have are 1. What seed was this?  2. Have you noticed this any other times, or were you able to recreate it more than once after loading your previous save?

Hope you continue to enjoy randomizer, and please let us know if you run into any more trouble!
