### ISSUE TITLE
(Bug) C3375388 Dark Palace not solveable / Unable to get the Bow

### ISSUE THREAD

**Issue by PurpleCat0917** [Dessyreqt/alttprandomizer#214]
The Bow is placed about halfway through the first dark world dungeon. Sadly you can not pass the first locked door right at the dungeon start (middle door), because the only chest you can reach without the bow is from the start down the left stairs and it contains the map (Shooter Room). Right way is blocked by an enemy you can only kill with the bow.

Otherwise great job on the randomizer. Had some really fun and challenging seeds so far.  

 
A Link to the Past Randomizer Log
---------------------------------
Version: 6
Creation Date: 25.11.2016 19:13:05
Seed: C3375388

Dark Palace
-----------
[dungeon-D1-1F] Dark Palace - big chest...................................................1 Rupee
[dungeon-D1-1F] Dark Palace - big key room................................................Key
[dungeon-D1-1F] Dark Palace - compass room................................................20 Rupees
[dungeon-D1-1F] Dark Palace - jump room [left chest]......................................Key
[dungeon-D1-1F] Dark Palace - jump room [right chest].....................................Key
[dungeon-D1-1F] Dark Palace - maze room [bottom chest]....................................Key
[dungeon-D1-1F] Dark Palace - maze room [top chest].......................................50 Rupees
[dungeon-D1-1F] Dark Palace - spike statue room...........................................Big Key
[dungeon-D1-1F] Dark Palace - statue push room............................................Key
[dungeon-D1-B1] Dark Palace - room leading to Helmasaur [left chest]......................Compass
[dungeon-D1-B1] Dark Palace - room leading to Helmasaur [right chest].....................Bow
[dungeon-D1-B1] Dark Palace - shooter room................................................Map
[dungeon-D1-B1] Dark Palace - turtle stalfos room.........................................Key

**Comment by BlueViper85** [comment]
Thanks for the feedback!  This is a known issue with the logic for this dungeon in V6 (see issue #123) This will be resolved with the v7 update once it is completed.
