### ISSUE TITLE
Seed C7058044

### ISSUE THREAD

**Issue by ericvenneker** [Dessyreqt/alttprandomizer#215]
I believe seed C7058044 cannot be finished.

The hookshot and cane of somaria are both in cave 56, and you need the hookshot to go from one platform to the other. I have tried damage boosting with bombs and running into a skull, but with both I could not reach the other platforms.

If I had the cane than I could at least finish the game (specifically turtle rock), but I think it cannot be reached without the hookshot. 

Also the hookshot is necessary for to get the bombos medallion (bumber cave) which is needed for the misery mire dungeon.

Is this seed really unbeatable? What am I missing, any recommendations?

**Comment by BlueViper85** [comment]
I'm unable to generate the seed or log (and won't be able to for a while) so I don't know which chest the Hookshot is in in this cave.  If it's in the lower chest then you can access it.

When you enter the cave, dash into the left side of the first pot you see to bonk across the gap. Then dash into the bottom of the bottom pot on this platform to reach the bottom chest.

After you "bonk" across a gap like that, it helps to hold the direction your moving on the D Pad to keep from falling in the hole if you land near the edge. So, for example, for the first gap while you are in the air moving towards the platform on the left, you want to hold left until you've successfully landed and move a little on the platform.

This can take a little practice but isn't hard to master at all.

This is the only chest you can access without the hookshot.  If the hookshot is not in that chest then there may be a logic issue (either my own or possibly with the randomizer).

Hope this helps!

**Comment by ericvenneker** [comment]
You are absolutely right...grmbl... just me being stupid. I got the hookshot now so it should be alright. Thanks for the fast response!

**Comment by BlueViper85** [comment]
Glad to hear it! Good luck with the rest, and let us know if you have any more trouble!

**Comment by ericvenneker** [comment]
Thanks. This is a great project, I have viewed several youtubers having a mental break-down because of the randomization. Extremely entertaining.

This project keeps ALTTP alive and fresh, I hope that big N leaves you alone!
