### ISSUE TITLE
[v6] Light World Dungeon Pendants did not get saved

### ISSUE THREAD

**Issue by Dessyreqt** [Dessyreqt/alttprandomizer#216]
Submitter: Alckor
Seed : C9867999
Emulator : Snes9X
Lttp Randomizer Version : 6

I cannot get the master sword even if I have completed the 3 light world dungeons.

Path since the start of the game : 
Escape
Go to Village to Collect some stuff 
Eastern Palace 
Go to desert palace, realize that i cannot finish the dungeon without the boots
Collect some more stuff around flippers guy, death mountain.
Tower of Hera (found pearl and mirror on the way there) 
(NO DEATH OR S&Q until this point)
I go back through to the dark world through the warp just below tower of hera
Go to Blue Cane Cave (Die => Save and chose to appear at old man)
Go back to blue cane cave and die again. (Die => Save and chose to appear at old man)
Got to the blue cane chest this time, S+Q since I couldnt leave without dying.
At this point I go to thieves town to collect a bunch of stuff and I end up finding the boots by the pyramid on my way out.
I go finish Desert Palace, I should now have 3 pendants
I go to collect the master sword, but it does not work. I then realize that only the blue pendant is showing up as collected in the Item Menu.

If you need my save to troubleshoot you can ask via email.

**Comment by BlueViper85** [comment]
While not listed, it sounds to me like you visited a great fairy somewhere for healing. There is a known bug where that might make the game more or less forget which pendants you had the time. So if you have blue you probably did it before getting that pendant and after getting the other two.

The good news is that you can go back through the dungeons quickly and get back to the boss room and get the pendant back. You won't have to fight the bosses again.

No contact info provided so I'm closing this issue now. It can be reopened if necessary.

**Comment by Alckor** [comment]
Yep definitely visited a great fairy. I could not find the bug in the issues section. Is there any other place where I can view the list of known bugs so I don't fill useless reports? 

Thanks for the quick reply!

**Comment by BlueViper85** [comment]
There really isn't a place to see the list of bugs except to search the issues page. Issues are kept open until they have been solved for the following update. So it may show up in the list of closed issues instead, but the search does let you check that.

But right now there aren't many known bugs:

-Great Fairies remove pendants
-Palace of Darkness has an issue where the keys can be placed in a way that if you open the basement door you might lock yourself out of a room with chests.
-Palace of Darkness doesn't properly take into account that you need the bow to get past the Goriyas (mimics) so if the bow is placed deeper in the dungeon and the first chest you can access doesn't have a key you can't access the bow. In rare cases this can prevent accessing the bow of an item required to get the bow is placed in the dungeon as well.
-Minor graphical issues (rupees falling at the two tablet locations are cut in half, 1/4 magic text distorts when you die)
-Magic Cape isn't affected by 1/4 magic

These are fixed for the next version which is still being worked on.

Good luck with the rest of your randomizer and let us know if you have any more issues!
