### ISSUE TITLE
[v6] Seed C3090978

### ISSUE THREAD

**Issue by Dessyreqt** [Dessyreqt/alttprandomizer#217]
Submitter: Scott
Email: syarmel90@yahoo.com
[v6] I'm playing Seed C3090978 

This is an excellent rom and a great game I'm having a wonderful time. That being said. I have completed in full all dungeons up to Misery Mire and to my knowledge have opened all available chests in both the light and dark worlds, but I have never found the Cane of Somaria, which is needed to finish Misery Mire and then enter Turtle Rock.  Any idea where this should spawn? I could only think it would be in Turtle rock or ganon's tower at this point.

**Comment by ChristosOwen** [comment]
I just checked and the Cane of Somaria is obtainable. I think you simply missed a chest when exploring sadly. Try looking in Swamp Palace again :)
