### ISSUE TITLE
Fix Mothula sword damage bug

### ISSUE THREAD

**Issue by MindWanderer** [Dessyreqt/alttprandomizer#220]
The original version of this game includes a bug in which Mothula takes no damage from the level 4 (gold) sword, or from spin attacks from the level 3 sword.  Since it's otherwise very reasonable in the randomizer to get the gold sword early, this can easily result in a very frustrating situation for those who are unaware of this bug (or forget), especially if they're used to the GBA port (in which the bug was fixed).

Of course, if feature #201 is implemented, this fix would become much less important (though novice randomizer players may still encounter it--amazing how many just don't see the "Y" indicator on the flute/shovel).

**Comment by BlueViper85** [comment]
The issues with gold sword on Mothula are well known and this will be fixed with the next update to randomizer (v7). The randomizer will notify you when the update is available (no ETA right now)

Thanks for the report, please let us know if you have any other concerns!
