### ISSUE TITLE
[v6] Too few keys in Skull Woods?

### ISSUE THREAD

**Issue by Dessyreqt** [Dessyreqt/alttprandomizer#221]
Submitter: Phil
[v6]

I am in seed C0299893. As far as I can tell because I have opened the three locked doors in the first part of the dungeon I have no keys to open the first locked door in the second part of the dungeon. I have killed every enemy and lifted every pot and there are only three keys in chests according to the spoiler log. Is it possible for a key from one dungeon to be in a chest in another or am I S.O.L?

**Comment by BlueViper85** [comment]
The last room of the first half (right before going outside to go to the second half) has a key under a pot (top-left). 

If you got that one you very likely missed a chest.

Closing due to lack of contact info)
