### ISSUE TITLE
C0537684

### ISSUE THREAD

**Issue by Dessyreqt** [Dessyreqt/alttprandomizer#223]
Submitter: Eivind Sagli
Email: sagerz91@gmail.com
It seems i am now stuck. i dont have bow so i cant get to bosses in eastern and oasis temple, and i dont have lamp or fire rod to get to last chest in hera temple to get the orb for staying human in the darkworld. I have now been everywhere i can in the lightworld, and in the darkworld i managed to openup some of the chest as a rabbit on death mountain, but it just would not do the same in misery mire. And now there is absolutely nothing left to be done. and that kind of sucks :S

**Comment by Radagast81** [comment]
As of the Spoilerlog it seems that the bow itself is in eastern palace and you don't need the bow to get to the chest. Just go to the right after the room with the cannon balls.
The rest of the seed seems to be quite straight forward...

**Comment by ChristosOwen** [comment]
As Radagast said, you missed the Bow when searching Eastern Palace. Bear in mind this is randomizer so the Moon Pearl isn't necessarily going to be in Hera (and is unlikely to be). 

Unfortunately this seed is not beatable but for different reasons to the ones you stated. Moon Pearl is at Lumberjack tree which requires beating Agahnim. Beating Agahinm requires an upgraded sword or the cape. Cape is at the pyramid, which requires either beating Agahnim or the Moon Pearl - which is not possible. This leaves getting either the Master Sword or Tempered Sword. Getting Master Sword requires all 3 pendants, which requires Lamp or Fire Rod to reach Lanmolas' (and Hera in this case, when the Big Key is in the basement). Fire Rod is in Swamp Palace, which requires Moon Pearl. Lamp is Dark World Death Mountain, which requires Moon Pearl. So Master Sword is not obtainable. Tempered Sword also requires Moon Pearl and is not accessible.

Thus it is not possible to get the Moon Pearl. This is a known issue with faulty logic relating to the Pyramid function and is fixed for the upcoming v7 release. Sorry! :)

**Comment by BlueViper85** [comment]
Sent Chris' comment to Eivind via the provided email (with appropriate credit to chris) to ensure it was seen by the submitter.
