### ISSUE TITLE
Possible bug: able to collect red boomerang twice

### ISSUE THREAD

**Issue by kaezen** [Dessyreqt/alttprandomizer#225]
seed: C9618341
I'm not a huge speedrunner, but tried this out to prank one of my friends (calls himself alttp 'master') and it was a lot of fun. But I noticed something odd. he was able to upgrade the normal boomerang to the red one at the fairy fountain, and then the magic boomerang showed up in a chest in ganon's tower later.

If this is intended, i'm a little confused, but either way, just wanted to bring it to your attention

Was a lot of fun to run through, thanks for the hard work.

**Comment by BlueViper85** [comment]
This is working as intended. The magic boomerang is meant to be available in a chest but the fairy remains untouched (for now) but may be added in a future release.

**Comment by kaezen** [comment]
long as this is intended, just wanted to report in case.

Thanks a lot for all the hard work.
