### ISSUE TITLE
Bug Report: unable to collect master sword

### ISSUE THREAD

**Issue by kaezen** [Dessyreqt/alttprandomizer#226]
seed: C9618341
My friend collected all 3 light world pendants, 1 and 3 first, then 2 later, when he collected the 2nd one, the start screen said he didn't have any of them, and he was unable to pick up the master sword. He was still able to finish the game, but it was kind of annoying (for him, i thought it was funny)

Still was a lot of fun to play through, thanks a lot for making this!

**Comment by Radagast81** [comment]
I had the same issues with the pendants several times until i read it's a known bug when you visit a fairy. In this case you are losing all of them and have to recapture them by visiting the boss rooms again (without killing the bosses).
It should be fixed with v7 as dessyreqt said...

**Comment by BlueViper85** [comment]
As radagast said, this is a known issue with visiting great fairies which cause the pendants that you have when you visit to be removed. Just go back to the respective boss rooms to pick up the pendant again without fighting the boss again.

The fix for this will come with the release of v7.
