### ISSUE TITLE
I am stuck C5873585

### ISSUE THREAD

**Issue by Jempa124** [Dessyreqt/alttprandomizer#229]
seed: C5873585
according to the spoiler log, the Ether is found inside Misery Mire, so how would I enter if to get the item if I need the item to enter, or am I reading the log wrong.

**Comment by BlueViper85** [comment]
The randomizer randomizes what medallion is required to open Misery Mire and Turtle Rock so the ether medallion may not be required at all. I can't check the spoiler logs myself at the moment, so you have two options:

1. Walk to misery mire and see what medallion is required by checking the ground in front of the entrance.

2. The medallions for both dungeons are listed at the very bottom of the spoiler log.

Alternatively someone else can verify that Ether is not required for Misery Mire.

While this could be a bug, based on testing and past experience the likelihood is low. I'll close this issue for now; however, it can be commented on and re-opened if Ether is determined to be required to open Misery Mire.

**Comment by Jaylow7** [comment]
Confirmed this is beatable. The medallion required to enter Misery Mire is Quake, which is in the caves on the east side of light world death mountain.
