### ISSUE TITLE
Can get trapped in Skull Woods dungeon

### ISSUE THREAD

**Issue by bradleyfrye** [Dessyreqt/alttprandomizer#23]
In what I like to call "The Useless Room" of Skull Woods Dungeon, you can get trapped and forced to reset.  This is the room you can drop into via the southeastern-most hole in the woods, it has 4 bumpers, gibdos, wallmasters, and a chest in the middle.

The chest ordinarily has a small key in it, and I think this needs to be guaranteed, otherwise you will be trapped (since you can drop in, mirroring / using the wallmaster doesn't help.)  I got a map in seed C7337684, so I had to reset.

**Comment by Dessyreqt** [comment]
This was addressed in v4
