### ISSUE TITLE
Dark World: Palace of Darkness softlock.

### ISSUE THREAD

**Issue by Dessyreqt** [Dessyreqt/alttprandomizer#230]
Submitter: John Thompson
I was using seed (C4374701) when i hit the dark palace i had the hammer already. I went to the end forgetting to open the maze door witch leads to a chest with a key and the big chest. Because i went all the way to the boss there is no outher key in the temple expect for the key in the maze room witch is locked. This is a soft lock because the ice rod is in the big chest in this seed run. The main issue is when you have the hammer early you can use your key on the basement locked door after the hammer pegs. Thous you can no longer enter the maze room or access the big check or 2 chests in side.

Thanks

**Comment by BlueViper85** [comment]
This is a known issue with this dungeon per issue #123 .  This will be addressed in the next update of the Ranodmizer (v7).
