### ISSUE TITLE
[v6]Will not download

### ISSUE THREAD

**Issue by Dessyreqt** [Dessyreqt/alttprandomizer#232]
Submitter: Anonymous
[v6]I keep clicking create and it wont create the rom.

**Comment by BlueViper85** [comment]
When you click Create something should happen at least with the text box on the Randomizer application. If it failed an error of some kind would appear there, if it was successful it would say so.

The ROM is generated in the same folder that the exe is located.

No contact details exist so I am closing this issue. Should you find this and can provide any further detail you can add that as a comment here and this can be reopened if necessary.
