### ISSUE TITLE
Master Sword/Armor issue

### ISSUE THREAD

**Issue by m7backflip** [Dessyreqt/alttprandomizer#233]
This may be a silly issue to bring up, but I want to speak about it regardless.

The issue is this: should the randomizer allow you to acquire a Blue Mail before you pull out the Master Sword in the Lost Woods...then, once you do, your Blue Mail will return to the green tunic you were wearing beforehand.

Now, there are two solutions to this problem. The first one involves just ignoring the Master Sword; perhaps instead I should just try to acquire the Tempered Sword instead if I need a stronger sword. The second solution involves making it so that this doesn't happen.

Now, the reason I said this is silly is because this randomizer was created for speedrunners. I am not a speedrunner; I play this randomizer because it's fun and challenging. Since I'm not a speedrunner, so I don't know how one thinks, but I assume that a speedrunner wouldn't bother to return to the forest to pull out the Master Sword when they can just just get a much better sword much sooner (assuming that they generate a seed that gives them the Moon Pearl, Titan's Mitt, Ocarina and Hammer early on).

Thanks for reading my issue comment!

**Comment by BlueViper85** [comment]
Thanks for the feedback. To clarify, are you saying that you experienced having the blue mail turned back to green after pulling the master sword?

If so, do you recall the seed that you experienced this on? Can you also confirm what emulator you used?

**Comment by BlueViper85** [comment]
Tested with a V6 seed I had from a previous run where Light World dungeon items were easily accessible and so was the Blue Mail.  Obtained Blue Mail, beat the three dungeons to get the pendants and pulled the Master Sword and retained the blue mail the entire time.

While this doesn't mean this bug doesn't exist, it seems that this might be most likely either an emulator-specific problem and/or possibly an issue with the SRAM Trace options.  Can you confirm if you used that option and what emulator and version you are using?  The Seed would also be helpful and an SRM file if you can provide it.

**Comment by m7backflip** [comment]
Here's my seed: C9871545

Anyway: Whoops! Seems like I imagined things! Perhaps I WANTED a Red/Blue
Mail so badly, I imagined that I had one, and the even of pulling out the
sword made me realize that I wasn't wearing any of these armors. I just
checked my spoiler log to confirm this. I'm not known for my good memory,
or my patience. That's why I didn't notice what was right in front of me.
Sorry for the alarm!

P.S. Do you know of any seed(s) where the following items are literally in
6 of the first chests you can access by the beginning of the game (the
items in question are the Magic Mirror, Mirror Shield, Moon Pearl, Ocarina,
Titan's Mitt, whichever medallion is required to open Misery Mire, and the
Fire Rod. For a 7th chest, the Hookshot would be nice). All of these are OP
items to have on early in the game,but that's my point. I like to get as OP
as I can early on in RPG games. It's just a habit I have. If you don't know
of any such seeds, that's fine. Maybe I can try to generate one myself.

Unless...maybe you have/are planning to make a program which allows you
decide what's in each che-- no, never mind. That'd ruin the surprise, which
is the key aspect of a randomizer.

**Comment by BlueViper85** [comment]
Thanks for confirming!

As for your question, I don't know if any seeds with specific items available in the chests you asked about. However, there are several resources that may be of use to you:

1. There is a google sheet with several seeds that people suggest for whatever reason. Some hard, some easy, some challenging. You can find it here: https://docs.google.com/spreadsheets/d/1HqX6S9XDw4BswiDcznx0b8xWedHRT6qmRdpteZ9Qsi0/edit#gid=0

2.  There is an application called the Plandomizer (Planned Randomizer) that allows you to build your own seeds. Some customs ones were added (with download links) to the sheet linked above. This can be downloaded here: https://zarby89.github.io/ZeldaHud/Plandomizer.rar

3.  For discussion on ALttP speed running and/or the Randomizer you can join our discord at https://discordapp.com/invite/3Bsfnwk look for the #randomizer channel to discuss the Randomizer and plandomizer.

I'll close this issue. If you have any questions you can still comment. Or (of course) you can report any new issues if any come up!

**Comment by m7backflip** [comment]
These tools seem like what I may be looking for. I'll try them out.

But anyway, thanks for responding to me!
