### ISSUE TITLE
Unwinnable seed: Hammer Unreachable

### ISSUE THREAD

**Issue by wadw** [Dessyreqt/alttprandomizer#234]
Seed: C0728215

The Hammer is located where you'd normally get the Bombos Medallion. This makes it impossible to progress..

**Comment by BlueViper85** [comment]
I can't pull up the spoiler log at the moment, but if you have the cape or master sword you probably have the moon pearl, book of mudora, mirror, and hook shot (or at least access to them). Assuming those are accurate, you can beat agahnim's tower (the cape willer you bypass the electric barrier) and warp to the dark world pyramid. From the pyramid walk right then up and follow the path until you see a small break in the wall next the river. Use the hook shot here to go across. From there you can walk (the admittedly long way) to get to where you would mirror to get the Bombos medallion.

I'll check the spoiler log later to confirm my thinking but figured I'd post this now in case that's all accurate. If it's not there may be a logic issue we need to look at further.  I'll post a new comment after reviewing later unless you've been able to progress before then.

**Comment by wadw** [comment]
Yeah it holds up. Thanks! I'm there without the Master Sword(out of necessity), but I got there.  However, I need the sword to get the medallion...

**Comment by BlueViper85** [comment]
If you have titan's mitts (or access to them) you can get the tempered sword. Just need to get that first. It may be deep in a dungeon (maybe not as well) so just keep in mind that the fighter sword will be a little more difficult to use in the DW.

**Comment by KatDevsGames** [comment]
Also bear in mind that, aside from Blind, dark world bosses will not take damage from FS slashes, only spins.

On December 17, 2016 10:55:59 PM EST, BlueViper85 <notifications@github.com> wrote:
>If you have titan's mitts (or access to them) you can get the tempered
>sword. Just need to get that first. It may be deep in a dungeon (maybe
>not as well) so just keep in mind that the fighter sword will be a
>little more difficult to use in the DW. 
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/Dessyreqt/alttprandomizer/issues/234#issuecomment-267801957

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by wadw** [comment]
Right. Knew that but the reminder helps! Only, I am in need of either the Lamp or Fire Rod to finish the pendant quests. It was tedious but I now have the lamp and am confident that I can now progress. This is proving to be a really fun challenge! Thanks for the tip about the barrier.
