### ISSUE TITLE
I can't join the Discord channel anymore!

### ISSUE THREAD

**Issue by Nicholas-Steel** [Dessyreqt/alttprandomizer#238]
My bookmark for the Discord channel no longer works after I changed from 32bit to 64bit Firefox. I assume the original invite set a Cookie or some such the first time I used it and that was what was letting the URL work. I've got a registered Discord account now, Nicholas Steel.

**Comment by BlueViper85** [comment]
Here's the invite link again: https://discordapp.com/invite/3Bsfnwk

**Comment by Nicholas-Steel** [comment]
Awesome, thanks.
