### ISSUE TITLE
C3725411 (test seed): Hera big key inaccessible

### ISSUE THREAD

**Issue by MichaelViewer** [Dessyreqt/alttprandomizer#240]
Big key in the Tower of Hera was Moldorm's Boss Heart drop. The hookshot was in the big chest and therefore also impossible to attain, which stopped all progress.

More big key issues from the spoiler log created with Plandomizer: Turtle Rock big key in the big chest. Ganon's Tower big key in the chest before Moldorm2.

**Comment by Dessyreqt** [comment]
Fixed
