### ISSUE TITLE
C9129417 (test seed)

### ISSUE THREAD

**Issue by Myramong** [Dessyreqt/alttprandomizer#241]
- Armos had the big key
- Helmasaur had a small key
- Tower of Hera big key was in the upstairs small chest
- Vitreous had the big key (rip run)
- Bombos, Ether, Magic bat aren't randomized (new addresses below)
- There are 0 boss hearts, 11 sanctuary hearts (that may be intentional, I'm unsure)
- Crystals, Pendants, and Swords were not randomized.
- My app is telling me there are 25 small keys in randomized locations, v6 had 26 small keys.  Was there one removed?

0x180015 is the new address for Magic bat
0x180016 is the new address for Ether
0x180017 is the new address for Bombos

**Comment by Dessyreqt** [comment]
> Armos had the big key

Fixed
> Helmasaur had a small key

Not sure if this actually causes problems, I'd like Christos to weigh in on this.
> Tower of Hera big key was in the upstairs small chest

Fixed
> Vitreous had the big key (rip run)

Fixed
> Bombos, Ether, Magic bat aren't randomized (new addresses below)

Fixed
> There are 0 boss hearts, 11 sanctuary hearts (that may be intentional, I'm unsure)

Fixed
> Crystals, Pendants, and Swords were not randomized.

Fixed
> My app is telling me there are 25 small keys in randomized locations, v6 had 26 small keys. Was there one removed?

Not so far as I noticed. Can you tell me which dungeon is short a key?

**Comment by Dessyreqt** [comment]
The missing key was in Ganon's Tower. Will keep open until we resolve the question of keys on bosses.

**Comment by ChristosOwen** [comment]
Small keys at bosses at the moment is a problem as dungeon logic doesn't take this into account. We do want to get to a point where they can have small keys (and big keys for some). I can write this today/tomorrow but it will mean some fiddling with the existing dungeon logic but shouldn't be too bad. Happy to do this, and also don't mind if you'd rather wait for v8 for this. Up to you! I'll probably think about it later today anyway so it'll be ready

**Comment by KatDevsGames** [comment]
V8 shouldn't be that far away once v7 is done and tbh I haven't even fully tested drops of dungeon items. We're so close to launch that I think permitting boss hearts to have dungeon items is unwise for v7 (though a good idea for v8).

**Comment by Dessyreqt** [comment]
This has been addressed
