### ISSUE TITLE
C0581401: (Test Seed)

### ISSUE THREAD

**Issue by djtifaheart** [Dessyreqt/alttprandomizer#242]
no boots (at Moldrom) found ~ ice rod in Lumber Jack's hut (which makes TR not doable) 
Swamp Palace's first chest was the compass so locked out of there too. (Seed became dead here)
No fire rod / lantern, locked out of Hera / Desert (and most of the Dark World dungeons)
Big Key was in the basement chest in Hera, which made getting to Moldrom not possible. (Lack of fire rod / lantern)

_Update_ Found the Lantern in the Dark World, swamp palace area, bomb the northeast wall where the hidden thief is. Second chest in there. 
Hera: Bottom basement chest is a heart piece, not the big key. Which makes getting the boots impossible now. 
PoD: No big key, either in the BK chest or as the boss drop. The blue rupees were also missing from the B1 room, where the two chests are.
Two Bombos were found.
Heart Containers are acting like the Sanctuary Heart and not the boss hearts. Refilling health after every pick up. 
Final Items: http://i.imgur.com/ekAxi8V.png

**Comment by Dessyreqt** [comment]
Closing this as all of these issues have either already been reported, are being actively worked on as part of v7 completion, or fixed.
