### ISSUE TITLE
 C1037234 (v7 test seed) - bug list

### ISSUE THREAD

**Issue by biohazardtx** [Dessyreqt/alttprandomizer#243]
Cannot find Moon Pearl anywhere.  According to the spoiler log generated from the plando it's not available anywhere

Based on the spoiler log

Flute is not available
Fire Rod is in GT
Thieves Town BK  is in the cell with Blind
PoD BK is the Boss Drop

Also bosses drop dungeon items (map and compass)... I thought that wasn't being implemented until v8, but thought I'd report it anyway.

-belmontjr

**Comment by Dessyreqt** [comment]
Fixed (logic is still being tweaked.)
