### ISSUE TITLE
Test v7 Seed C5044647 - Dark World Crystal Map

### ISSUE THREAD

**Issue by BlueViper85** [Dessyreqt/alttprandomizer#244]
The map in the dark world is showing incorrect Crystals. Notice that Crystals 1 and 6 each show in two different dungeons. Per the spoiler log Swamp palace should have Crystal 5, but shows 4 on the map.  Misery Mire is supposed to hold Crystal 4, and Dark Palace is supposed to hold Crystal 7.

I haven't beaten the dungeons yet, but will add a comment when I beat these dungeons to confirm what crystal I get from the respective bosses.

![image](https://cloud.githubusercontent.com/assets/12190332/21472876/0f0f2f06-cab3-11e6-8e78-e597210c30b7.png)

**Comment by BlueViper85** [comment]
Fire Rod is in Ganon's Tower and the Hammer is in Skull Woods (Specifically at Mothula's heart drop), making it nearly impossible to check the accuracy of any of the crystals in the specified dungeons.

**Comment by Dessyreqt** [comment]
Copy/paste error. Fixed.
