### ISSUE TITLE
Logic issues v7

### ISSUE THREAD

**Issue by MichaelViewer** [Dessyreqt/alttprandomizer#245]
Stuck due to Moon Pearl or Ether tablet or Lamp/Fire Rod:

[cave-012-1F] Death Mountain - wall of caves - left cave..................................Moon Pearl
>requires Hammer or Hookshot

[cave-073] cave northeast of swamp palace [bottom middle chest]...........................Hammer
>requires Moon Pearl

Ether.....................................................................................Hookshot
>requires Master Sword

Moldorm and Lanmolas both require fire (if I wanted to go and get MS), because
[dungeon-L3-1F] Tower of Hera - first floor...............................................Big Key

[dungeon-D5-B5] Ice Palace - b5 up staircase..............................................Lamp
>unavailable without Moon Pearl and any kind of fire

[cave-056] Dark World Death Mountain - cave under boulder [bottom left chest].............Fire Rod
>unavailable without Moon Pearl and Hookshot

[cave-071] Misery Mire west area [right chest]............................................Bombos
>unavailable without Moon Pearl

**Comment by Dessyreqt** [comment]
Let's leave this open as the "your logic sucks" issue.

**Comment by Dessyreqt** [comment]
From #248:

- Moon Pearl is at Ether Tablet (no upgraded sword to get it, which also leaves the dark world not doable)
- Lamp is in Misery Mire, Fire Rod is in the Dark World (making Desert Palace not beatable, therefore not being able to get the master sword). Did Hera and Eastern just fine.
- Mitts in Graveyard (needed for DW access)

**Comment by ChristosOwen** [comment]
From #246:

Quoting Blueviper: "Fire Rod is in Ganon's Tower, which in itself makes this seed unbeatable. Hammer is in Skull Woods, further adding to the inability to complete many dungeons."

**Comment by MichaelViewer** [comment]
Seed: C7474373
Turtle Rock Required Medallion............................................................Ether
[dungeon-D7-B2] Turtle Rock - Eye bridge room [bottom left chest].........................Ether

**Comment by Dessyreqt** [comment]
Fire Rod and Ether issues have been addressed. Please only add logic issues from roms listed as created AFTER 12/26/2016 5:18:18 PM

**Comment by Dessyreqt** [comment]
From Discord:
Turtle Rock can generate without a Key in the first three chests.

**Comment by Dessyreqt** [comment]
Turtle Rock key issue has been fixed. Closing this. Open new logic issues (for v7P3 only) in separate issues.
