### ISSUE TITLE
Test v7 Seed C5044647 - Fire Rod in Ganon's Tower

### ISSUE THREAD

**Issue by BlueViper85** [Dessyreqt/alttprandomizer#246]
Fire Rod is in Ganon's Tower, which in itself makes this seed unbeatable.  Hammer is in Skull Woods, further adding to the inability to complete many dungeons.

**Comment by ChristosOwen** [comment]
When pendants/crystals are randomized cross worlds, this could be a thing (if no skull/trock required)!! But yeah, a problem for now as don't think that's done yet
