### ISSUE TITLE
Phantom Lantern

### ISSUE THREAD

**Issue by djtifaheart** [Dessyreqt/alttprandomizer#247]
No lantern, light up the torch in the first room with the fire rod, but game acted like I had a lantern.
https://www.youtube.com/watch?v=VAfJONgRW80

Changed by Dessyreqt from:

> Crashed at Smiths:
https://www.youtube.com/watch?v=nfdyfaC2Npo

**Comment by BlueViper85** [comment]
From Myramong in Discord:

Myramong - Today at 4:27 PM
looks like that crash is because the vanilla master sword was placed there, instead of the modified master sword (item 0x50)

**Comment by MichaelViewer** [comment]
No crystal dropped after the Helmasaur King fight in this seed, resulting in a softlock.

**Comment by djtifaheart** [comment]
Two new issues:

No lantern, light up the torch in the first room with the fire rod, but game acted like I had a lantern. 
https://www.youtube.com/watch?v=VAfJONgRW80

No boss music during the fight AND the crystal dropped, but locked up after grabbing it. 
https://www.youtube.com/watch?v=4qL9nC-264U

Crystal Locations:
http://i.imgur.com/pv1w4px.jpg

**Comment by KatDevsGames** [comment]
Helma King is just an issue of the crystal tables being filled in weird by client, probably minor.

**Comment by KatDevsGames** [comment]
Also the music not playing is a table filling issue.

**Comment by KatDevsGames** [comment]
The lantern issue here has been known since v4. Fix is "pending" (I'm 
working on it, no ETA). I have no idea why it's not in the tracker already.

**Comment by Dessyreqt** [comment]
Let's keep this issue just for the lantern...

**Comment by ChristosOwen** [comment]
This is fixed in the live web version: http://vt.alttp.run/
