### ISSUE TITLE
Test Seed (V7: C2168980)

### ISSUE THREAD

**Issue by djtifaheart** [Dessyreqt/alttprandomizer#248]
- Moon Pearl is at Ether Tablet (no upgraded sword to get it, which also leaves the dark world not doable)
- Lamp is in Misery Mire, Fire Rod is in the Dark World (making Desert Palace not beatable, therefore not being able to get the master sword). Did Hera and Eastern just fine.
- Mitts in Graveyard (needed for DW access)

**Comment by Dessyreqt** [comment]
Merging into #245
