### ISSUE TITLE
V7 Test Seed C4642871 Hard Lock

### ISSUE THREAD

**Issue by BlueViper85** [Dessyreqt/alttprandomizer#249]
https://www.twitch.tv/crrool/v/109824457

Hard lock when getting the Crystal in Misery Mire.

**Comment by KatDevsGames** [comment]
Can someone please verify the below table is filled in:

; MIND THE SNES BYTE ORDER #$0006 == byte[]{06, 00}
;--------------------------------------------------------------------------------
org $02885E ; PC 0x1085E - Bank02.asm:1606 - (dw $0006, $005A, $0029, 
$0090, $00DE, $00A4, $00AC, $000D)
dw $0006 ; Crystal 2 Location
dw $005A ; Crystal 1 Location
dw $0029 ; Crystal 3 Location
dw $0090 ; Crystal 6 Location
dw $00DE ; Crystal 5 Location
dw $00A4 ; Crystal 7 Location
dw $00AC ; Crystal 4 Location ;AC
dw $000D ; Agahnim II Location ; 0D

;C8 = Armos Room
;33 = Lanmolas Room
;07 = Moldorm Room

;06 = Arrghus Room
;5A = Helmasaur Room
;29 = Mothula Room
;90 = Viterous Room
;DE = Kholdstare Room
;A4 = Trinexx Room
;AC = Blind Room
;0D = Agahnim 2 Room
;--------------------------------------------------------------------------------

**Comment by Dessyreqt** [comment]
Fixed
