### ISSUE TITLE
Test Seed (V7: C9952509)

### ISSUE THREAD

**Issue by djtifaheart** [Dessyreqt/alttprandomizer#250]
Seemed very, very promising at the end. Someone mentioned that we're a small key short now? Losing that extra small key came back to hurt badly in PoD, got locked out of the boss, thus not being able to finish the game. All I had left was PoD, TR.  Ganon's Tower and Ganon. 

Such a shame, had all items. Video below just to show what happened here.

https://www.youtube.com/watch?v=JhQwIpqREfU

**Comment by Dessyreqt** [comment]
The key missing was in Ganon's Tower. Likely Helmasaur had a key. This is probably a good argument for keeping the keys out of bosses' hands on Casual.

Closing.
