### ISSUE TITLE
V7 Test Seed Packs 

### ISSUE THREAD

**Issue by Hiei408** [Dessyreqt/alttprandomizer#252]
Apparently went through the v7 seed test packs and noticed that they have 25 keys instead of the normal 26 keys in the v6 seeds.

Just wanted to bring this up in case if not noted.

**Comment by Dessyreqt** [comment]
This has been fixed.

**Comment by Hiei408** [comment]
very nice quick work there Dessyreqt hope you had a Merry Christmas.
