### ISSUE TITLE
[v6] unwinable seed

### ISSUE THREAD

**Issue by Dessyreqt** [Dessyreqt/alttprandomizer#255]
Submitter: John
Email: starwar225@aol.com
[v6]

A Link to the Past Randomizer Log
---------------------------------
Version: 6
Creation Date: 12/26/2016 5:53:24 PM
Seed: C2613075

Generated Item Order
-------------------- 
[dungeon-D1-1F] Dark Palace - big key room................................................Flippers 
[dungeon-D1-B1] Dark Palace - room leading to Helmasaur [left chest]......................Bow 
[dungeon-D1-B1] Dark Palace - shooter room................................................Compass

 
Hey just wanted to let you know this was an unwinnable seed. The first chest you can get is the compass and all the other chests are blocked by a key door and red goriya.

**Comment by BlueViper85** [comment]
This is a known issue with V6, the logic will be updated with v7
