### ISSUE TITLE
V7 Test Seed C9294380 Unbeatable Turtle Rock

### ISSUE THREAD

**Issue by Hiei408** [Dessyreqt/alttprandomizer#257]
Turtle Rock can't progress without a key since the following rooms have these items
[dungeon-D7-1F] Turtle Rock - compass room................................................Piece of Heart
[dungeon-D7-1F] Turtle Rock - Map room [left chest].......................................100 Rupees
[dungeon-D7-1F] Turtle Rock - Map room [right chest]......................................Big Key

**Comment by Dessyreqt** [comment]
Closing as duplicate of #245
