### ISSUE TITLE
Hookshot randomized to a chest that requires it.

### ISSUE THREAD

**Issue by YoItsTrev** [Dessyreqt/alttprandomizer#259]
Seed C8954506 randomizes the hookshot to Darkworld [cave-056] Dark World Death Mountain - cave under boulder [bottom right chest], a chest that REQUIRES the hookshot to get. Perhaps add code to make sure the hookshot cannot be randomized to chests that would require it?

**Comment by BlueViper85** [comment]
The bottom right chest in this cave can be accessed by "bonking" across the first and second gaps. When you enter the cave, stand to the left of the first pot you see, and dash into it. You will bonk and fly over the gal to the platform. Then stand below the lowest pot on that platform (that you can) and dash into it to get to the platform with the chest. Get the hook shot from the chest and complete the rest of the cave.
