### ISSUE TITLE
Softlocked in Ganon's Tower.

### ISSUE THREAD

**Issue by Kilieni** [Dessyreqt/alttprandomizer#26]
Total casual here, but I attempted a randomizer on stream at twitch.tv/kilieni with seed C1528189. There were 2 keys in the compass room, but I opened too many other key doors and can't get there. 

Included in ZIP: Rom, Spoilers .txt file, and SNES9x Savestate.
[C1528189.zip](https://github.com/Dessyreqt/alttprandomizer/files/308377/C1528189.zip)

**Comment by Dessyreqt** [comment]
This should be addressed in v4
