### ISSUE TITLE
Impossible Titan Mitt

### ISSUE THREAD

**Issue by Dessyreqt** [Dessyreqt/alttprandomizer#260]
Submitter: Zammy
Email: skellyjack44@yahoo.com
In seed C3677703 the titan mitt spawns underneath the top right gravestone. The only way to get to it is to pick up the black rocks which is now impossible.

**Comment by BlueViper85** [comment]
Sent the following to the email address specified:

Hello!

I saw your issue for the ALttP Randomizer. You can use the dark world to access the area with that tombstone.

Walk there in the dark world, you can cut bushes to access that area, then use the mirror to switch to the light world. You have to stand in front of the tombstone and face left or right, hold A to start the dash and then while Link is kicking up dust you can press up to dash into the tombstone.

Good luck, and let us know if you have any more issues or questions!

You can access your issue and add any comments if necessary, via the link below:

https://github.com/Dessyreqt/alttprandomizer/issues/260

BlueViper85
