### ISSUE TITLE
[v7] Softlock Issue

### ISSUE THREAD

**Issue by Dessyreqt** [Dessyreqt/alttprandomizer#264]
Submitter: Ian Sullivan
[v7]

Seed C0331450

Magic Mirror spawned in place of Moldorm's heart container, Tower of Hera boss.  WIth the Magic Hammer spawning in the dark world, there is no possible way into the Tower of Hera.  Generated Item Order places the Magic Mirror at Step 4, after you've been collecting dark world items during Step 3.

**Comment by KatDevsGames** [comment]
Hookshot next to zelda, moon pearl at bottle vendor, titan's mitt at East DW, hammer at the chest game. There is nothing at all unsolvable about this seed and original reporter did not leave contact information.

Problem is user error. Closing.

**Comment by Nicholas-Steel** [comment]
Yes, the user can use the hookshot to get across the broken Death mountain bridge and use a cave to get access to the top of the mountain and Tower of Hera.
