### ISSUE TITLE
"Bunny opening chests" question (v7)

### ISSUE THREAD

**Issue by GB-CG** [Dessyreqt/alttprandomizer#265]
Not sure if this is intentional or if it's already been talked about, but while in the north west cave of the Swamp of Evil as a bunny, the 2 chests with the blocks do not open, unlike the chests at Death Mountain.

Is it a bug or do you think the bunny should allow to open any chest in the dark world?

(Seed C7672870 is now beaten with all items without any issues)

**Comment by BlueViper85** [comment]
No chests can be open as a bunny unless you use a glitch known as "Super Bunny." One way to activate that glitch is to fall down a hole as the bunny, which then allows you to swing your sword (though you don't see it), push blocks, open chests, etc...

This is the reason you'd be able to open the chests on death mountain (as long as you fell down one of the holes in the cave) but not the chests in the the Swamp of Evil (jumping down a ledge does not count)

This glitch exists in vanilla and is not specific to randomizer. The casual seeds will NOT require you to use this glitch to access any items. This glitch is also banned in general races (of course if you race with your friends you can decide how to handle it, but if joining an existing race with others you don't normally race with, know that this is considered banned), but of course it is absolutely fine for use on your own.

Good luck with future randomizations, and let us know if you run into anyboher problems or questions!

**Comment by GB-CG** [comment]
Fair enough, I must've overlooked this fact. I play it for personal use. Still, it's a little annoying though. Thank you anyway.

**Comment by KatDevsGames** [comment]
Technically, the "fix" here would be to prohibit the bunny from opening the death mountain chests. I don't think anyone wants that though.
