### ISSUE TITLE
C5532622 - Swamp Big Key / Hookshot Issue

### ISSUE THREAD

**Issue by BlueViper85** [Dessyreqt/alttprandomizer#267]
Hookshot is in the big chest, and the big key is after the big chest, requiring the hookshot.

Swamp Palace
------------
[dungeon-D2-1F] Swamp Palace - first room.................................................Key
[dungeon-D2-B1] Swamp Palace - big chest..................................................Hookshot
[dungeon-D2-B1] Swamp Palace - big key room...............................................300 Rupees
[dungeon-D2-B1] Swamp Palace - map room...................................................Piece of Heart
[dungeon-D2-B1] Swamp Palace - push 4 blocks room.........................................Compass
[dungeon-D2-B1] Swamp Palace - south of hookshot room.....................................50 Rupees
[dungeon-D2-B2] Swamp Palace - flooded room [left chest]..................................Red Boomerang
[dungeon-D2-B2] Swamp Palace - flooded room [right chest].................................Big Key
[dungeon-D2-B2] Swamp Palace - hidden waterfall door room.................................50 Rupees
Heart Container (Arrghus).................................................................Map

**Comment by ChristosOwen** [comment]
Logic looks correct so not sure what the issue is here actually. I guess something going slightly iffy with implementation but I can't help much here sorry!

**Comment by BlueViper85** [comment]
I thought the logic looked good when I reviewed it as well.  I don't know how much use it is, but I threw in a logger to track item placement as it goes through and places them, and noticed that the Big Key in Swamp Palace is placed immediately following the Hookshot.  I don't know how much use that is in finding it, but thought I'd at least throw it out there to help with figuring this out.

Hookshot was also the very first item to be placed in Swamp Palace at all.

If anyone cares, I've attached the output file

[GeneratedItemOrder - C5532622 .txt](https://github.com/Dessyreqt/alttprandomizer/files/680370/GeneratedItemOrder.-.C5532622.txt)

[Edit: So I just realized when comparing v6 and v7 source that v7 reworked how dungeon items are placed, and I don't think it's properly considering (at least in the case of the Fire Rod at moldorm) that you actually need the Big Key to get to Moldorm. So my theory being that it thinks you can get the fire rod and THEN go get the Big Key

I think this applies to the this issue as well.  It placed the hookshot first, so at that point the flooded room didn't have the big key.  After that, it placed the big key in the flooded room thinking you could access the Hookshot because it didn't realize the Big Key was needed to access the hookshot]

**Comment by BlueViper85** [comment]
Looking further at other issues where Moldorm had the Fire Rod I found there was a logic error in how those items are placed.  I went into this issue with this same logic issue in mind and I think I found a tolerable solution.

The BigChest in Swamp palace as the following code:

`CanEnterSwampPalace(have) 
                        && have.Contains(InventoryItemType.Hammer) 
                        && (have.Contains(InventoryItemType.Hookshot) 
                            && (!LocationHasItem("[dungeon-D2-B2] Swamp Palace - flooded room [left chest]",InventoryItemType.BigKey) 
                                && !LocationHasItem("[dungeon-D2-B2] Swamp Palace - flooded room [right chest]",InventoryItemType.BigKey)   
                                && !LocationHasItem("[dungeon-D2-B2] Swamp Palace - hidden waterfall door room",InventoryItemType.BigKey))),`

First it checks that you can enter Swamp Palace, which makes sense.  Then it checks that you have the hammer, which also makes sense.

Then it checks that EITHER You can access the hookshot OR explicitly that the big key is not in the last few chests.  But it only evaluates that if you CAN'T get the hookshot.  Changing this to a simple OR (instead of conditional OR) seems to fix this. You either have to have the hookshot OR those chests CAN NOT have the big key.   This way it still evaluates those.

I tested this with just a standard OR and it still placed the Big Key in the flooded room right chest, and it put the Hookshot in the room south of the Hookshot room instead of in the big chest.

Swamp Palace
------------
[dungeon-D2-1F] Swamp Palace - first room.................................................Key
[dungeon-D2-B1] Swamp Palace - big chest..................................................Mirror Shield
[dungeon-D2-B1] Swamp Palace - big key room...............................................100 Rupees
[dungeon-D2-B1] Swamp Palace - map room...................................................3 Bombs
[dungeon-D2-B1] Swamp Palace - push 4 blocks room.........................................Map
[dungeon-D2-B1] Swamp Palace - south of hookshot room.....................................Hookshot
[dungeon-D2-B2] Swamp Palace - flooded room [left chest]..................................Heart Container
[dungeon-D2-B2] Swamp Palace - flooded room [right chest].................................Big Key
[dungeon-D2-B2] Swamp Palace - hidden waterfall door room.................................3 Bombs
Heart Container (Arrghus).................................................................Compass


I've got this code built in with the other changes I've noted today and can provide (as a pull?)  But want to make sure someone else looks at this and doesn't see any concerns or problems.

**Comment by BlueViper85** [comment]
While the circumstances are different, this issue ultimately boils down to the Big Key not being placed when the logic considered its location (and didn't recheck when the big key was placed) which is the same root cause as #266

I am closing this issue as it will be fixed by the same long term fix as that issue and tracking in one place is much simpler and keeps things in better order.
