### ISSUE TITLE
SNES PowerPak (flashcart) Support Broken in v7

### ISSUE THREAD

**Issue by ghost** [Dessyreqt/alttprandomizer#268]
I been using V6 with my snes powerpak with no a single issue , but V7 keeps giving me an error 

no internal header found  I can screen shot it 
![untitled](https://cloud.githubusercontent.com/assets/24786223/21579256/30efe28c-cf7c-11e6-90da-94532ffe025b.png)

I will gladly use an emulator to play your game, I love it , but just wanted to let you know

**Comment by KatDevsGames** [comment]
This might be addressable if and only if we can find someone with the hardware in question to test some roms.

**Comment by Dessyreqt** [comment]
I have a PowerPak, so I will be able to test this.

**Comment by Smallhacker** [comment]
Just as a shot in the dark: does Randomizer repair the ROM checksum and its compliment?

**Comment by KatDevsGames** [comment]
No, nor does any other rom hack ever.

On January 19, 2017 1:38:47 AM EST, Smallhacker <notifications@github.com> wrote:
>Just as a shot in the dark: does Randomizer repair the ROM checksum and
>its compliment?
>
>-- 
>You are receiving this because you were assigned.
>Reply to this email directly or view it on GitHub:
>https://github.com/Dessyreqt/alttprandomizer/issues/268#issuecomment-273694036

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Dessyreqt** [comment]
Abyssonym's Beyond Chaos FF6 randomizer does this, but I doubt it has any effect on whether PowerPak can read it.

**Comment by ChristosOwen** [comment]
Hasn't been reproduced ever but many fixes have been made to the new version: http://vt.alttp.run/
