### ISSUE TITLE
[v7] Swords???

### ISSUE THREAD

**Issue by Dessyreqt** [Dessyreqt/alttprandomizer#269]
Submitter: Hunter
[v7]

Do the swords actually get randomized?  Or are the swords you get from the smithy, pedastal, and fairy just randomized?

**Comment by BlueViper85** [comment]
Each of the swords are randomized among themselves.  All four swords will be in every seed.  You will always get the Level 1 (Fighter) sword from your uncle.  The remaining three will be randomized among the smithy, pedestal and fairy.

No contact information provided, so I will go ahead and close this issue.
