### ISSUE TITLE
C2863125 - Turtle Rock key shortage

### ISSUE THREAD

**Issue by seegtease** [Dessyreqt/alttprandomizer#271]
I opened every chest, killed every enemy, but do not have enough keys to access the final area. According to the spoiler log, I've opened every chest leading to this door that is supposed to contain a key, but I don't remember if they all contained keys. I even opened the chests that normally require the mirror shield by just eating the damage, no luck. Unbeatable?

**Comment by BlueViper85** [comment]
Do you have any video recording of your play through Turtle Rock or can you provide a save state and/or SRM file from the emulator?

Labeled as "help wanted" until this can be confirmed.

**Comment by seegtease** [comment]
Yeah... couldn't get it to allow me to upload a zip file even though it says it supports it... so I put it on google. The state is right at the locked door.

https://drive.google.com/file/d/0B9frGErfeJx1UWVmSHlKVGZ1cVE/view?usp=sharing

**Comment by BlueViper85** [comment]
Loaded up your save and found your missing key.  There is any enemy you didn't kill.  If you'd like me to tell you exactly which one it is, I can do so but I figure I'll leave you to ask first in case you'd like to find it yourself.

**Comment by seegtease** [comment]
I'll figure it out. Thanks for looking it over. I don't know why I missed it, I've done several runs not even that long ago.

**Comment by BlueViper85** [comment]
No worries, good luck! I'll go ahead and close this issue for now.  You can still add comments if you'd like me to tell you exactly where and I'll get an e-mail notification.

Thanks for playing the Randomizer! Let us know if you run into any further issues or have any questions!
