### ISSUE TITLE
Increase Client/Spoiler Log Font Size 

### ISSUE THREAD

**Issue by Nicholas-Steel** [Dessyreqt/alttprandomizer#272]
It would be nice if the font could be made larger, like size 14 or 16.

**Comment by Nicholas-Steel** [comment]
If http://vt.alttp.run/randomizer is the successor to the client application than I will consider this resolved because the text size is a suitable size/can be adjusted via web browser zoom settings.

**Comment by KatDevsGames** [comment]
Technically the resolution is Closed/Won'tFix since the website has its own separate bugtracker. Your analysis would be correct though.
