### ISSUE TITLE
[v7] doesn't start

### ISSUE THREAD

**Issue by Dessyreqt** [Dessyreqt/alttprandomizer#273]
Submitter: Sotirios Papadopoulos
[v7] I downloaded version 7, but it doesn't start. I am using Windows 7 64bit Home Premium. Version 6 works though (excellent work by the way).

**Comment by BlueViper85** [comment]
The ALttP Randomizer is built on the .NET Framework v 4.5.2, which does NOT come included with Windows 7.  You can download the latest version of the .NET Framework (v4.6) from https://support.microsoft.com/en-us/kb/3045560

No e-mail or direct means of communication, so I am closing this issue.
