### ISSUE TITLE
C8976687 - Turtle Rock Lamp Missing from Logic

### ISSUE THREAD

**Issue by Dessyreqt** [Dessyreqt/alttprandomizer#274]
Submitter: hiei408
Seed # C8976687

In a casual seed lamp was located after a dark room:

Turtle Rock: [dungeon-D7-B2] Turtle Rock - Eye bridge room [top right chest]...........................Lamp

**Comment by ChristosOwen** [comment]
This one is nice and simple, simply need to add Lamp to those 4 chests and Trinexx. Forgot about the dark room initially hehe

**Comment by ChristosOwen** [comment]
For clarity, Lamp is to be added to these 5:

"[dungeon-D7-B2] Turtle Rock - Eye bridge room [top right chest]"
"[dungeon-D7-B2] Turtle Rock - Eye bridge room [top left chest]"
"[dungeon-D7-B2] Turtle Rock - Eye bridge room [bottom right chest]"
"[dungeon-D7-B2] Turtle Rock - Eye bridge room [bottom left chest]"
Trinexx

**Comment by BlueViper85** [comment]
The fix for this issue has been applied to the base code and will be available when the next version is released (no ETA).  Closing this issue since a fix has been applied.
