### ISSUE TITLE
Client Update: Clear Seed Numbers When Switching Between Mode Types

### ISSUE THREAD

**Issue by Nicholas-Steel** [Dessyreqt/alttprandomizer#275]
The Seed box should be cleared when changing modes so that the Create and Spoiler buttons will correctly create a result based on the newly selected mode without having to manually clear the Seed box first.

This new behavior should be more intuitive.

Alternatively have the Create/List Spoiler buttons automatically change the letter prefix and leave the numbers as is.

**Comment by BlueViper85** [comment]
For what it's worth, I would add to this that if a seed number is entered that doesn't match the mode, it would be good to be to recognize the difference and confirm what the user wants to happen.

While I don't personally use Glitched mode (at the moment) I can see a use case where someone opens it up for a race, had Glitched selected, and entered a C seed to generate.

**Comment by BlueViper85** [comment]
The base code has been updated to accommodate switching between Casual and Glitched and will be available when the next version is released (no ETA).  Closing this issue since a fix has been applied.
