### ISSUE TITLE
[v7] Vision issues in Dark Palace. Seed C6489158

### ISSUE THREAD

**Issue by Dessyreqt** [Dessyreqt/alttprandomizer#277]
Submitter: Andrew 
[v7]
Going through the Dark Palace dungeon. The maze room to get to the big chest is completely dark. You cannot see Link or a vision cone, making it impossible to navigate. The fire enemies and flame spurts from the dinosaur enemies are seen but that's all you can see in this room.

**Comment by BlueViper85** [comment]
You need the Lamp to see in the dark. Find the Lamp and return to see. The lamp, for the most part, will not be in any places that require you to navigate a dark room like that without the Lamp. There is a known hug where it can happen in certain instances, but that has been identified and will be fixed. 

No contact details, so I am closing this issue.
