### ISSUE TITLE
Remove Random Spoiler button

### ISSUE THREAD

**Issue by thejoshwolfe** [Dessyreqt/alttprandomizer#286]
The Random Spoiler button seems redundant with the List Spoiler button. The only difference is that the Random Spoiler button effectively clears the Seed textbox first. If there's a Random Spoiler button, why not a Random Rom button that's like Generate but also first clears the Seed textbox?

Another idea: don't write generated seeds to the Seed Textbox. The seed is still being output in the filename and the `output` text area. Is there a reason we put the seed in the Seed textbox? Is it to make it more convenient to regenerate the same seed again? It's a bit confusing to me that the same box is used for both input and output.

**Comment by BlueViper85** [comment]
Just providing some feedback of my own on this:

I find the Random Spoiler option a useful means of generating a seed for someone else (such as for the weekly race) without having to generate a file on my computer that I might have to find and open. As you said, the list spoiler button does negate the need for this I suppose, though. As long as I have a means of conveniently generating a log for a random seed number (i.e. letting the application generate it for me) without creating the ROM itself I don't have a strong of an opinion on how that's accomplished.

As for the Seed being entered into the text box, I find that quite convenient.  If I'm looking through a spoiler log the seed is right there so I don't have to lose my place and scroll up if I need it.  The seed being part of the file name is purely optional as well, so relying on that as a means of finding a seed if you lose it isn't as reliable.  It's also useful in the event that I didn't have "Create spoiler log" checked, and need to regenerate the same seed again.

**Comment by Nicholas-Steel** [comment]
The problem is that, as already mentioned, the List Spoiler button doesn't first clear the Seed box. So you can't click it over and over to look at a new Seed each time and find one with a configuration that you like. Instead you'd have to delete the contents of the seed box between each click of the List Spoiler button which is tedious.

The Random Spoiler button allows you to do this without the tediousness.

**Comment by thejoshwolfe** [comment]
It sounds like the current functionality provides features that people like, and I don't have a good alternative for those features if we delete the button.
