### ISSUE TITLE
Seed c9775635 Trinexx has lamp

### ISSUE THREAD

**Issue by thatguycore** [Dessyreqt/alttprandomizer#289]
Heart Container (Trinexx).................................................................Lamp

**Comment by BlueViper85** [comment]
CanDefeatTurtleRock is missing the Lamp which is technically (as far as Randomizer is concerned) required.

If LW dungeons are ever removed from the dark rooms lighting up without the Lamp it will also need to be added to CanDefeatEasternPalace

CanDefeatMiseryMire and CanDefeatDarkPalace already check for the Lamp, so it won't wind up at Helmasaur or Vitreous

**Comment by ChristosOwen** [comment]
This is already logged in #274 so going to close... because the sheer quantity of reports scares me :>
