### ISSUE TITLE
Randomize which enemies drop room keys

### ISSUE THREAD

**Issue by ghost** [Dessyreqt/alttprandomizer#299]
Might be fun to randomize which enemy in a room drops a key to proceed so specific rooms can't be memorized for exactly which enemy needs to be killed, bypassing others.

**Comment by BlueViper85** [comment]
This has been discussed in various mediums in the past. Ultimately this just wouldn't be that fun. You'd have to kill every enemy until you found a key, which hurts the fun, and would add time (potentially significantly at times) which would likely make it feel more like a chore than fun by the end. 

Among plenty of other changes planned for the future, there are changes coming that affect what items enemies might drop, without moving keys. This gives some potential utility to killing more enemies than necessary, without requiring it.

**Comment by ghost** [comment]
Fair enough. Thanks for the response!
