### ISSUE TITLE
Softlock in PoD with 3 Keys

### ISSUE THREAD

**Issue by JingerTV** [Dessyreqt/alttprandomizer#3]
Hi, i should let you know that there is a possible way to get stuck in Palace of Darkness with 3 keys before opening the room where you use the Bombjump for the big chest

Seed was: 0303724

https://www.twitch.tv/jingertv/v/69444475     | Video for the the route i was taking

had 3 keys opend the following Keydoors - 1. in the Basement after the Arrowstatue | 2. Before Big key Chest | 3. The first Keydoor in the dungeon in the middle pathway

**Comment by Dessyreqt** [comment]
I made Dark Palace a little more generous with its keys... looking at the route you took you would be able to complete the dungeon with the new generation.
