### ISSUE TITLE
Tower and randomizing Aga1?

### ISSUE THREAD

**Issue by churine** [Dessyreqt/alttprandomizer#300]
So right now it is very rare you need to do Hyrule Castle Tower.
I was thinking how in vanilla, you can glitch Agahnim 1 to actually drop Ether. Is there a way something like this could be used?
The easy thought is to make another of the LW bosses warp you instead while Agahnim drops items, but that'd probably be really hard to implement. (And likely unintuitive)

Another more practical thought is that, if shuffling bosses is ever a thing, simply have Agahnim 1 also switched. This would have the interesting effect that one other dungeon would be unmarked and just as potentially optional.

**Comment by ChristosOwen** [comment]
While getting a drop from Agahnim is possible I don't think it's something we should implement in Casual (or even Glitched). It's widely unknown.

I see where you're coming from that it's rarer to have to do Agahnim's Tower but that's not necessarily a bad thing. It's just down to the distribution of items really. I've had to do it at least a few times, and I've certainly had the option of doing it almost instantly right off the bat after finding cape+moon pearl. Do you risk investing the time, or should you keep searching and hope for mitts/hammer/gloves? I actually think it's fine how it is.

Randomizing which LW boss warps you to the DW is an interesting idea, although I'll have to think more about whether it would be a good idea to change a game mechanic like that. 

As for randomizing bosses, I think this would just be frustrating when you manage to find the items to get through a dungeon only to find you don't have the items to defeat the boss, for example. Not to mention difficulty with boss rooms, dungeon ID's and correctly assigning the pendant/crystal drops.

**Comment by Nicholas-Steel** [comment]
Seeing as most (all?) boss rooms lock you in with the boss you can end up being forced to die (or Save & Quit I guess, which originally counted as a death). if bosses are randomized.

**Comment by Dessyreqt** [comment]
I'm not in favor of boss randomization, but technically (at least for dark world bosses) the floor outside of the boss room could be switched to show which boss is in the boss room (except in Thieves' Town?)

Anyway, let's not do this, at least right now.
