### ISSUE TITLE
[v7] Lamp spawn in room only reachable through darkness

### ISSUE THREAD

**Issue by Dessyreqt** [Dessyreqt/alttprandomizer#301]
Submitter: Paul
[v7]
seed: C4925662
[dungeon-D7-B2] Turtle Rock - Eye bridge room [top left chest]............................Lamp

This location for the lamp is not reachable without passing through an area that requires the lamp to see. I used a cheat to illuminate the room so that I could get to the lamp. Rest of the seed was fine.

**Comment by ChristosOwen** [comment]
This is known and is already logged, so going to close. Thanks for alerting us though anyway!
