### ISSUE TITLE
Turtle Rock Wrong Medallion

### ISSUE THREAD

**Issue by Dessyreqt** [Dessyreqt/alttprandomizer#302]
Submitter: Turtle Rock Wrong Medallion
[v7]

Seed: C5921915
Spoiler lists Required Medallion - Turtle Rock as Either and Either is acquired in Ice Palace.
Either is in Ice Palace but Turtle Rock has Quake required.
Quake is found in Ganon's Tower, therefore cannot complete.

**Comment by BlueViper85** [comment]
I'll validate this later, without screenshots I suspect this may be a case of mistaken medallion graphics.

I checked the hex values in this seed's ROM file, and the Medallion for Turtle Rock is properly set to Ether. So this may just be a misunderstanding that the medallions used to open the dungeons are randomized too.  I'll still play test to confirm something else didn't happen.

**Comment by sporchia** [comment]
this feels like they misunderstood entrance requirement randomization, agreed

**Comment by miketrethewey** [comment]
```
Required Medallion - Misery Mire..........................................................Bombos
Required Medallion - Turtle Rock..........................................................Ether
```

**Comment by miketrethewey** [comment]
Misery Mire
![c5921915v7-mire-closed](https://cloud.githubusercontent.com/assets/2232440/21976066/df12582c-db84-11e6-9cd5-e1a112fd1eb8.png)
![c5921915v7-mire-open](https://cloud.githubusercontent.com/assets/2232440/21976067/df187f36-db84-11e6-82ed-17bbb3e3e823.png)

**Comment by miketrethewey** [comment]
Turtle Rock
![c5921915v7-trock-closed](https://cloud.githubusercontent.com/assets/2232440/21976207/9ca0c54a-db85-11e6-9fb3-afa265371a25.png)
![c5921915v7-trock-open](https://cloud.githubusercontent.com/assets/2232440/21976208/9ca1b112-db85-11e6-8591-8b934da6dcf9.png)

**Comment by BlueViper85** [comment]
@miketrethewey confirmed the medallions showed correctly and worked as expected, confirming there is no issue.

For the submitter, if you see this: Please be aware that in Randomizer the medallions used to open Misery Mire and Turtle Rock are randomized among the three. Check the medallion symbol in front of each dungeon to confirm which is needed (or check the spoiler log)
