### ISSUE TITLE
V7 Glitch Seed G7560294 (Complexity 10) - Moon Pearl at Catfish... impossible?!

### ISSUE THREAD

**Issue by nacitar** [Dessyreqt/alttprandomizer#303]
I know this is the glitch category, but I can't think of any possible way to get to the dark world area where the catfish circle is in and be able to activate the circle (can't throw items as bunny, can't figure out any fake-dark-world way to make it let me be there as normal link and not be bunny, ...).  
  
  
So, seriously.. Simply put, Moon Pearl at Catfish... how is that ever possible to retrieve?

I wish the docs said which glitches the player is expected to know in order to complete these seeds.

**Comment by BlueViper85** [comment]
I am not familiar enough with the glitches to comment too much on this in anyway, except to say that here is a document that can help identify which glitches are useful for Glitched Mode.

https://docs.google.com/document/d/1LRnLCyIIvNAAvIaXnYhiDxblIhIJgTlboMuSOvrp3P4

**Comment by ChristosOwen** [comment]
You can clip there from Death Mountain, the screen near Turtle Rock, almost the same as if we were clipping to Zora's Domain (e.g. what we do in All Dungeons). 

You need to YBA in the DW first to a location where you can convert super bunny to real Link (e.g. using Death Moutain's accessible portal, and then fluting to 7 and pulling the statue). Then you either YBA to 1 or DW DMA, and then clip to east DM (using the standard upper clip from All Dungeons, for example).

The doc is meant to be a helpful guide, not a walkthrough, although it is a WIP so hopefully it'll grow and become more useful over time. Superskuj's tutorial is also a useful resource. 

Hope this helps!

**Comment by nacitar** [comment]
![got_it](https://cloud.githubusercontent.com/assets/1252549/22054186/e2db3500-dd19-11e6-8280-0c5a877d153e.png)

That guide BlueViper linked, plus some other videos youtube using the terms I learned from that guide... and now I got it!  Thanks guys!  You should make that link prominent on the randomizer FAQ/Readme, it's great.
