### ISSUE TITLE
v4 Dark World Spawning

### ISSUE THREAD

**Issue by BlueViper85** [Dessyreqt/alttprandomizer#31]
A minor issue, but I've found that when I save and quit in the Dark World without having beaten Agahnim, I would respawn in light world (which is intended) however, when I died in Dark World and chose to continue I respawned at the Pyramid.

When I died, I was in the Cane of Byrna cave and selected the bottom "Do Not Save and Continue" option when I restarted in the Pyramid.

Video https://www.twitch.tv/blueviper85/v/76269805?t=55m47s

**Comment by darkmagician1184** [comment]
Had the same thing happen to me, I died in the hookshot cave near TRock (dark world) and spawned on the pyramid without mirror or aga death.  S+Q from the pyramid put me in light world

**Comment by Dessyreqt** [comment]
This is fixed in v5
