### ISSUE TITLE
Fortune Tellers Should Sell Hints

### ISSUE THREAD

**Issue by tim-burget** [Dessyreqt/alttprandomizer#310]
Would it be possible to make fortune tellers sell spoilers?

**Comment by ChristosOwen** [comment]
This is already something we're considering (and Sahasrahla telapathy tiles) to either give specific or generic hints. This won't be until a much later version, most likely v10 onwards. I'm going to close this as it's already on the drawing board though! :)

**Comment by tim-burget** [comment]
Cool!
