### ISSUE TITLE
[v7] Item(Lamp) placement softlock at turtle rock

### ISSUE THREAD

**Issue by Dessyreqt** [Dessyreqt/alttprandomizer#312]
Submitter: Anom
I ran into a softlock which made it impossible, sans some insane cheating, to beat the game. I was looking for the Lamp item to finish misery Mire, Dark Palace, and turtle rock, and has gotten through all of them up to those points, and after searching the world for three days I finally checked the spoilers, to find the lamp had been placed in one of the four chests of the eye bridge room. Seeing as that is past the only total darkness room in the game that is impossible to navigate at all without the lamp(the other two I can wade around in by being stupid careful and dashing properly), I couldn't actually beat the game.

Seed was "C0817650"

**Comment by ChristosOwen** [comment]
Hello, sorry you played a seed where this happened! It's an issue we're already aware of and will be fixed in the next update. This is already logged in Issue #274 so going to close this one and link your comment there. Hopefully this will be fixed soon!
