### ISSUE TITLE
Exploration Glitch Help

### ISSUE THREAD

**Issue by tim-burget** [Dessyreqt/alttprandomizer#314]
Could I please have a list of all places you can exit Exploration Glitch?

**Comment by BlueViper85** [comment]
There isn't a very effective way to list how you can exit Exploration Glitch.   There is an [EG Map](http://sr.nyo.fr/alttp/eg-map.png) that can show you how rooms are linked (note, stay away from the red-colored rooms).  From there you'd need to find places that let you jump back in bounds.

Playing on Emulator and just messing with EG and turning off the top layer is a good way to play with EG and learn where you are, where you can't can't move and where you might be able jump back in bounds (or jump into areas that might block you in)

Other things like resetting the console, and possibly saving and quitting after entering EG would allow you out, but are less helpful in advancing you anywhere.  There may be other methods to get back inbounds as well that I'm not aware of.

To bring that back around to randomizer: Keep in mind that the Glitched version of Randomizer does not take EG into account for the logic.  While you can certainly use EG on your own, the logic does not require using EG and generally speaking EG isn't meant to be used when racing (though individual race rules could vary)

**Comment by tim-burget** [comment]
Do you know which glitches the randomizer's logic account for (so I can
look them up)?

**Comment by BlueViper85** [comment]
[This document](https://docs.google.com/document/d/1LRnLCyIIvNAAvIaXnYhiDxblIhIJgTlboMuSOvrp3P4) is as close to what you're looking for as it gets.  This document is very much a work in progress, and not necessarily meant as a complete, detailed walkthrough more as a helpful guide. YouTube videos are a good resource for learning glitches, as are watching streams and asking questions.  On YouTube one of the best resources are found on superskuj's channel.
