### ISSUE TITLE
Seed: C3168662 I believe this one is unbeatable...

### ISSUE THREAD

**Issue by AvatarMew** [Dessyreqt/alttprandomizer#315]
I'm at Turtle rock, I have all the crystals and all the items but the ice rod. I've opened every chest but to the big door but the big key isn't in any of them so I am unable to beat this seed.

I think there should be a way for the randomizer to place the big key in a room that doesn't require the big key to access.

**Comment by Radagast81** [comment]
Hey Mew,
have you checked the spoiler log? You can access that by entering the seed number and then press the "List Spoiler"-button so you can see where all the items are.
I am not sure if I have the same version of the randomizer as you have, but on my version the big key is in the map room of turtle rock and therefore is accessible (so if it's a bug it seems like it's allready fixed).
But I think you should check the spoiler log in your version, as the locations of the items can be different...
Hope you can proceed in your game.

**Comment by AvatarMew** [comment]
I made the seed with V6.

[dungeon-D7-B1] Turtle Rock - big key room................................................Big Key
I'm confused...

**Comment by Radagast81** [comment]
Ah ok, then please enter the seed into the seed field and enable the checkbox "Create Spoiler Log" and then "Create Rom". By this way you can get the spoiler log retroactive and check the positioning.
The log will be in the same directory as the rom...

**Comment by BlueViper85** [comment]
Generated seed C3268662 with v6 and confirmed that the Ice Rod is accessible. I won't spoil where, but it is accessible.

Radagast confirmed it was accessible in another version (presumably v7) as well.

You can re-generate the seed with the "Create Spoiler Log" option in v6 and it will place a spoiler log in the same location as the ROM if you'd like to spoil the location for yourself.

**Comment by AvatarMew** [comment]
I'I made a typo... The seed is C3168662 

It said that the big key is in the compass room, it's not.

**Comment by BlueViper85** [comment]
Can you please attach a copy of your ROM? You can put it in a ZIP file and attach directly here if you need.

**Comment by BlueViper85** [comment]
If you are using an emulator a save state or SRM file would be useful as well.

**Comment by AvatarMew** [comment]
I'll do it when I'm home.

**Comment by AvatarMew** [comment]
[ALttP_Random_-_C3168662 save.zip](https://github.com/Dessyreqt/alttprandomizer/files/737092/ALttP_Random_-_C3168662.save.zip)
[ALttP_Random_-_C3168662.zip](https://github.com/Dessyreqt/alttprandomizer/files/737093/ALttP_Random_-_C3168662.zip)

There is the rom and the save file.


Note: I do not want to know where the ice rod is, I just want to know if this seed can be beaten.

**Comment by BlueViper85** [comment]
Thanks for the files information @AvatarMew !  So here's what I've been able to find...

1. This seed is actually a v7 seed (complexity level 6)
2. The Big Key is listed in the spoiler log that I've generated as being somewhere other than the Compass room (I won't say where, though you do have the spoiler log of course, but I can tell you as well, if you need)
3. I checked the chest where the spoiler log said the big key was and it had NOT been opened, and it DID have the big key.

I'm more than happy to elaborate on where the big key is if you need any further assistance, just ask.

I also double-checked the Ice Rod just to make sure it was accessible, which it was.

**Comment by AvatarMew** [comment]
Thank you. I have no idea how I missed a chest. I will look for the key.

Is really impossible to beat Trinexx without the ice rod?

**Comment by BlueViper85** [comment]
Glad to help. Some chests/locations can be easily missed, it happens!

As for Trinexx, yes. Without the Ice Rod you can't beat the fire head.
