### ISSUE TITLE
Soft lock Seed: C5802433

### ISSUE THREAD

**Issue by huwpascoe** [Dessyreqt/alttprandomizer#320]
Please can you confirm if this is unbeatable?

http://pastebin.com/vJpL8Xg8

To get lamp/fire rod you need either the pendant of courage or moon pearl:
```
Sahasrahla................................................................................Fire Rod
[dungeon-D6-B1] Misery Mire - big key.....................................................Lamp
```

To get the moon pearl/pendant you need lamp/fire rod
```
[dungeon-L3-1F] Tower of Hera - first floor...............................................Big Key
[dungeon-L3-4F] Tower of Hera - 4F [small chest]..........................................Moon Pearl
Pendant - Tower of Hera...................................................................Pendant of Courage (Green)
```

**Comment by BlueViper85** [comment]
Hello, and thanks for the report. Sorry you ran into this bug, but it is a known bug and a fix has been put in place and will be included in the next update.  Closing this issue as it is effectively a duplicate.
