### ISSUE TITLE
Could you compile this for mac?

### ISSUE THREAD

**Issue by nickretallack** [Dessyreqt/alttprandomizer#321]

**Comment by KatDevsGames** [comment]
The client actually works fine in the OSX version of wine. It COULD be built properly for OSX but that's probably more of a long-term goal unless someone wants to put together build scripts for it.

**Comment by thejoshwolfe** [comment]
The client also works fine in the Linux version of wine as well, fwiw.

**Comment by GB-CG** [comment]
I just use the Wine app via Winebottler. Works great.

**Comment by nickretallack** [comment]
True.  I installed wine using brew moments after filing this and it worked.

**Comment by Dessyreqt** [comment]
Seems like this is not an issue then.
