### ISSUE TITLE
[v7] anonymous Issue - quest performance issues

### ISSUE THREAD

**Issue by Dessyreqt** [Dessyreqt/alttprandomizer#322]
Submitter: elzo_d
[v7], seed: C2743844

I played through my first randomized game (it was amazing, by the way) and being confident that I got everything, fought Ganon. However, when the credits got to the quest performance log, it said I missed 1 chest and 2 other locations. Me missing a chest was correct (never knew about that block-move chest in the swamp palace) but I'm pretty sure I got everything else. Furthermore, it also said I missed 1 Y-item (but I have no clue what it thinks I'm missing) and 2 heart containers (even though I had 20 hearts when I fought Ganon). I checked that chest I missed and it only contained 10 arrows.

A second issue I ran into is that the leaves of the tree that you run into to (normally) get a heart container was all glitchy and made up of body parts. No clue how that happened.

Here's a zip file containing the rom, sram, spoiler log and a few screenshots: http://elzod.16mb.com/extern/Archief.zip

On a unrelated note, is it correct that you end up with 1 extra key at the end of Misery Mire and Ganon's tower?

**Comment by ChristosOwen** [comment]
We removed a key door in Misery Mire and Ganon's Tower (to prevent softlocks and allow better key distributions) so yes that is correct you have 1 small key leftover in each of those.

The Lumberjack HP tree is a known buggy issue which has been fixed but until Dessy pushes out v8 it remains a (harmless) bug; but thanks for reporting it nonetheless!

The stats lock after the first time you beat the game so anything you don't collect in your first attempt will remain missing. With that said, possible Y-items you could be missing I guess would be something which shares a slot with another item (Mushroom/Powder, Boomerang/Magic Boomerang, Shovel/Flute, Bottles x4, Bow/Silver Arrows). Perhaps if you turn in the Mushroom it's also removed from the stats - I'm not actually sure. Unsure why it thinks you're missing 2 heart containers if you had 20 hearts.

Overall I think the statistics are still a WIP and need some refinement, though.

**Comment by BlueViper85** [comment]
Stats issues are being tracked in #307. Chris answered everything else. Closing this issue.
