### ISSUE TITLE
Early access to Ganon's Tower

### ISSUE THREAD

**Issue by MindWanderer** [Dessyreqt/alttprandomizer#326]
Ganon's Tower is usually a boring and tedious part of randomizer runs.  You're not looking for major items anymore, just the Big Key and one extra small key in the basement somewhere, unless you're going for 100%, and even then there can be no required items and it's just a matter of going through the optimal route until you get them all.  And you have to have all required items before you can even enter.

What if Ganon's Tower didn't require the seven crystals to access?  Players would then have to be familiar with the various obstacles in it to know how far they could get and what chests they could reach when they don't have all major items.  You could still make it so that Ganon himself isn't accessible until you've collected all the crystals (although this might be harder to code--maybe use logic similar to what you did for the ocarina boy becoming a tree).  Then required items could be hidden in the tower and make for a very interesting challenge.

**Comment by KatDevsGames** [comment]
I'd like thoughts from Chris on doing this as part of the "no rain" open adventure mode that was discussed earlier.

If this idea were used as part of open mode, I could simply put a force field over the pyramid hole that would require the crystals to disarm.

On February 9, 2017 2:57:28 PM EST, MindWanderer <notifications@github.com> wrote:
>Ganon's Tower is usually a boring and tedious part of randomizer runs. 
>You're not looking for major items anymore, just the Big Key and one
>extra small key in the basement somewhere, unless you're going for
>100%, and even then there can be no required items and it's just a
>matter of going through the optimal route until you get them all.  And
>you have to have all required items before you can even enter.
>
>What if Ganon's Tower didn't require the seven crystals to access? 
>Players would then have to be familiar with the various obstacles in it
>to know how far they could get and what chests they could reach when
>they don't have all major items.  You could still make it so that Ganon
>himself isn't accessible until you've collected all the crystals
>(although this might be harder to code--maybe use logic similar to what
>you did for the ocarina boy becoming a tree).  Then required items
>could be hidden in the tower and make for a very interesting challenge.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/Dessyreqt/alttprandomizer/issues/326

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by ChristosOwen** [comment]
It's an interesting idea and one that has been mentioned and discussed previously. However I feel that having it available would increase the length of the randomizer considerably as it gives you a (very large) new place to search; and you're very likely to have to revisit multiple times due to the sheer number of chests there (26). You can rarely explore the entire first floor, let alone complete the dungeon, in one visit.

It's good in theory but not so much in practice. Ganon's Tower is already accessible in the Glitched version from the get-go and having to go there multiple times like I mentioned above is very common. 

It changes too much from the original IMO.

**Comment by Nicholas-Steel** [comment]
I was thinking, maybe when you get all 7 pendents you're rewarded with the Boss Key (or access to it) for Ganon's Tower? So a huge amount of Ganon's Tower is accessible early but not all of it (this idea is an alternative to the idea of force fielding the pyramid hole).
