### ISSUE TITLE
Bugged Seed: Swamp Palace Hookshot Problem

### ISSUE THREAD

**Issue by AndreTremblay** [Dessyreqt/alttprandomizer#327]
Hello,

I recently came across a seed where the hookshot is in the big chest of Swamp Palace, but the Big Key is in the flood room. 

As in the room you need the hookshot to get to.

[dungeon-D2-B1] Swamp Palace - big chest..................................................Hookshot
[dungeon-D2-B2] Swamp Palace - flooded room [right chest].................................Big Key

Seed # : C0278913

I've attached the spoiler log for your perusal. 

Thank you.

[ALttP_Random_-_.sfc.spoilers.txt](https://github.com/Dessyreqt/alttprandomizer/files/765733/ALttP_Random_-_.sfc.spoilers.txt)

**Comment by BlueViper85** [comment]
This is a known issue and has been fixed in the base code. The fix for this will be included with the next update to the randomizer (v8). There currently is no ETA on when this will be complete.

Thanks for the report, sorry you ran into this issue!  Let us know if you see anything else!
