### ISSUE TITLE
Non-random seed glitch - Missing heart piece

### ISSUE THREAD

**Issue by Loogaroo1** [Dessyreqt/alttprandomizer#332]
The cave south of Haunted Grove contained a bomb capacity upgrade instead of a heart piece. I've opened every chest not associated with a dungeon, and the heart piece was not replaced.

**Comment by ChristosOwen** [comment]
Could you provide the seed number?

**Comment by KatDevsGames** [comment]
It remains the responsibility of the generating client software to fill in all fields. Even on non-randomized seeds, the fields are officially undefined, not vanilla config.

**Comment by Loogaroo1** [comment]
It was the NORAND seed, the one that is made when you select "No Randomization" in the client.

**Comment by ChristosOwen** [comment]
Issues with these heart piece locations have been fixed in the live web version: http://vt.alttp.run/
