### ISSUE TITLE
Incorrect Sprite for Dead tree in North Hyrule after Agahnim defeat's

### ISSUE THREAD

**Issue by avenger339** [Dessyreqt/alttprandomizer#333]
Using Seed C8343613.

After defeating Agahnim, the tree that can be dashed into that reveals a hole (in this seed, the location for the hookshot) - The sprite is incorrect.

Please see attached image.

![zelda sprite](https://cloud.githubusercontent.com/assets/9437520/23335187/acdddda4-fb7d-11e6-9a9d-fc144a244a6a.png)

Edit: Generated using v7.

**Comment by ChristosOwen** [comment]
Thank you for letting us know, I've added this to our bug list and we'll get this fixed for the next release!

**Comment by KatDevsGames** [comment]
Remove from buglist. This was already fixed in trunk.
