### ISSUE TITLE
[v7] Unbeatable Seed or am I missing something?

### ISSUE THREAD

**Issue by Dessyreqt** [Dessyreqt/alttprandomizer#334]
Submitter: Parker
Email: Parker.syphus@gmail.com
[v7]

I have followed all steps on the spoiler list through step three.  I cannot complete step 4 however.  Here are the steps:

Step 4 - Items reachable after collecting all items from Step 3:
  [cave-009-1F] Death Mountain - wall of caves - right cave [top left middle chest].........Bottle (Fairy)
  [cave-012-1F] Death Mountain - wall of caves - left cave..................................Blue Mail
  [cave-073] cave northeast of swamp palace [top middle chest]..............................Magic Powder
  [dungeon-D3-B1] Skull Woods - big chest...................................................Pegasus Boots
  Crystal - Skull Woods.....................................................................Crystal 3 (Yellow/Brown)
  Crystal - Thieves' Town...................................................................Crystal 5 (Green/Red)
  Flute Boy.................................................................................Bombos
  Piece of Heart (Graveyard)................................................................Ether

I have gotten both the Bottle(Fairy) and Blue Mail but cannot access the swamp palace area or the skull woods since I have neither the Hammer or the Power Glove (they are both listed in step 5): 

Step 5 - Items reachable after collecting all items from Step 4:
  [cave-018] Graveyard - top right grave....................................................Titan's Mitt
  [dungeon-L2-B1] Desert Palace - big chest.................................................Hammer
  Pendant - Desert Palace...................................................................Pendant of Courage (Green)

I am veritably stuck in the upper right hand corner of the dark world and have no way to make it to other portions of the dark world besides the portal on top of death mountain (which is a dead end in and of itself).  Listed below are steps 1-3 to show you what I have.  Is this really unbeatable or did I miss something?

Step 1 - Items reachable from start:
  [cave-021] Kakariko well [bottom chest]...................................................Bottle
  [cave-022-B1] Thief's hut [top chest].....................................................Power Glove
  [cave-026] chicken house..................................................................Fire Rod
  [cave-035] Sahasrahla's Hut [center chest]................................................Shovel
  [cave-035] Sahasrahla's Hut [right chest].................................................Staff of Byrna
  [cave-044] Aginah's cave..................................................................Red Shield
  [cave-047] Dam............................................................................Bottle (Blue Potion)
  [cave-050] cave southwest of Lake Hylia [bottom left chest]...............................Moon Pearl
  [cave-050] cave southwest of Lake Hylia [bottom right chest]..............................Mushroom
  [dungeon-C-B1] Escape - first B1 room.....................................................Magic Mirror

Step 2 - Items reachable after collecting all items from Step 1:
  [dungeon-C-B1] Escape - final basement room [left chest]..................................Bow
  [dungeon-C-B1] Escape - final basement room [right chest].................................Cape
  [dungeon-L3-4F] Tower of Hera - big chest.................................................Book of Mudora
  Pendant - Tower of Hera...................................................................Pendant of Power (Blue)

Step 3 - Items reachable after collecting all items from Step 2:
  [dungeon-D1-1F] Dark Palace - spike statue room...........................................Ice Rod
  Catfish...................................................................................Flippers
  Pendant - Eastern Palace..................................................................Pendant of Wisdom (Red)
  Piece of Heart (Desert - west side).......................................................Hookshot

Seed is C0114628

Thanks!

**Comment by BlueViper85** [comment]
The end of Step 3 ends with the Hookshot. From the Pyramid, if you walk east one screen, then walk north, following the dirt path, you will each a spot with some bushes and and skull rocks. In this area you will see a small break in the wall next to the river.  Use the hookshot here to get across and you'll have access to most of the rest of the Dark World.

Sent this as an e-mail to the provided address to ensure it was seen.  I am closing this issue now, however, comments can still be added and this can be reopened if needed.
