### ISSUE TITLE
Code used for 1/4 magic, etc?

### ISSUE THREAD

**Issue by Fish-waffle64** [Dessyreqt/alttprandomizer#336]
Hi there, I tried to find a way to privately contact you so that I could not "spam" the issue thread, but I did not find a way. I apologize, but please read me out.

I've been messing with A Link to the Past myself and am very new at hex editing. As a result, I try to figure out where certain code goes to do things such as get 1/4 magic instead of 1/2 but fail. I found what to change but for the life of me not where it goes. I also request knowledge/help with changing the item select names; example Hookshot to G. Beam or similar. My main request is the magic thing; I would love to implement it... Please let me know.
You guys have done an excellent job at the randomizer; keep up the good work ^^
Thank you,
Fish <><

**Comment by KatDevsGames** [comment]
The complete source to the ROM changes can be found at [http://alttp.run/karkat/randomizer/working/](url). The code regarding quarter magic is spread about but most of the relevant information is in [http://alttp.run/karkat/randomizer/working/inventory.asm](url) and [http://alttp.run/karkat/randomizer/working/newitems.asm](url).

If you have any questions about the ROM changes specifically. Feel free to contact me (username Karkat) in the ALTTP SRL discord (https://discord.gg/h4QJ9GB).
