### ISSUE TITLE
SEED C9005290 - lantern placement

### ISSUE THREAD

**Issue by Dessyreqt** [Dessyreqt/alttprandomizer#339]
Submitter: Ulfang
Email: quentin.arnould@yahoo.fr
Lantern was placed after a room i'm used to do in dark despite no lantern ( because i never get it early :'( ).
The room is in TurtleRock, you have to navigate on a somaria platform in the dark to press a button to open the door. Lantern was in a treasure chest right after this where the eyes lazer you while you go towards the chest.

Not sure if it's intended, but i created the seed in casual difficulty and doing that room in the dark without the lantern, even though i'm getting good at it, is anything but easy : )

Have a good day!

PS: Great romhack!!

**Comment by BlueViper85** [comment]
This is a known issue and will be fixed in the next update.
