### ISSUE TITLE
Unreachable Hammer

### ISSUE THREAD

**Issue by biohazardtx** [Dessyreqt/alttprandomizer#34]
Version: 4
Creation Date: 7/9/2016 9:01:24 PM
Seed: C2084242

The Hammer is located in the Ice Palace in the Big Key Room.  You have to have the hammer to knock down the mole-post things to reach the pull tongue statue that opens the door to the big key room.  The treasure that's located in the room with the pull tongue statue also would require the hammer to access since the button to make it appear is behind the posts. 

Thanks again for making a great randomizer!

**Comment by darkmagician1184** [comment]
Seed: c6588851

another seed where hammer is unreachable.  in Swamp flooded room

**Comment by Dessyreqt** [comment]
These issues are addressed in v5
