### ISSUE TITLE
Softlock getting to sanctuary

### ISSUE THREAD

**Issue by Dessyreqt** [Dessyreqt/alttprandomizer#340]
Submitter: Adam
[v7]

Seed = C4471421

At the very beginning, I've got Zelda and I'm going through the sewers to get to sanctuary.  Chest gave bottle and not key.  No enemies have key.  I tried save and quitting, but no change.  Items given were red boomerang, two bottles, one with a bee in it.  I can't think where else to look for key.

**Comment by HonkiTonk** [comment]
Have you forgot one of the keys from a guard or a rat? Because i get every key i need.

**Comment by Jaylow7** [comment]
If I'm understanding correctly, the room with the door you can't get past has the key you need. It's held by one of the 3 rats in the room.

**Comment by BlueViper85** [comment]
No contact info and submitted via form. Sufficient answer provided if seen. Closing.
