### ISSUE TITLE
Cannot complete the quest.

### ISSUE THREAD

**Issue by Dessyreqt** [Dessyreqt/alttprandomizer#343]
Submitter: Branon Troy Bernatowicz
[v7] Hello, I am unable to complete my quest.  The shovel is located in the big chest of Skull Woods.  The Fire Rod is located at the digging game.  And the big key to unlock the big chest in Skull Woods is located at the chest of Part 2 of Skull Woods (the part where you have to use the fire rod to enter the next part of dungeon 3 in skull woods).

**Comment by HonkiTonk** [comment]
You can play the digging game without shovel, you only need to be Link.

**Comment by Jaylow7** [comment]
Correct. The only requirement for digging game is actually being Link (AKA have the Moon Pearl). 

You are temporarily given a shovel during digging game, replacing whatever item you have on the Y button.

**Comment by BlueViper85** [comment]
No contact info provided and submitted via the horn which provides no response to the submitter. Closing issue.
