### ISSUE TITLE
Open Source License?

### ISSUE THREAD

**Issue by CanadianJeff** [Dessyreqt/alttprandomizer#344]
What is this getting released under?

Apache License 2.0
BSD 3-Clause "New" or "Revised" license
BSD 2-Clause "Simplified" or "FreeBSD" license
GNU General Public License (GPL)
GNU Library or "Lesser" General Public License (LGPL)
MIT license
Mozilla Public License 2.0
Common Development and Distribution License
Eclipse Public License

**Comment by Dessyreqt** [comment]
MIT License... this is one of those things that CodePlex made you choose right away and I guess I never specified it here. Not sure if what the clearest way of doing so would be.
