### ISSUE TITLE
[v7] Unwinnable Casual Run

### ISSUE THREAD

**Issue by Dessyreqt** [Dessyreqt/alttprandomizer#345]
Submitter: Gullwhacker
Email: wizzard@nbnet.nb.ca
[v7]

Created a random game, wound up with seed C5990540.  Doesn't seem to be winnable - after spending a few hours I checked the spoiler log and don't see a way to proceed.  Tower of Hera's big key (and Desert Temple's boss) are locked behind torches, and the only sources of fire are in the Dark World or are the prize later in Tower of Hera.  Dark World isn't really accessible - the only sequence breakers are the Ocarina and the Hookshot, but without the Titan's Mitt or Hammer there's no way in.  I'd rush Aghanim, but Sahasrala has the Cape - and wants the medallion from Tower of Hera.

Still fun to get literally everything I could before that, but it looks like I'll have to start with another seed.  Complexity 3 seemed a little odd, admittedly...  If there's a solution I've missed (outside glitches, I did pick Casual), I'd love to hear it.  Thanks for making this, though - I might try with another seed and see how that goes!

**Comment by BlueViper85** [comment]
This is a known issue with the logic and a fix has been applied to the base code and is ready for any future updates.
