### ISSUE TITLE
Will this work with an emulator too?

### ISSUE THREAD

**Issue by Khalhys** [Dessyreqt/alttprandomizer#346]
I want to learn more about this before I get it.

I want to know if this is a standalone or an add-on to A Link to the Past. Furthermore, if it has to be a rom or if it can be an emulator as well.

I'm sorry if I asked a stupid question; I have little to know knowledge of programming. Nevertheless I thank you in advance for your patience.

**Comment by BlueViper85** [comment]
This is a modified version of ALttP. When you run the application and generate a Seed it will generate a ROM you can play on any SNES Emulator, SNES9x 1.51 (or higher or BSNES (aka Higan) are recommended. 

You can play it on a SNES console using a flashcart (SD2SNES or Everdrive).
