### ISSUE TITLE
Still stuck on how this works.

### ISSUE THREAD

**Issue by Khalhys** [Dessyreqt/alttprandomizer#347]
In reference to Issue #346 , I've downloaded the files, but some I opened as plain text files. I don't know if I was supposed to do that or leave them alone, but I can't re-download them as they were before.

The Emulator, Higan, Doesn't even run it for some reason. I don't know why, or if I'm not understanding something.

Please assist?
![the files](https://cloud.githubusercontent.com/assets/19635025/24086306/96e49264-0ce3-11e7-8ca9-3fbe11a0e5c0.png)
Above is a picture that shows what happened to some of the files.

**Comment by BlueViper85** [comment]
You downloaded the code. You can go to http://dessyreqt.github.io/alttprandomizer/ to download the application and run it. Just click Download at the top of the page. Read the page to get details on the various changes and other important things to be aware of, as there are many.
