### ISSUE TITLE
Dessyreqt contact

### ISSUE THREAD

**Issue by nyybatboy** [Dessyreqt/alttprandomizer#348]
Hey David, I had something I would like to discuss with you re: LttP modding. An idea I'm hoping interests you. Can you provide me with your contact info for a private discussion?

**Comment by BlueViper85** [comment]
There is an ALttP discord which has a Hacking channel where you can ask questions. Here is an invite to that.

https://discordapp.com/invite/3Bsfnwk

If you want to chat about the ALttP Randomizer there is a specific discord for that as well:  https://discord.gg/MsWxB5K
