### ISSUE TITLE
UNBEATABLE SEED C6020154

### ISSUE THREAD

**Issue by mistersg1** [Dessyreqt/alttprandomizer#349]
This seed is unbeatable, here's the scoop. I have beaten all dark world dungeons except Skull Woods, Misery Mire, and Turtle Rock

I can't beat the Skull Woods Dungeon because I need the Fire Rod to enter the second part of the dungeon, the Fire Rod is in the DEATH MOUNTAIN LEFT CAVE, but to get that chest I need to magic mirror there from Turtle Rock (unless you know something about the game I don't), furthermore, I can't get to the point in Turtle Rock because I DO NOT have the RED CANE (nor do I have the fire rod of course but RANDOM key placement could get me around that potentially). Where's the red cane, in the Skull Woods chest, but I can't get that because the big key is hidden behind that chest in the first room of Part 2 of Skull Woods which I need the fire rod to beat

Therefore this seed is unbeatable

QED

A Link to the Past Randomizer Log
---------------------------------
Version: 7
Creation Date: 3/29/17 9:36:13 PM
Complexity: 6
Seed: C6020154

Complexity Analysis
-------------------
Step 1 - Items reachable from start:
  [cave-021] Kakariko well [left chest row of 3]............................................Red Shield
  [cave-021] Kakariko well [right chest row of 3]...........................................Staff of Byrna
  [cave-022-B1] Thief's hut [bottom left chest].............................................Mushroom
  [cave-026] chicken house..................................................................Bottle (Fairy)
  [cave-031] Tavern.........................................................................Book of Mudora
  [cave-035] Sahasrahla's Hut [center chest]................................................Boomerang
  [cave-035] Sahasrahla's Hut [right chest].................................................Pegasus Boots
  [cave-044] Aginah's cave..................................................................Flippers
  [dungeon-C-1F] Sanctuary..................................................................Bow
  [dungeon-C-B1] Hyrule Castle - boomerang room.............................................Cape
  [dungeon-L1-1F] Eastern Palace - map room.................................................Blue Mail
  Bottle Vendor.............................................................................Shovel

Step 2 - Items reachable after collecting all items from Step 1:
  [cave-016] cave under rocks west of Santuary..............................................Ice Rod
  Haunted Grove item........................................................................Power Glove
  Heart Container (Armos Knights)...........................................................Magic Mirror
  Hobo......................................................................................Ocarina
  Library...................................................................................Bottle (Gold Bee)
  Pendant - Eastern Palace..................................................................Pendant of Power (Blue)
  Piece of Heart (Zora's River).............................................................Lamp

Step 3 - Items reachable after collecting all items from Step 2:
  [dungeon-C-B1] Escape - final basement room [left chest]..................................Magic Powder
  [dungeon-C-B1] Escape - final basement room [middle chest]................................Titan's Mitt
  [dungeon-L3-4F] Tower of Hera - 4F [small chest]..........................................Moon Pearl
  Pendant - Desert Palace...................................................................Pendant of Wisdom (Red)
  Pendant - Tower of Hera...................................................................Pendant of Courage (Green)
  Piece of Heart (Spectacle Rock Cave)......................................................Bottle (Gold Bee)
  Piece of Heart (Spectacle Rock)...........................................................Hookshot

Step 4 - Items reachable after collecting all items from Step 3:
  [cave-009-1F] Death Mountain - wall of caves - right cave [bottom chest]..................Bottle (Red Potion)
  [cave-012-1F] Death Mountain - wall of caves - left cave..................................Fire Rod
  [cave-056] Dark World Death Mountain - cave under boulder [bottom right chest]............Red Mail
  [cave-071] Misery Mire west area [right chest]............................................Hammer
  [cave-073] cave northeast of swamp palace [bottom chest]..................................Bug-Catching Net
  [dungeon-D2-B1] Swamp Palace - map room...................................................Mirror Shield
  [dungeon-D4-B1] Thieves' Town - Bottom left of huge room [bottom right chest].............Quake
  Crystal - Thieves' Town...................................................................Crystal 1 (Orange/Red)
  Piece of Heart (Death Mountain - floating island).........................................Red Boomerang
  Piece of Heart (Treasure Chest Game)......................................................Bombos

Step 5 - Items reachable after collecting all items from Step 4:
  [dungeon-D3-B1] Skull Woods - big chest...................................................Cane of Somaria
  Crystal - Dark Palace.....................................................................Crystal 7 (Zelda)
  Crystal - Ice Palace......................................................................Crystal 3 (Yellow/Brown)
  Crystal - Skull Woods.....................................................................Crystal 4 (Pink/Red)
  Crystal - Swamp Palace....................................................................Crystal 2 (Pink/White)

Step 6 - Items reachable after collecting all items from Step 5:
  [dungeon-A2-6F] Ganon's Tower - Moldorm room..............................................Ether
  Crystal - Misery Mire.....................................................................Crystal 5 (Green/Red)
  Crystal - Turtle Rock.....................................................................Crystal 6 (Green)

Generated Item Order
--------------------
[cave-044] Aginah's cave..................................................................Flippers
[cave-031] Tavern.........................................................................Book of Mudora
[dungeon-C-B1] Hyrule Castle - boomerang room.............................................Cape
Bottle Vendor.............................................................................Shovel
Haunted Grove item........................................................................Power Glove
[cave-022-B1] Thief's hut [bottom left chest].............................................Mushroom
Piece of Heart (Spectacle Rock Cave)......................................................Bottle (Gold Bee)
[dungeon-C-1F] Sanctuary..................................................................Bow
[cave-035] Sahasrahla's Hut [right chest].................................................Pegasus Boots
[dungeon-C-B1] Escape - final basement room [middle chest]................................Titan's Mitt
Heart Container (Armos Knights)...........................................................Magic Mirror
Piece of Heart (Spectacle Rock)...........................................................Hookshot
[cave-012-1F] Death Mountain - wall of caves - left cave..................................Fire Rod
Hobo......................................................................................Ocarina
[dungeon-L3-4F] Tower of Hera - 4F [small chest]..........................................Moon Pearl
[dungeon-C-B1] Escape - final basement room [left chest]..................................Magic Powder
[cave-071] Misery Mire west area [right chest]............................................Hammer
Piece of Heart (Treasure Chest Game)......................................................Bombos
[dungeon-D4-B1] Thieves' Town - Bottom left of huge room [bottom right chest].............Quake
[dungeon-D3-B1] Skull Woods - big chest...................................................Cane of Somaria

Light World
-----------
[cave-009-1F] Death Mountain - wall of caves - right cave [bottom chest]..................Bottle (Red Potion)
[cave-009-1F] Death Mountain - wall of caves - right cave [top left chest]................3 Bombs
[cave-009-1F] Death Mountain - wall of caves - right cave [top left middle chest].........1/4 Magic
[cave-009-1F] Death Mountain - wall of caves - right cave [top right chest]...............10 Arrows
[cave-009-1F] Death Mountain - wall of caves - right cave [top right middle chest]........Piece of Heart
[cave-009-B1] Death Mountain - wall of caves - right cave [left chest]....................70 Arrow Cap
[cave-009-B1] Death Mountain - wall of caves - right cave [right chest]...................20 Rupees
[cave-012-1F] Death Mountain - wall of caves - left cave..................................Fire Rod
[cave-013] Mimic cave (from Turtle Rock)..................................................Heart Container
[cave-016] cave under rocks west of Santuary..............................................Ice Rod
[cave-018] Graveyard - top right grave....................................................Piece of Heart
[cave-021] Kakariko well [bottom chest]...................................................100 Rupees
[cave-021] Kakariko well [center chest row of 3]..........................................20 Rupees
[cave-021] Kakariko well [left chest row of 3]............................................Red Shield
[cave-021] Kakariko well [right chest row of 3]...........................................Staff of Byrna
[cave-021] Kakariko well [top chest]......................................................10 Arrows
[cave-022-B1] Thief's hut [bottom left chest].............................................Mushroom
[cave-022-B1] Thief's hut [bottom right chest]............................................100 Rupees
[cave-022-B1] Thief's hut [top chest].....................................................Piece of Heart
[cave-022-B1] Thief's hut [top left chest]................................................Heart Container
[cave-022-B1] Thief's hut [top right chest]...............................................20 Rupees
[cave-026] chicken house..................................................................Bottle (Fairy)
[cave-031] Tavern.........................................................................Book of Mudora
[cave-034] Hyrule Castle secret entrance..................................................3 Bombs
[cave-035] Sahasrahla's Hut [center chest]................................................Boomerang
[cave-035] Sahasrahla's Hut [left chest]..................................................Piece of Heart
[cave-035] Sahasrahla's Hut [right chest].................................................Pegasus Boots
[cave-040] Link's House...................................................................Piece of Heart
[cave-044] Aginah's cave..................................................................Flippers
[cave-047] Dam............................................................................Heart Container
[cave-050] cave southwest of Lake Hylia - generous guy....................................100 Rupees
[cave-050] cave southwest of Lake Hylia [bottom left chest]...............................3 Bombs
[cave-050] cave southwest of Lake Hylia [bottom right chest]..............................Heart Container
[cave-050] cave southwest of Lake Hylia [top left chest]..................................3 Bombs
[cave-050] cave southwest of Lake Hylia [top right chest].................................1 Rupee
[cave-051] Ice Cave.......................................................................3 Bombs
Bombos....................................................................................Piece of Heart
Bottle Vendor.............................................................................Shovel
Ether.....................................................................................20 Rupees
Haunted Grove item........................................................................Power Glove
Hobo......................................................................................Ocarina
King Zora.................................................................................Piece of Heart
Library...................................................................................Bottle (Gold Bee)
Mushroom..................................................................................1 Arrow
Old mountain man..........................................................................5 Rupees
Piece of Heart (Dam)......................................................................3 Bombs
Piece of Heart (Death Mountain - floating island).........................................Red Boomerang
Piece of Heart (Desert - northeast corner)................................................3 Bombs
Piece of Heart (Desert - west side).......................................................3 Bombs
Piece of Heart (Graveyard)................................................................100 Rupees
Piece of Heart (Lake Hylia)...............................................................Piece of Heart
Piece of Heart (Lumberjack Tree)..........................................................20 Rupees
Piece of Heart (Maze Race)................................................................100 Rupees
Piece of Heart (south of Haunted Grove)...................................................50 Rupees
Piece of Heart (Spectacle Rock Cave)......................................................Bottle (Gold Bee)
Piece of Heart (Spectacle Rock)...........................................................Hookshot
Piece of Heart (Thieves' Forest Hideout)..................................................50 Rupees
Piece of Heart (Zora's River).............................................................Lamp
Purple Chest..............................................................................20 Rupees
Sahasrahla................................................................................20 Rupees
Sick Kid..................................................................................20 Rupees
Witch.....................................................................................Piece of Heart

Dark World
----------
[cave-055] Spike cave.....................................................................Piece of Heart
[cave-056] Dark World Death Mountain - cave under boulder [bottom left chest].............20 Rupees
[cave-056] Dark World Death Mountain - cave under boulder [bottom right chest]............Red Mail
[cave-056] Dark World Death Mountain - cave under boulder [top left chest]................Heart Container
[cave-056] Dark World Death Mountain - cave under boulder [top right chest]...............300 Rupees
[cave-057-1F] Dark World Death Mountain - cave from top to bottom [bottom chest]..........3 Bombs
[cave-057-1F] Dark World Death Mountain - cave from top to bottom [top chest].............Heart Container
[cave-062] C-shaped house.................................................................Piece of Heart
[cave-063] doorless hut...................................................................Piece of Heart
[cave-071] Misery Mire west area [left chest].............................................Piece of Heart
[cave-071] Misery Mire west area [right chest]............................................Hammer
[cave-073] cave northeast of swamp palace - generous guy..................................20 Rupees
[cave-073] cave northeast of swamp palace [bottom chest]..................................Bug-Catching Net
[cave-073] cave northeast of swamp palace [bottom middle chest]...........................20 Rupees
[cave-073] cave northeast of swamp palace [top chest].....................................20 Rupees
[cave-073] cave northeast of swamp palace [top middle chest]..............................10 Arrows
Catfish...................................................................................Heart Container
Flute Boy.................................................................................10 Arrows
Piece of Heart (Dark World - bumper cave).................................................Piece of Heart
Piece of Heart (Dark World blacksmith pegs)...............................................50 Rupees
Piece of Heart (Digging Game).............................................................10 Arrows
Piece of Heart (Pyramid)..................................................................20 Rupees
Piece of Heart (Treasure Chest Game)......................................................Bombos

Hyrule Castle Escape
--------------------
[dungeon-C-1F] Sanctuary..................................................................Bow
[dungeon-C-B1] Escape - final basement room [left chest]..................................Magic Powder
[dungeon-C-B1] Escape - final basement room [middle chest]................................Titan's Mitt
[dungeon-C-B1] Escape - final basement room [right chest].................................3 Bombs
[dungeon-C-B1] Escape - first B1 room.....................................................Piece of Heart
[dungeon-C-B1] Hyrule Castle - boomerang room.............................................Cape
[dungeon-C-B1] Hyrule Castle - map room...................................................Key
[dungeon-C-B3] Hyrule Castle - next to Zelda..............................................Map

Eastern Palace
--------------
[dungeon-L1-1F] Eastern Palace - big ball room............................................Piece of Heart
[dungeon-L1-1F] Eastern Palace - big chest................................................Map
[dungeon-L1-1F] Eastern Palace - Big key..................................................Big Key
[dungeon-L1-1F] Eastern Palace - compass room.............................................Compass
[dungeon-L1-1F] Eastern Palace - map room.................................................Blue Mail
Heart Container (Armos Knights)...........................................................Magic Mirror

Desert Palace
-------------
[dungeon-L2-B1] Desert Palace - big chest.................................................Map
[dungeon-L2-B1] Desert Palace - Big key room..............................................Compass
[dungeon-L2-B1] Desert Palace - compass room..............................................Big Key
[dungeon-L2-B1] Desert Palace - Map room..................................................100 Rupees
Heart Container (Lanmolas)................................................................Heart Container

Tower of Hera
-------------
[dungeon-L3-1F] Tower of Hera - first floor...............................................Compass
[dungeon-L3-2F] Tower of Hera - Entrance..................................................Big Key
[dungeon-L3-4F] Tower of Hera - 4F [small chest]..........................................Moon Pearl
[dungeon-L3-4F] Tower of Hera - big chest.................................................Map
Heart Container (Moldorm).................................................................10 Arrows

Hyrule Castle Tower
-------------------
[dungeon-A1-2F] Hyrule Castle Tower - 2 knife guys room...................................Key
[dungeon-A1-3F] Hyrule Castle Tower - maze room...........................................Key

Dark Palace
-----------
[dungeon-D1-1F] Dark Palace - big chest...................................................Map
[dungeon-D1-1F] Dark Palace - big key room................................................Key
[dungeon-D1-1F] Dark Palace - compass room................................................20 Rupees
[dungeon-D1-1F] Dark Palace - jump room [left chest]......................................Key
[dungeon-D1-1F] Dark Palace - jump room [right chest].....................................Key
[dungeon-D1-1F] Dark Palace - maze room [bottom chest]....................................3 Bombs
[dungeon-D1-1F] Dark Palace - maze room [top chest].......................................50 Rupees
[dungeon-D1-1F] Dark Palace - spike statue room...........................................Key
[dungeon-D1-1F] Dark Palace - statue push room............................................Key
[dungeon-D1-B1] Dark Palace - room leading to Helmasaur [left chest]......................20 Rupees
[dungeon-D1-B1] Dark Palace - room leading to Helmasaur [right chest].....................Compass
[dungeon-D1-B1] Dark Palace - shooter room................................................Key
[dungeon-D1-B1] Dark Palace - turtle stalfos room.........................................Big Key
Heart Container (Helmasaur King)..........................................................50 Rupees

Swamp Palace
------------
[dungeon-D2-1F] Swamp Palace - first room.................................................Key
[dungeon-D2-B1] Swamp Palace - big chest..................................................10 Arrows
[dungeon-D2-B1] Swamp Palace - big key room...............................................Big Key
[dungeon-D2-B1] Swamp Palace - map room...................................................Mirror Shield
[dungeon-D2-B1] Swamp Palace - push 4 blocks room.........................................3 Bombs
[dungeon-D2-B1] Swamp Palace - south of hookshot room.....................................300 Rupees
[dungeon-D2-B2] Swamp Palace - flooded room [left chest]..................................Compass
[dungeon-D2-B2] Swamp Palace - flooded room [right chest].................................Map
[dungeon-D2-B2] Swamp Palace - hidden waterfall door room.................................Piece of Heart
Heart Container (Arrghus).................................................................Piece of Heart

Skull Woods
-----------
[dungeon-D3-B1] Skull Woods - big chest...................................................Cane of Somaria
[dungeon-D3-B1] Skull Woods - Big Key room................................................Key
[dungeon-D3-B1] Skull Woods - Compass room................................................300 Rupees
[dungeon-D3-B1] Skull Woods - east of Fire Rod room.......................................Key
[dungeon-D3-B1] Skull Woods - Entrance to part 2..........................................Big Key
[dungeon-D3-B1] Skull Woods - Gibdo/Stalfos room..........................................Compass
[dungeon-D3-B1] Skull Woods - south of Fire Rod room......................................Key
Heart Container (Mothula).................................................................Map

Thieves Town
------------
[dungeon-D4-1F] Thieves' Town - Room above boss...........................................50 Rupees
[dungeon-D4-B1] Thieves' Town - Bottom left of huge room [bottom right chest].............Quake
[dungeon-D4-B1] Thieves' Town - Bottom left of huge room [top left chest].................20 Rupees
[dungeon-D4-B1] Thieves' Town - Bottom right of huge room.................................Big Key
[dungeon-D4-B1] Thieves' Town - Top left of huge room.....................................Key
[dungeon-D4-B2] Thieves' Town - big chest.................................................20 Rupees
[dungeon-D4-B2] Thieves' Town - next to Blind.............................................Compass
Heart Container (Blind)...................................................................Map

Ice Palace
----------
[dungeon-D5-B1] Ice Palace - Big Key room.................................................50 Bomb Cap
[dungeon-D5-B1] Ice Palace - compass room.................................................Compass
[dungeon-D5-B2] Ice Palace - map room.....................................................Map
[dungeon-D5-B3] Ice Palace - spike room...................................................Key
[dungeon-D5-B4] Ice Palace - above Blue Mail room.........................................Key
[dungeon-D5-B5] Ice Palace - b5 up staircase..............................................Big Key
[dungeon-D5-B5] Ice Palace - big chest....................................................Piece of Heart
Heart Container (Kholdstare)..............................................................10 Arrows

Misery Mire
-----------
[dungeon-D6-B1] Misery Mire - big chest...................................................Compass
[dungeon-D6-B1] Misery Mire - big hub room................................................Big Key
[dungeon-D6-B1] Misery Mire - big key.....................................................Key
[dungeon-D6-B1] Misery Mire - compass.....................................................Key
[dungeon-D6-B1] Misery Mire - end of bridge...............................................Key
[dungeon-D6-B1] Misery Mire - map room....................................................5 Rupees
[dungeon-D6-B1] Misery Mire - spike room..................................................Map
Heart Container (Vitreous)................................................................300 Rupees

Turtle Rock
-----------
[dungeon-D7-1F] Turtle Rock - Chain chomp room............................................Key
[dungeon-D7-1F] Turtle Rock - compass room................................................Key
[dungeon-D7-1F] Turtle Rock - Map room [left chest].......................................Key
[dungeon-D7-1F] Turtle Rock - Map room [right chest]......................................Big Key
[dungeon-D7-B1] Turtle Rock - big chest...................................................10 Arrows
[dungeon-D7-B1] Turtle Rock - big key room................................................Compass
[dungeon-D7-B1] Turtle Rock - Roller switch room..........................................50 Rupees
[dungeon-D7-B2] Turtle Rock - Eye bridge room [bottom left chest].........................Map
[dungeon-D7-B2] Turtle Rock - Eye bridge room [bottom right chest]........................20 Rupees
[dungeon-D7-B2] Turtle Rock - Eye bridge room [top left chest]............................Key
[dungeon-D7-B2] Turtle Rock - Eye bridge room [top right chest]...........................20 Rupees
Heart Container (Trinexx).................................................................3 Bombs

Ganon's Tower
-------------
[dungeon-A2-1F] Ganon's Tower - above Armos...............................................Key
[dungeon-A2-1F] Ganon's Tower - big chest.................................................Piece of Heart
[dungeon-A2-1F] Ganon's Tower - compass room [bottom left chest]..........................Heart Container
[dungeon-A2-1F] Ganon's Tower - compass room [bottom right chest].........................20 Rupees
[dungeon-A2-1F] Ganon's Tower - compass room [top left chest].............................Piece of Heart
[dungeon-A2-1F] Ganon's Tower - compass room [top right chest]............................Big Key
[dungeon-A2-1F] Ganon's Tower - down right staircase from entrance [left chest]...........Compass
[dungeon-A2-1F] Ganon's Tower - down right staircase from entrance [right chest]..........Piece of Heart
[dungeon-A2-1F] Ganon's Tower - east of down right staircase from entrace.................3 Bombs
[dungeon-A2-1F] Ganon's Tower - map room..................................................Key
[dungeon-A2-1F] Ganon's Tower - north of gap room [bottom left chest].....................Map
[dungeon-A2-1F] Ganon's Tower - north of gap room [bottom right chest]....................Piece of Heart
[dungeon-A2-1F] Ganon's Tower - north of gap room [top left chest]........................Piece of Heart
[dungeon-A2-1F] Ganon's Tower - north of gap room [top right chest].......................20 Rupees
[dungeon-A2-1F] Ganon's Tower - north of teleport room....................................10 Arrows
[dungeon-A2-1F] Ganon's Tower - west of teleport room [bottom left chest].................3 Bombs
[dungeon-A2-1F] Ganon's Tower - west of teleport room [bottom right chest]................3 Bombs
[dungeon-A2-1F] Ganon's Tower - west of teleport room [top left chest]....................20 Rupees
[dungeon-A2-1F] Ganon's Tower - west of teleport room [top right chest]...................Key
[dungeon-A2-6F] Ganon's Tower - before Moldorm............................................1 Rupee
[dungeon-A2-6F] Ganon's Tower - Moldorm room..............................................Ether
[dungeon-A2-6F] Ganon's Tower - north of falling floor four torches [top left chest]......Heart Container
[dungeon-A2-6F] Ganon's Tower - north of falling floor four torches [top right chest].....Heart Container + Refill
[dungeon-A2-B1] Ganon's Tower - north of Armos room [bottom chest]........................10 Arrows
[dungeon-A2-B1] Ganon's Tower - north of Armos room [left chest]..........................20 Rupees
[dungeon-A2-B1] Ganon's Tower - north of Armos room [right chest].........................20 Rupees

Special Locations
-----------------
Bottle Item - Pyramid.....................................................................Bottle (Red Potion)
Bottle Item - Waterfall...................................................................Bottle (Bee)
Crystal - Dark Palace.....................................................................Crystal 7 (Zelda)
Crystal - Ice Palace......................................................................Crystal 3 (Yellow/Brown)
Crystal - Misery Mire.....................................................................Crystal 5 (Green/Red)
Crystal - Skull Woods.....................................................................Crystal 4 (Pink/Red)
Crystal - Swamp Palace....................................................................Crystal 2 (Pink/White)
Crystal - Thieves' Town...................................................................Crystal 1 (Orange/Red)
Crystal - Turtle Rock.....................................................................Crystal 6 (Green)
Pendant - Desert Palace...................................................................Pendant of Wisdom (Red)
Pendant - Eastern Palace..................................................................Pendant of Power (Blue)
Pendant - Tower of Hera...................................................................Pendant of Courage (Green)
Required Medallion - Misery Mire..........................................................Bombos
Required Medallion - Turtle Rock..........................................................Quake
Sword - Fairy.............................................................................Master Sword
Sword - Pedestal..........................................................................Tempered Sword
Sword - Smithy............................................................................Gold Sword

**Comment by miketrethewey** [comment]
Link's House
Go through Escape
Open Sanctuary chest for Bow
Use the copious amounts of cash at bomb shop in SW Kakariko to buy Bombs
Use the copious amounts of cash at Bottle Vendor to buy Shovel
Walk to Haunted Grove and dig up Power Glove
Walk to Aginah's Cave in NE Desert for Flippers
Use Flippers to get to Hobo for Ocarina
Go to Kakariko and activate Flute
Flute to spot 5
Go beat Armos Knights in Eastern Palace to get Magic Mirror
Flute to spot 1
Climb Death Mountain and use free-access portal
Mirror back on top of Spectacle Rock for Hookshot
Fall back down to bottom of mountain
Head east to broken bridge
Hookshot across broken bridge
Enter far bottom-right cave
Up, left, upstairs, kill mini-moldorms, south exit
Counting the gap below us as first, we go left to the fourth gap.
Jump down, enter cave
Spiral around to hole, fall in hole
Open chest, ???, Fire Rod
Go to SkWoods. Fire Rod to open Second Entrance. Circle back to that first chest you see to get Big Key. Go back to Big Chest for Cane of Somaria.

**Comment by ChristosOwen** [comment]
The Fire Rod is in a dark world death mountain chest that does not require mirror, NOT the one part way through turtle rock (mimic room). You just need access to east DM, which you already have. Check the left door of the double-doors at the base of east death mountain in the dark world.
