### ISSUE TITLE
C1907977 how do you get to zora's river with NO power glove/titan's mitt

### ISSUE THREAD

**Issue by mistersg1** [Dessyreqt/alttprandomizer#351]
To get the titan's mitt, it says I need to go to Zora's River in the spoiler.....but how do I do that with NO power glove?

Is this one beatable?

**Comment by BlueViper85** [comment]
I'm not in a place to check the spoiler log to confirm it's completable; however, if you have the flippers there is a warp in Lake Hylia just south of the Stairs up to the Pond of Happiness (the island) that takes you to the screen just outside of Zora's domain.

**Comment by mistersg1** [comment]
Dang it, you are absolutely right, I should have known better to use that warp.

**Comment by BlueViper85** [comment]
Happy to help!
