### ISSUE TITLE
Cannot enter Desert Palace or Dark World Seed 460112249

### ISSUE THREAD

**Issue by D3g3n** [Dessyreqt/alttprandomizer#352]
This may be doable but if it is I wouldn't know how. Moon Pearl is on the ledge in desert, and the book and magic mirror are on the side of Death Mountain I can't reach without going into the dark world. Hookshot at the darkworld pyramid so cannot use bridge. Any Ideas?

Seed: 460112249

**Comment by BlueViper85** [comment]
If the seed was generated via the newer web system  any issue should be reported via that page's Report Issue feature. If it were generated in this application the seed would start with a C or G depending on the mode and would have fewer numbers.

But that says, if you have the cape or level 2 sword you can beat Agahnim to get to the pyramid and collect the hook shot without the moon pearl. Then you should be able to save and quit back to the light world.
