### ISSUE TITLE
Not randomizing swords.

### ISSUE THREAD

**Issue by Dessyreqt** [Dessyreqt/alttprandomizer#357]
Submitter: Zack
[v7]
Hey guys, just started using the randomizer so i could definetely just be doing things wrong, but every seed ive generated has the swords randomized but still in there 3 respective locations. thanks.

**Comment by BlueViper85** [comment]
This is how the v7 randomizer works.  It randomizes all the swords (except the first sword (fighter)) among the three sword locations (pedestal, smiths, cursed fairy)

No contact information provided, closing issue.
