### ISSUE TITLE
[v7] Issue with Blacksmiths

### ISSUE THREAD

**Issue by Dessyreqt** [Dessyreqt/alttprandomizer#358]
Submitter: 10x
[v7] When blacksmiths are reunited they will take your sword and give you their random item.

My seed - C9044163

**Comment by BlueViper85** [comment]
When you reunite the smiths in v7 and talk to them they give you another sword. You have to talk to them to give it and pay the 10 rupees, leave and come back and they give you whatever sword they have. If they have a sword lower than your current sword you get your sword back.

No contact info to get more details. Closing issue.
