### ISSUE TITLE
[v7] bad seed

### ISSUE THREAD

**Issue by Dessyreqt** [Dessyreqt/alttprandomizer#359]
Submitter: Miles
[v7]

the seed is C5383084 can not find the power/titans glove and no mirror in the beginning so can't go get the glove and no upgraded sword to go fight agahnim

**Comment by HonkiTonk** [comment]
Hyrule Castle - boomerang room -> Cape
Mushroom -> Flippers
Use the waterteleport to the zoras.
King Zora -> Moon Pearl
Sahasrahla's Hut [right chest] -> Bow
Heart Container (Armos Knights) -> Hookshot
Use the Cape to get into Hyrule Castle Tower and beat Agahnim.
Use the Hookshot in the dark world and go to the Swamp.
cave northeast of swamp palace - generous guy -> Hammer
cave northeast of swamp palace [bottom chest] -> Power Glove
cave northeast of swamp palace [bottom middle chest] -> Boomerang
cave northeast of swamp palace [top chest] -> Lamp
Use the Hookshot and the Hammer to reach the Tower of Hera.
Tower of Hera - Entrance -> Magic Mirror

**Comment by BlueViper85** [comment]
Solution provided. No contact info provided. Closing issue.
