### ISSUE TITLE
ALTTP Randomizer VT, race mode, seed impossible (at least I think)

### ISSUE THREAD

**Issue by FalconQC** [Dessyreqt/alttprandomizer#360]
Hello, 

Not sure if it can help you, but I wish to share a seed here, that I believe is impossible to beat. I cannot read spoilers for that seed because I generate the seed using the function "race". The seed is open, but without glitch (meaning I had to find myself a sword, which I did. 

Seed: ALttP - VT_no-glitches-19_normal-open_LzMY9JxDMg.sfc

Basically, I have the following: 
- Sword, shield and blue mail. 
- 12 hearts. 
- Silver arrows (no bow). 
- Blue boomerang.  
- Hookshot
- Bombs
- Fire rod
- Quake
- Lantern
- Some bottles. 
- Red cape
- Magic Mirror
- Boots
- Power glove
- Moon perl
- Mushroom (was in palace of darkness, I went to the witch and I got some garbage). 

I finished off hyrule castle, including sewers, link's uncle and the chest near by...and the three chests that can be accessed later from the cemetery. 
I finished off tower of Hera (was a crystal). 
I finished off Aghanim phase 1 (hyrule tower). 
I got as far as possible in eastern palace (no bow, so stuck to get to the boss). 
I got as far as possible in Palace of Darkness. No big key, so missing the big chest and no bow, so missing the two chests that can be accessed by the teleportation device (need the bow to beat the red knight). 

I've done this (not in this order). 

- Chest in Sanctuary. 
- Chest left to sanctuary (with the boots). 
- Cleaned town Kakariko light world, including the sick guy (had a bottle for that), well, green roof house, house with crack wall on the right, maze, bottle seller, and the pub (blue house, back entrance). 
- Check lost woods and Lumberjacks cave. 
- Chest in link house. 
- Check the DAM (two items). 
- Check one chest in desert (one item, nothing of value on the right side, which cannot be accessed at this time). 
- Check Ice rod location. 
- Check the cave with the thief and four chests near Lake Hylia. 
- Check three chests at the sage near eastern palace. 
- Spectacle rock and the cave just under it 
- East death mountain light world (with hookshot). 
- Pyramide. 
- Cat fish. 

I manage to glitch the fake flippers which I never do normally. The guy that sleeps under the bridge did not help. Nothing on the small island either (no access for now). 

In order to progress, I need either: 
- Flippers (to get the hammer in the waterfalls, no access without flippers). 
- Titan mitts (to get in outcast, or death mountain dark world). 
- Bow (to complete eastern palace (and possibly get the item from the sage near the palace since it is pendant of courage) and also to continue in palace of darkness (need to get Hammer to clean it) ). 
- Book of Mudora (to get into desert palace. 

That's about it. Looks like I cannot attached my "saved file", and I'm pretty sure that I cannot attached the seed itself due to ... rules. The reference is on top (ALttP - VT_no-glitches-19_normal-open_LzMY9JxDMg.sfc), but I am not able to generate a spoiler file that works. Feel free to look at it, and if you see something that I may have overlooked, then it would be nice to drop me a hint. 

Thank you

![items_alttp - vt_no-glitches-19_normal-open_lzmy9jxdmg](https://cloud.githubusercontent.com/assets/28245202/25571808/8ea816a4-2e01-11e7-835d-af11c3fdce24.JPG)
![map_darkworld_alttp - vt_no-glitches-19_normal-open_lzmy9jxdmg](https://cloud.githubusercontent.com/assets/28245202/25571806/8ea50ba8-2e01-11e7-9703-2b512f075757.JPG)
![map_lightworld_alttp - vt_no-glitches-19_normal-open_lzmy9jxdmg](https://cloud.githubusercontent.com/assets/28245202/25571807/8ea6867c-2e01-11e7-973d-e03f92616d11.JPG)

**Comment by BlueViper85** [comment]
Looking VERY briefly here you have the hookshot and you said you beat agahnim.

Go to the pyramid and go east one screen and follow the dirt path north. When you reach the area with the broken bridge, just a little above that is a break in the barrier. Hookshot across. This gives you access to the north and north western part of DW as well as the Village of Outcasts.

You can comment here for additional questions, however I will be closing the issue. Please not that the VT randomizer has a link on it at the top to report issues with it where they can help you.

**Comment by FalconQC** [comment]
I'm  extremely disappointed with myself now. That's ... obvious. 
Alright, I just lost 15 minutes of my time to explain all of this. Sorry about that.

**Comment by BlueViper85** [comment]
It's an easy thing to miss. Good luck on your future randomizers!
