### ISSUE TITLE
Zora gave no item?

### ISSUE THREAD

**Issue by KimWahlman** [Dessyreqt/alttprandomizer#361]
Note: I am new to the entire Randomizer thing, so I don't know if this is intentional or not, if it is feel free to close/delete the ticket.

I don't know what you want/need to know so I'll just add what I can think of. The ROM is linked below if it is needed. If anything else is needed please tell me what and I'll try and find it.

Seed: Green mail, flute, ether, mirror shield, bug-catching net.
Filename: ALttP - VT_no-glitches-19_normal-standard_O4v5Lxx3Mq.sfc [ [Link](http://kimwahlman.com/ftp/ALttP_-_VT_no-glitches-19_normal-standard_O4v5Lxx3Mq.sfc) ]
What happened: I went to Zora to see what item I would get, I got nothing.
Video: https://www.youtube.com/watch?v=sDKOEUjF9_g

What the textfile is telling me:
```
{
    "meta": {
        "difficulty": "normal",
        "logic": "no-glitches-19",
        "build": "2017-04-15",
        "mode": "standard"
    }
}
```

**Comment by KatDevsGames** [comment]
Thank you for your report. Unfortunately, your bug report appears to be for the V8 webclient version of randomizer. You can report bugs with the webclient by clicking the "Report a Problem" link in the upper right or by going to https://github.com/sporchia/alttp_vt_randomizer/issues/new and simply copying your submission to that window.

**Comment by sporchia** [comment]
But also to save you time, Zora requires 500 rupees, you seem to be a little shy

**Comment by KimWahlman** [comment]
Oh tanks for the info @sporchia :)
