### ISSUE TITLE
Unbeatable seed from most recent logic?

### ISSUE THREAD

**Issue by TheBraveHylian** [Dessyreqt/alttprandomizer#363]
The seed number is 267891746, using the newest logic from vt.alttp.run. I'm not sure if you guys support issues from the online generator at this time but I'm pretty sure this seed is unbeatable. This is Normal Difficulty with the No Glitches Logic.
Here's my issue:

Turtle Rock is a crystal dungeon. The Cane of Somaria is required to beat this dungeon. The Cane of Somaria is located in Misery Mire. The Medallion required to open Misery mire is the Quake. Quake is the Bumper Cave item. Hookshot is required to traverse the bumper cave. The Hookshot is located in the Mimic Cave, which to my knowledge is only accessible from Turtle Rock.

**Comment by BlueViper85** [comment]
You can traverse the bumper cave by walking up to the edge of the pit and walking left and hugging the wall around the hole making this accessible without accessing the mimic cave.

For future reference please report any issues with the web-based randomizer via the appropriate link on the vt.alttp.run page
