### ISSUE TITLE
VT Randomizer Idea and Soft lock

### ISSUE THREAD

**Issue by Dessyreqt** [Dessyreqt/alttprandomizer#364]
Submitter: Tantalus-X
Pls remove the door in red ring make soft lock you not find key in the chest ( dungeon-C-2F )
http://fs5.directupload.net/images/170517/g2op8pbl.png

can pls add option for Progressive Boomerang and add version number i see not patched VT Randomizer

**Comment by ChristosOwen** [comment]
You can s+q back to the throne room if you miss the key so this isn't a softlock.

You can switch between boomerangs with Y in the menu; we don't currently have plans to make them progressive.
