### ISSUE TITLE
Possible Issue

### ISSUE THREAD

**Issue by willyfunt** [Dessyreqt/alttprandomizer#366]
I was unable to complete this seed.
Lantern is in Graveyard Cave.  This unlocks pegusus boots (big chest in palace of darkness, I dont want to got through this blind) and titan mitts are in library.  I don't see any way to get to Graveyard cave missing Boots and Mitts.

Let me know.
Thanks.

Logic: no-glitches-21
ROM build: 2017-05-12
Difficulty: normal
Mode: standard
Goal: ganon
Seed: 115611631
Save Spoiler  Save Rom
 Spoiler!
Light World
Escape
Eastern Palace
Desert Palace
Death Mountain
East Death Mountain
Tower of Hera
Hyrule Castle Tower
Dark World
North East Dark World
North West Dark World
South Dark World
Palace of Darkness
Swamp Palace
Skull Woods
Thieves Town
Ice Palace
Misery Mire
Turtle Rock
Ganons Tower
Pendants
Crystals
Medallions
Fountains
playthrough
meta
{
    "1": {
        "Light World": {
            "Uncle": "Progressive Sword",
            "[cave-047] Dam": "Flippers",
            "[cave-040] Link's House": "Magic Cape",
            "[cave-044] Aginah's cave": "Hookshot",
            "[cave-021] Kakariko well [right chest row of 3]": "Moon Pearl",
            "[cave-022-B1] Thief's hut [bottom right chest]": "Flute",
            "[cave-050] cave southwest of Lake Hylia [top left chest]": "Progressive Glove"
        }
    },
    "2": {
        "Hyrule Castle": {
            "[dungeon-C-B1] Escape - first B1 room": "Fire Rod"
        },
        "Death Mountain": {
            "[cave-009-1F] Death Mountain - wall of caves - right cave [top left chest]": "Hammer"
        },
        "Dark World": {
            "Catfish": "Bow",
            "[cave-062] C-shaped house": "Ice Rod",
            "[cave-073] cave northeast of swamp palace [top middle chest]": "Book Of Mudora",
            "[cave-073] cave northeast of swamp palace [bottom middle chest]": "Magic Mirror"
        }
    },
    "3": {
        "Light World": {
            "Piece of Heart (Graveyard)": "Lamp",
            "Piece of Heart (Desert - west side)": "Progressive Sword"
        },
        "Swamp Palace": {
            "[dungeon-D2-B1] Swamp Palace - big key room": "Cane Of Somaria"
        },
        "Eastern Palace": {
            "Eastern Palace Pendant": "Crystal 4"
        },
        "Tower Of Hera": {
            "Tower of Hera Pendant": "Crystal 1"
        },
        "Skull Woods": {
            "Skull Woods Crystal": "Crystal 7"
        }
    },
    "4": {
        "Dark Palace": {
            "[dungeon-D1-1F] Dark Palace - big chest": "Pegasus Boots",
            "Palace of Darkness Crystal": "Crystal 3"
        }
    },
    "5": {
        "Light World": {
            "Library": "Progressive Glove"
        }
    },
    "6": {
        "Light World": {
            "Piece of Heart (Desert - northeast corner)": "Quake"
        },
        "Dark World": {
            "[cave-057-1F] Dark World Death Mountain - cave from top to bottom [top chest]": "Progressive Sword",
            "[cave-056] Dark World Death Mountain - cave under boulder [bottom left chest]": "Ether"
        },
        "Ice Palace": {
            "Ice Palace Crystal": "Crystal 2"
        }
    },
    "7": {
        "Misery Mire": {
            "Misery Mire Crystal": "Crystal 6"
        },
        "Turtle Rock": {
            "Turtle Rock Crystal": "Crystal 5"
        }
    },
    "8": {
        "Ganons Tower": {
            "[dungeon-A2-1F] Ganon's Tower - above Armos": "Silver Arrows Upgrade"
        }
    },
    "longest_item_chain": 8,
    "regions_visited": 17
}

**Comment by BlueViper85** [comment]
This relates to the web based randomizer and should be submitted there. Go to vt.alttp.run and click the Report Issue in the upper-right.

I do agree that this seems like poor placement assuming that navigating dark rooms is something that is still meant to be avoided in the standard difficulty.
