### ISSUE TITLE
version 8.22 algorithm updates

### ISSUE THREAD

**Issue by gatordile** [Dessyreqt/alttprandomizer#368]
First of, I absolutely love this randomizer. It's amazing. One things bugging me a little though. I really liked the trollish nature of version 8.21 in regards to item placements and late game items. The new version seems to take away from the randomness feeling a bit. I'm wondering if there's a way to keep the v8.21 trollish algorithms somehow, perhaps as a custom setting switch or as a downloadable version?

Thanks again for this game and your time.

**Comment by BlueViper85** [comment]
This page is for the v7 application-based randomizer. Please resubmit using the Report Issue button on the web-based randomizer at vt.alttp.run
