### ISSUE TITLE
Do not reveal freestanding items until collected

### ISSUE THREAD

**Issue by Trivial-Man** [Dessyreqt/alttprandomizer#369]
It would be a fun mode to make it so all items look identical prior to being picked up, perhaps as a custom ? sprite or something. It would totally change strategies that rely on checking items without solving the puzzles needed to get them and make the game just that bit more random.

**Comment by ChristosOwen** [comment]
This may be something we implement in the web version eventually: http://vt.alttp.run/

We recently did this for the festive themed randomizers so we have the capability!

**Comment by ChristosOwen** [comment]
We now have this logged on our end so no need for this open issue. Will happen eventually!
