### ISSUE TITLE
[v7] Randomizer keeps crashing

### ISSUE THREAD

**Issue by Dessyreqt** [Dessyreqt/alttprandomizer#372]
Submitter: Malcolm Flaherty
[v7]

For some reason, every time I try to create a new randomized rom, the randomizer program will crash and a rom won't be made. I've tried redownloading it, lanching it as an administrator, but nothing seems to work. And, just in case you ask, I have tried using the new version online, but it won't accept my japanese rom even though it's a version 1.0 .sfc file. Can you help? I would really appreciate it.

**Comment by BlueViper85** [comment]
Make sure you the path the file is generating on is valid with appropriate characters and that you can write to it.

You can also try the newer randomizer at vt.alttp.run. 

No contact info provided. Closing.
