### ISSUE TITLE
Can't download randomizer with 'HTTPS Everywhere' enabled

### ISSUE THREAD

**Issue by GiantWolfSpider** [Dessyreqt/alttprandomizer#373]
I can upload the Japanese game file, select all the options, click the 'Generate' button, but it just loads forever without producing the ROM. It worked before the latest update, before you could select your character, so I'm not sure what changed. 

I tried turning off HTTPS Everywhere and it generated the randomized ROM.

After that, I reproduced it by clearing the cookies and saved info from Firefox, going to the randomizer page, disabled NoScript, loaded the ROM, and tried generating the ROM 3 times with no success. 

Then, I disabled HTTPS Everywhere and it produced the randomized ROM within seconds of clicking 'Generate'.

I'm not sure what else you need to know or that I can tell you, but please feel free to ask. 

Browser: Firefox 54.0 (32 bit)
OS: Windows 10 Home, 64 bit

I run NoScript 5.0.5 in Firefox but I disable it on the randomizer page. I also run HTTPS Everywhere 5.2.18.

**Comment by BlueViper85** [comment]
I'm assuming this is referencing the web randomizer based on a variety of statements. Please report this issue using the "Report Issue" button on that page (http://vt.alttp.run)

**Comment by GiantWolfSpider** [comment]
My mistake. Sorry about that.

**Comment by GiantWolfSpider** [comment]
My mistake. I reported it there.
