### ISSUE TITLE
Cant complete seed...

### ISSUE THREAD

**Issue by carnathfd** [Dessyreqt/alttprandomizer#374]
attempted seed: G9RYA5M6 (which is blue boomerang, magic dust, empty bottle, hookshot, shovel) and it appears that bombos (required to access turtle rock) is either in turtle rock or in ganon's tower. 

I should note i did rename the file for a race, so i may have inadvertantly removed the first character in the seed. if so, you can disregard this.

**Comment by BlueViper85** [comment]
This should be reported on the web-based randomized page at http://vt.alttp.run use the menu and click Report an Issue or the otherwise appropriate button
