### ISSUE TITLE
No light in dark rooms in light world dungeons and caves.

### ISSUE THREAD

**Issue by SonicAnim** [Dessyreqt/alttprandomizer#375]
Hi,

I seem to be having a slight issue with the randomizer that I hope someone can give some information on please. I'm using the required ROM for the randomizer, SNES9x emulator version 1.53 and have the following settings set over http://vt.alttp.run/randomizer:

Mode: Standard
Goal: Defeat Ganon
Seed: Random
Logic: No Glitches
Difficulty: Normal

From what I've read up is that if you don't have the lantern you can still go into dark cave areas in the Light World and dark rooms in Eastern Palace and Hyrule Castle (Light World) and still have a flashlight view at least to see where you are going. However these areas for me are pitch black and I cannot see anything at all except effects of weapons etc.

I understand that you need the lantern for Dark World dungeons and caves, but I thought Light World dungeons and caves should be so that I can see automatically regardless of whether I have the lantern in procession or not. This has happened to me on 2 generated games now and I am wondering if there's something I am doing wrong or if I have missed a setting when generating the ROM please?

I've attached one of the generated ROMs in question inside a ZIP folder and any help would be appreciated.

Thanks.

[ALttP - VT_no-glitches-24_normal-standard-ganon_641975418.zip](https://github.com/Dessyreqt/alttprandomizer/files/1137139/ALttP.-.VT_no-glitches-24_normal-standard-ganon_641975418.zip)

**Comment by BlueViper85** [comment]
Light cones require the lamp. Make sure to not compare info on this randomizer page to the info on https://vt.alttp.run as they are different. 

If you feel this is still an issue you want reported, please submit to the issues page using the menu on that page (https://vt.alttp.run)
