### ISSUE TITLE
[v7] Crystals/Pendants/Swords

### ISSUE THREAD

**Issue by Dessyreqt** [Dessyreqt/alttprandomizer#378]
Submitter: Ed
Hi, so when I randomize, all pendants only randomize to pendant drop locations and the same with the crystals. Also, the swords will only ever be found in sword locations (pedestal smithy etc) how do I fix this? Do I have to use glitched logic?

**Comment by BlueViper85** [comment]
This is normal for v7. Use the new randomizer at vt.alttp.run for further randomization of these items.
