### ISSUE TITLE
Stuck in Misery Mire

### ISSUE THREAD

**Issue by ogsell** [Dessyreqt/alttprandomizer#379]
v.7
Seed:C4482987

Misery Mire
-----------
[dungeon-D6-B1] Misery Mire - big chest...................................................Key
[dungeon-D6-B1] Misery Mire - big hub room................................................Piece of Heart
[dungeon-D6-B1] Misery Mire - big key.....................................................Key
[dungeon-D6-B1] Misery Mire - compass.....................................................Big Key
[dungeon-D6-B1] Misery Mire - end of bridge...............................................Key
[dungeon-D6-B1] Misery Mire - map room....................................................Compass
[dungeon-D6-B1] Misery Mire - spike room..................................................Heart Container
Heart Container (Vitreous)................................................................Map

I think i'm stuck in Misery Mire if i'm right, and i cant find another key to open the door on the southwest of the big room. I remember that i opened the door on the upper right of the big room and the door with the skeletons and spikes. i think i looked everywhere but can't find any other small key to open the door in the southwest. So my question is, am i stuck now and have to restart? I think the missing key is the one where i could find the big key but without it i cant reach the big key in the compass room :/

**Comment by BlueViper85** [comment]
If I'm understanding correctly, you may have one key still available that you need to be careful with.

From the room with the skeletons and spikes (spike room), go through the northern door and follow the path to the room with more spikes and skeletons, and a crystal switch.  There is a key under the pot in that room.  Walk back the way you came (don't use the southern key door if it's still locked)  and then hopefully you can progress.

http://ian-albert.com/games/legend_of_zelda_a_link_to_the_past_maps/dungeon-D6-B1.png

Upper-left of that map you'll see the Boss (Vitreous) and the room below him with the firesnake, the pit, stairs to the floor below.  Directly to the right of that room is the room I'm talking about.
