### ISSUE TITLE
Potentially Stuck Early, Will explain (w/spoiler log)

### ISSUE THREAD

**Issue by JeesusShuttlesworth** [Dessyreqt/alttprandomizer#382]
Here's the list of reasons why I seem to be stuck:

1. I can't seem to enter the Dark World at all, as I have no hammer, glove, cape, or Master Sword.
2. The **hammer** is in the Hyrule Castle basement, final room, but I can't get to the room since first B1 room didn't have a small key and I have no glove to allow me to enter through the graveyard.
3. One **glove** is with the Eastern Palace boss, but I have no bow to get past the Red Eyegore (bow is in Swamp Palace). The other **glove** is at the Ether tablet on Death Mountain, which I cannot reach without the other glove or a hammer.
4. **Cape** is in the Dark World.
5. The remaining three **swords** are 1) Mimic Cave on Death Mountain, which requires Dark World (both gloves), 2) Moldorm, which requires Dark World or hammer, and 3) Ganon's Tower.

Am I really stuck? I looked at the playthrough spoilers but it accesses Tower of Hera with no hammer or glove.

Light World:
{
    "Altar": "Five Rupees",
    "Uncle": "Twenty Rupees",
    "[cave-034] Hyrule Castle secret entrance": "Twenty Rupees",
    "[cave-018] Graveyard - top right grave": "Piece Of Heart",
    "[cave-047] Dam": "Half Magic",
    "[cave-040] Link's House": "Mushroom",
    "[cave-031] Tavern": "Twenty Rupees",
    "[cave-026] chicken house": "Flippers",
    "[cave-044] Aginah's cave": "Heart Container",
    "[cave-035] Sahasrahla's Hut [left chest]": "Heart Container (refill)",
    "[cave-035] Sahasrahla's Hut [center chest]": "Three Bombs",
    "[cave-035] Sahasrahla's Hut [right chest]": "Bottle (Golden Bee)",
    "[cave-021] Kakariko well [top chest]": "Fifty Rupees",
    "[cave-021] Kakariko well [left chest row of 3]": "Progressive Armor",
    "[cave-021] Kakariko well [center chest row of 3]": "Bomb Upgrade (5)",
    "[cave-021] Kakariko well [right chest row of 3]": "Hookshot",
    "[cave-021] Kakariko well [bottom chest]": "Heart Container",
    "[cave-022-B1] Thief's hut [top chest]": "Shovel",
    "[cave-022-B1] Thief's hut [top left chest]": "Twenty Rupees",
    "[cave-022-B1] Thief's hut [top right chest]": "Arrow Upgrade (5)",
    "[cave-022-B1] Thief's hut [bottom left chest]": "Heart Container",
    "[cave-022-B1] Thief's hut [bottom right chest]": "Bottle (Green Potion)",
    "Blacksmiths": "Arrow Upgrade (5)",
    "[cave-016] cave under rocks west of Santuary": "Five Rupees",
    "[cave-050] cave southwest of Lake Hylia [bottom left chest]": "Three Bombs",
    "[cave-050] cave southwest of Lake Hylia [top left chest]": "Twenty Rupees",
    "[cave-050] cave southwest of Lake Hylia [top right chest]": "Magic Mirror",
    "[cave-050] cave southwest of Lake Hylia [bottom right chest]": "Arrow Upgrade (10)",
    "[cave-051] Ice Cave": "Magic Powder",
    "Bottle Vendor": "Magical Boomerang",
    "Sahasrahla": "Fifty Rupees",
    "Magic Bat": "Heart Container",
    "Sick Kid": "Heart Container",
    "Purple Chest": "Bottle (Blue Potion)",
    "Hobo": "Progressive Sword",
    "Bombos Tablet": "Piece Of Heart",
    "King Zora": "Ten Arrows",
    "Piece of Heart (Thieves' Forest Hideout)": "Flute",
    "Piece of Heart (Lumberjack Tree)": "Piece Of Heart",
    "Piece of Heart (south of Haunted Grove)": "Fifty Rupees",
    "Piece of Heart (Graveyard)": "Piece Of Heart",
    "Piece of Heart (Desert - northeast corner)": "Twenty Rupees",
    "[cave-050] cave southwest of Lake Hylia - generous guy": "Three Hundred Rupees",
    "Library": "Ice Rod",
    "Mushroom": "Heart Container",
    "Witch": "Progressive Shield",
    "Piece of Heart (Maze Race)": "Twenty Rupees",
    "Piece of Heart (Desert - west side)": "Piece Of Heart",
    "Piece of Heart (Lake Hylia)": "Piece Of Heart",
    "Piece of Heart (Dam)": "Boomerang",
    "Piece of Heart (Zora's River)": "Book Of Mudora",
    "Haunted Grove item": "Three Hundred Rupees"
}

Hyrule Castle:
{
    "[dungeon-C-1F] Sanctuary": "Moon Pearl",
    "[dungeon-C-B1] Escape - final basement room [left chest]": "Key",
    "[dungeon-C-B1] Escape - final basement room [middle chest]": "Hammer",
    "[dungeon-C-B1] Escape - final basement room [right chest]": "Dungeon Map",
    "[dungeon-C-B1] Escape - first B1 room": "Quake",
    "[dungeon-C-B1] Hyrule Castle - boomerang room": "Twenty Rupees",
    "[dungeon-C-B1] Hyrule Castle - map room": "Twenty Rupees",
    "[dungeon-C-B3] Hyrule Castle - next to Zelda": "Five Rupees"
}

Eastern Palace:
{
    "[dungeon-L1-1F] Eastern Palace - compass room": "Ten Arrows",
    "[dungeon-L1-1F] Eastern Palace - big chest": "Compass",
    "[dungeon-L1-1F] Eastern Palace - big ball room": "Big Key",
    "[dungeon-L1-1F] Eastern Palace - Big key": "Dungeon Map",
    "[dungeon-L1-1F] Eastern Palace - map room": "Three Bombs",
    "Heart Container - Armos Knights": "Progressive Glove",
    "Eastern Palace Pendant": "Crystal 3"
}

Desert Palace:
{
    "[dungeon-L2-B1] Desert Palace - big chest": "Dungeon Map",
    "[dungeon-L2-B1] Desert Palace - Map room": "Cane Of Byrna",
    "[dungeon-L2-B1] Desert Palace - Small key room": "Key",
    "[dungeon-L2-B1] Desert Palace - Big key room": "Big Key",
    "[dungeon-L2-B1] Desert Palace - compass room": "Bomb Upgrade (5)",
    "Heart Container - Lanmolas": "Compass",
    "Desert Palace Pendant": "Crystal 7"
}

Death Mountain:
{
    "Old Mountain Man": "Bombos",
    "Piece of Heart (Spectacle Rock Cave)": "Arrow Upgrade (5)",
    "Ether Tablet": "Progressive Glove",
    "Piece of Heart (Spectacle Rock)": "Heart Container",
    "[cave-012-1F] Death Mountain - wall of caves - left cave": "Cane Of Somaria",
    "[cave-013] Mimic cave (from Turtle Rock)": "Progressive Sword",
    "[cave-009-1F] Death Mountain - wall of caves - right cave [top left chest]": "Twenty Rupees",
    "[cave-009-1F] Death Mountain - wall of caves - right cave [top left middle chest]": "Twenty Rupees",
    "[cave-009-1F] Death Mountain - wall of caves - right cave [top right middle chest]": "Fifty Rupees",
    "[cave-009-1F] Death Mountain - wall of caves - right cave [top right chest]": "Bomb Upgrade (5)",
    "[cave-009-1F] Death Mountain - wall of caves - right cave [bottom chest]": "Arrow Upgrade (5)",
    "[cave-009-B1] Death Mountain - wall of caves - right cave [left chest]": "Twenty Rupees",
    "[cave-009-B1] Death Mountain - wall of caves - right cave [right chest]": "Piece Of Heart",
    "Piece of Heart (Death Mountain - floating island)": "Three Bombs"
}

**Comment by BlueViper85** [comment]
Spoiler log clearly indicates that this is for the new randomizer.

Please resubmit this at http://vt.alttp.run and use the Report an Issue (or similar) option there.
