### ISSUE TITLE
Hookshot on bumper cave?!

### ISSUE THREAD

**Issue by LexamusPrime** [Dessyreqt/alttprandomizer#384]
Hookshot is on bumper cave. Can't get through bumper cave without hookshot. Am I missing something?

**Comment by BlueViper85** [comment]
As could be guessed by the fact that the Hookshoot was placed there, you can actually get through the cave without the Hookshot.

After you come out of the stairs for the second floor,, walk down to just above the pit and then walk West/Left. If you were close enough to the top of the pit you'll walk right between the pit and the wall, and then you can pick up the pots.
