### ISSUE TITLE
Unable to reach mirror, softlock?

### ISSUE THREAD

**Issue by GameOutLoud** [Dessyreqt/alttprandomizer#386]
My seed has placed the magic mirror in the Tower of Hera, and while I hear that there's a hookshot/hammer option to reach Tower of Hera, the hammer is in Thieves' Town.  I believe I need either the hammer or the mirror to reach there...  Am I missing something, or am I totally stuck?
[ALttP - VT_no-glitches-26_normal-standard-ganon_975213106.txt](https://github.com/Dessyreqt/alttprandomizer/files/1404567/ALttP.-.VT_no-glitches-26_normal-standard-ganon_975213106.txt)

::Edit:: I think I found what I was missing.  The Save/quit thing allowed me to explore the dark world and get the titan's mitt, and get back to the light world.  That'll give me access to Thieves' Town.  Will post back if I get stuck again.

**Comment by miketrethewey** [comment]
This repository is for Version 7 of the Randomizer.
If you do have further issues with this seed, please report to the "Report Issue" link found in the upper-right corner of the Randomizer website ( http://vt.alttp.run/ ).
