### ISSUE TITLE
Ending Sequence Text Pool?

### ISSUE THREAD

**Issue by protogilly** [Dessyreqt/alttprandomizer#387]
Not really an issue so much as a question, I poked around the source and couldn't find where the ending sequence text changes are made (eg: the master sword text changed to something like "The Couch Cash Sleeps Again" or "Boy Lifts Again"). If this isn't in the current source, is there a place I can find a comprehensive list of all the possible text choices?

**Comment by miketrethewey** [comment]
This repository is for Version 7 of the Randomizer.
You're looking for the "Report Issue" Link in the upper right of Version 8's Randomizer ( http://vt.alttp.run/ ).
The source you're looking for can be found in Altar.php and the sub folders of:
https://github.com/sporchia/alttp_vt_randomizer/tree/master/app/Location

**Comment by ChristosOwen** [comment]
You can also contact Veetorp on Discord if you have any further questions about this: https://discord.gg/xzxy2Mq
