### ISSUE TITLE
Hammer unreachable -  C0324765

### ISSUE THREAD

**Issue by avenger339** [Dessyreqt/alttprandomizer#39]
[dungeon-D5-B2] Ice Palace - map room.....................................................Hammer

This specific location requires you to go to the other side of the room, which is blocked by heads you have to hit with the hammer.  It is impossible to get in this seed.

**Comment by Mime64** [comment]
Had a similar issue using the seed 16092109

In my case, the hammer was in the big chest, and big key was in the same chest that avenger339 listed above. With the switch on the other side, needing the hammer to get to, this was a softlock.

**Comment by Dessyreqt** [comment]
This is addressed in v5
