### ISSUE TITLE
Forced to go through dark room in pod

### ISSUE THREAD

**Issue by Deflaktor** [Dessyreqt/alttprandomizer#390]
Hi, I have come across a seed in which I can choose to use my last obtainable dungeon key for one of two doors. One of the doors leads me to a progression item. The other door leads me to a dark room. So I used up my last key and am now forced to navigate through a dark room. 

I have checked the spoilers and went through all kinds of possibilities on how I could get a lamp with my current inventory:
-bluemarang
-‎hookshot
-‎ice rod
-‎hammer
-‎boots 
-‎power gloves
-‎moon pearl
-‎flippers

in order to get a lamp I need a mirror, which is in the hookshot cave. I cannot access death mountain unless I get the flute. And the flute was behind the other room which I could choose to use my key on. 

The dungeon in question is pod. When I go to the left door after the breaking bridge I use up my key and will have to navigate through a dark room to potentially get another key. When I go to the right door, I can get the flute which opens the path to death mountain.

[ALttP - VT_no-glitches-27_easy-open-ganon_230938447.txt](https://github.com/Dessyreqt/alttprandomizer/files/1574021/ALttP.-.VT_no-glitches-27_easy-open-ganon_230938447.txt)

**Comment by StarWolf3000** [comment]
Why not post over at sporchia/alttp_vt_randomizer instead, since you're using that one?

**Comment by ChristosOwen** [comment]
This is actually a valid issue, I'll follow this up in the correct GitHub.

**Comment by ChristosOwen** [comment]
This has been fixed as of V28! :)

BTW you posted on a legacy Github. The new one for the current randomizer is:

https://github.com/sporchia/alttp_vt_randomizer

And make sure you're generating seeds from the website not the outdated application:

http://vt.alttp.run/randomizer

Lastly you can join the community on Discord too:

discord.gg/alttprandomizer
