### ISSUE TITLE
Need help plz

### ISSUE THREAD

**Issue by doggieboy8954** [Dessyreqt/alttprandomizer#391]
is it possible to get here without the hammer?

[cave-056] Dark World Death Mountain - cave under boulder [top right chest]...............Hammer

**Comment by StarWolf3000** [comment]
If you have Titan's Mitt and Hookshot, then cross the bridge, use the teleporter located under the dark boulder and then use the left of the two caves. It leads to the upper part, right next to the large boulder.

**Comment by ChristosOwen** [comment]
Also note the current version: http://vt.alttp.run/

And the Discord: https://discord.gg/xzxy2Mq
