### ISSUE TITLE
CanAccess maybe not accurate for Dark Palace - turtle stalfos room

### ISSUE THREAD

**Issue by sectokia** [Dessyreqt/alttprandomizer#392]
Accessing the turtle stalfos room requires you to drop down after opening the first key door.

Now, assuming inventory has:
		Hammer
		MoonPeal
		PowerGlove
		Bombs	
		Lamp
And that a small key is NOT in ' Dark Palace - shooter room'

Then CanAccess ' Dark Palace - turtle stalfos room' returns true.

However, you cannot actually access it:
-There is room you must go through in B1 and kill all the enemies in (the room with 2x Green Goriya, and 1x Red Goriya).
-There is no way to kill Red Goriya with the items you have. You need Bow, or medallion with master sword (or better).

**Comment by ChristosOwen** [comment]
This is heavily updated in the current web version: http://vt.alttp.run/

And the Discord: https://discord.gg/xzxy2Mq
