### ISSUE TITLE
Extra case for CanAccess of 3x Escape final basement room chests

### ISSUE THREAD

**Issue by sectokia** [Dessyreqt/alttprandomizer#393]
CanAccess requirement for "[dungeon-C-B1] Escape - final basement room"s is "CanLiftLightRocks". However you can access it merely by having bombs, so long as "Escape - first B1 room" is a small key.

So a more liberal CanAccess for the 3 chests could be:
CanLiftLightRocks(have) || (LocationHasItem("[dungeon-C-B1] Escape - first B1 room", $Item_Key)

In this situation, if the Escape - first b1 room chest is a small key, players can simply re-do the escape path after they have bombs, and access the chests without going via graveyard.

**Comment by ChristosOwen** [comment]
This is heavily updated in the current web version: http://vt.alttp.run/

And the Discord: https://discord.gg/xzxy2Mq
