### ISSUE TITLE
Need Mirror but its in Bumper Cave. Blacksmith has Magic cape to get through bumper cave?

### ISSUE THREAD

**Issue by Spiritbeats** [Dessyreqt/alttprandomizer#397]
Need Mirror but its in Bumper Cave. Blacksmith has Magic cape to get through bumper cave? How do I do this? I need mirror to get cape and cape to get mirror ?

**Comment by ChristosOwen** [comment]
You don't need the mirror for the Blacksmith, you can s+q with him to return to the LW :)

BTW you posted on a legacy Github. The new one for the current randomizer is:

https://github.com/sporchia/alttp_vt_randomizer

And make sure you're generating seeds from the website not the outdated application:

http://vt.alttp.run/randomizer

Lastly you can join the community on Discord too:

discord.gg/alttprandomizer
