### ISSUE TITLE
Believe I've found an unbeatable game

### ISSUE THREAD

**Issue by daftinquisitor** [Dessyreqt/alttprandomizer#399]
This might be a little hard for me to give much info on, since I stupidly deleted the patch file I used. Don't know if it helps, but the "HASH" on the startup screen is showing as:
Green Pendant - Hookshot - Boss Key - Hammer - Hammer

I've made it most of the way through the game, but I'm stuck on two particular spots. I have most of the items in the game, but never found the Magic Mushroom, Fire Rod, or Cape. Without the Fire Rod, I can't open the main entrance to the Skull Woods dungeon, nor can I progress past the first couple of rooms of Turtle Rock, the only two dungeons I haven't beat.

Not having the cape blocks me from getting a couple of items (spike floor rooms), same with the magic mushroom preventing one. The Red Pendant is in Turtle Rock too, so I haven't gotten whatever is in the Master Sword's place, and I'm about 95% sure I have gotten every single other obtainable chest in the game.

I can provide the image I'm using if that helps at all.

**Comment by daftinquisitor** [comment]
Nevermind, you can lock this out. Finally found the Fire Rod after going through a "Heart Piece" guide. It was in a light-world cave reached from Misery Mire, had completely forgotten that it even existed.

**Comment by ChristosOwen** [comment]
Glad you resolved this.

BTW you posted on a legacy Github. The new one for the current randomizer is:

https://github.com/sporchia/alttp_vt_randomizer

And make sure you're generating seeds from the website not the outdated application:

http://vt.alttp.run/randomizer

Lastly you can join the community on Discord too:

discord.gg/alttprandomizer
