### ISSUE TITLE
Seed C7651352 - Glitchless Softlocked

### ISSUE THREAD

**Issue by avenger339** [Dessyreqt/alttprandomizer#40]
Piece of Heart (Dam)......................................................................Pegasus Boots
Library...................................................................................Bow
[cave-016] cave under rocks west of Santuary..............................................Flippers
[cave-026] chicken house..................................................................Book of Mudora
[cave-022-B1] Thief's hut [top left chest]................................................Bottle
[cave-047] Dam............................................................................Cape
[dungeon-L2-B1] Desert Palace - compass room..............................................Power Glove
Piece of Heart (Desert - west side).......................................................Magic Mirror
[cave-022-B1] Thief's hut [bottom left chest].............................................Hookshot
[cave-050] cave southwest of Lake Hylia [top right chest].................................Moon Pearl
[dungeon-D2-B2] Swamp Palace - flooded room [left chest]..................................Titan's Mitt
Piece of Heart (Lake Hylia)...............................................................Bombos
Piece of Heart (Dark World - bumper cave).................................................Fire Rod
[cave-018] Graveyard - top right grave....................................................Lamp / 5 rupees
[cave-062] C-shaped house.................................................................Hammer
[cave-073] cave northeast of swamp palace - generous guy..................................Quake
[dungeon-D1-1F] Dark Palace - maze room [bottom chest]....................................Cane of Somaria
[cave-057-1F] Dark World Death Mountain - cave from top to bottom [bottom chest]..........Shovel
[cave-071] Misery Mire west area [right chest]............................................Mirror Shield
Piece of Heart (Death Mountain - floating island).........................................Ether
[dungeon-D2-B1] Swamp Palace - map room...................................................Ice Rod

I have no way to beat Dungeons 2 and 3 glitchless (Both require the Lantern or Fire Rod).  They are both in the Dark World and the items required to get to the Dark World early (Hammer and Titan's Mitt are not found until the dark world).

**Comment by elevow** [comment]
I have something similar with the Lamp & Fire Rod - I don't think I can complete the Desert Temple without being able to set the 4 torches on Fire. Both require access to Dark World.

Version: 4
Creation Date: 7/24/2016 3:38:55 PM
Seed: C7133625
Catfish...................................................................................Lamp / 5 rupees
Purple Chest..............................................................................Fire Rod

**Comment by churine** [comment]
The first one can get the Magic Cape in the dam, which allows you to pass through the barrier at Hyrule Castle Tower and fight Agahnim, enabling the castle's gate.

**Comment by elevow** [comment]
Thanks @zilarch any other tips or tricks to get to the Catfish without completing the 3 Temples?

**Comment by Dessyreqt** [comment]
C7133625 also wants you to use the cape to defeat Agahnim. Neither of these seeds are softlocks.

**Comment by elevow** [comment]
That was it.  I didn't know about the cape trick and it worked.  Thank you/
