### ISSUE TITLE
[v7] Stuck Issue

### ISSUE THREAD

**Issue by Dessyreqt** [Dessyreqt/alttprandomizer#401]
Submitter: Ramon
Email: luigi_garcia@hotmail.com
[v7]
Unable to finish due to candle being at Moldorm, Fire Rod in Purple chest and Titan's mitts in big chest in Tower of Hera

**Comment by ChristosOwen** [comment]
If you're on V7 that is VERY outdated now. Please see the following resources:

V8.29 Website: http://vt.alttp.run/start
Current Version GitHub: https://github.com/sporchia/alttp_vt_randomizer
Discord Community: discord.gg/alttprandomizer

The application version is no longer maintained and is heavily outdated, and contains known issues, so please use the website. And please join us on Discord too where we can answer any questions you might have!
