### ISSUE TITLE
No flashlight effect in Castle Sewers

### ISSUE THREAD

**Issue by demonwolf8398** [Dessyreqt/alttprandomizer#403]
Hey, I started a new randomized seed on the "Normal mode" difficulty, and I had some surprisingly great first items, except for when I went into the castle dungeon to find chests. As I understand, this isn't an emulation issue (Unless it is, I'm honestly not too sure) But as you're aware, the lamp you start the game with didn't spawn where it was supposed to. I can't traverse through the castle sewers, or the dark room in the first Light World dungeon. Any info or feedback on the issue is appreciated. I've played this game for years and not even I want to try to kill myself in a dark room.

**Comment by miketrethewey** [comment]
This is by design. ALttP Escape is not required as your first task in this game. You can load up at Sanctuary and get out to the overworld area. From Link’s House you can head south too. The Lamp will be found somewhere prior to needing it.

**Comment by BlueViper85** [comment]
This version of the randomizer was retired in favor of a significantly updated version over at https://alttpr.com/
