### ISSUE TITLE
Impossible mitts in seed

### ISSUE THREAD

**Issue by RiddleMeThis54** [Dessyreqt/alttprandomizer#404]
So I am trying to get all items in the seed I have, but am running into an issue where i can not get the titan mitts because they are in the digging game and I can not get the shovel because it is behind the hammer pegs in the east part of underworld village. Please let me know if there is something I am missing. For reference seed is 815126948 thanks loving the randomizer though!

**Comment by KatDevsGames** [comment]
This version of the randomizer was discontinued in December of 2016. 
Please use and report any bugs to the current version.

**Comment by BlueViper85** [comment]
Current version available at https://alttpr.com/
