### ISSUE TITLE
 (Seed: C7750588) impossible, need pegasus boots or titan's mitt to access Zora's river

### ISSUE THREAD

**Issue by DFPercush** [Dessyreqt/alttprandomizer#406]
One of these two items is required to access King Zora and the piece of heart in Zora's River. Seed: C7750588
Complexity Analysis
Step 2 - Items reachable after collecting all items from Step 1:
  King Zora.................................................................................Bow
  Piece of Heart (Zora's River).............................................................Moon Pearl
Step 3 - Items reachable after collecting all items from Step 2:
  [cave-073] cave northeast of swamp palace [bottom middle chest]...........................Pegasus Boots
Step 4 - Items reachable after collecting all items from Step 3:
  [cave-009-1F] Death Mountain - wall of caves - right cave [bottom chest]..................Titan's Mitt

**Comment by BlueViper85** [comment]
Pretty sure you can just walk past the stacks of stones and jump down to the lower level from the left side. You’d need to warp or save and quit to get out though.

In any event, this version of the randomizer has been retired. You can access the latest randomizer at https://alttpr.com
