### ISSUE TITLE
Web based terminal returning invalid address error

### ISSUE THREAD

**Issue by AkivaDaphydd** [Dessyreqt/alttprandomizer#408]
The link located at https://dessyreqt.github.io/alttprandomizer returns a DNS error when the link is attempted to be used. I have tried the link in both Firefox and Chrome. I'm not sure if the error is specifically my ISP (Cox Cable) or a possible error in the HTML/Java coding used for the site.

If the error is not a true DNS error, please provide the correct URL I should be using.

**Comment by BlueViper85** [comment]
Page loads fine for me on more than one internet connection.

Please note that this version of the ALttP Randomizer has been retired in favor of http://www.alttpr.com
