### ISSUE TITLE
Power Glove in Link's house?

### ISSUE THREAD

**Issue by blicksky** [Dessyreqt/alttprandomizer#41]
Is it possible to have the Power Glove assigned to the chest in Link's house, such that you can lift the rock in the southeast corner of the castle grounds and leave the intro sequence while it's still raining? If that assignment is allowed, would you consider adding a feature to the randomizer to choose one or more of the item locations so you can create a game that's set up this way?

**Comment by Dessyreqt** [comment]
This is not possible. For Casual mode, I REALLY want you to have a sword.

**Comment by blicksky** [comment]
Fair enough. To generalize the idea, I might also be interested in something like making sure that the moon pearl and hammer or titan's mitt are found early so I can see what it's like to explore the dark world early on without the master sword. What do you think about the idea of choosing a few "legal" item locations and letting the randomizer fill in the rest? Maybe just an option to choose between a few scenarios like this to adjust the randomization? Perhaps what I'm describing is something different from the randomizer, and what I'm really looking for is just a tool to edit individual item locations in a more raw way.
