### ISSUE TITLE
Lamp spawns after dark rooms

### ISSUE THREAD

**Issue by DanielKrawisz** [Dessyreqt/alttprandomizer#410]
For me the lamp spawned in Turtle Rock and the only way to get it is to go through a dark room that's impossible to navigate without light! I don't think there's another way to light up a room.

**Comment by Dessyreqt** [comment]
If you're talking about the platform room, you can hold the direction until you hit the junction to go that way. Hopefully you'll be able to tell when you've passed the junction and can hold the next direction. If you can't sorry! I personally am not good at the dark rooms myself and have to pull up a map whenever I come across them.

That said, this version of the randomizer is quite outdated. I recommend you check out https://alttpr.com/en and use that to create a seed to play. There is improved logic, and I believe you can set it so the lamp is considered required to make it past locked rooms.
