### ISSUE TITLE
Can't Leave Starting House

### ISSUE THREAD

**Issue by Ki11erRabbit** [Dessyreqt/alttprandomizer#42]
Whenever I go to leave my house the game gives me a "Save and Continue" or "Save and Quit" menu that I cannot close without it opening up.
![problem with leaving house](https://cloud.githubusercontent.com/assets/20647749/17112101/5f964022-5259-11e6-8594-407ae85d5b58.PNG)

**Comment by Dessyreqt** [comment]
Your select button is being held down. Double check your controller settings (if using emulator) or clean out or controller (if using an SNES.)
