### ISSUE TITLE
Bottles don't appear in the menu until you get another item

### ISSUE THREAD

**Issue by BlueViper85** [Dessyreqt/alttprandomizer#44]
When you get a bottle before any other Y-button menu item, the bottle doesn't appear in the item menu, which can give the impression that you didn't actually get the bottle.

As soon as you obtain the lamp, or any other Y-Button menu item (the sword + shield don't seem to count) then that item as well as the bottle(s) appear in the start menu.

Seed C6977827, for example, has a bottle in Link's house, and it won't show up until you get the ice rod from the Sanctuary chest or the bombs from one of the chests in the town well.

This has the additional side-effect of having your Pendants and sword/shield/mail status not being able to be checked if you get bombs, then use them all leaving only the bottle in your inventory.  While I'd expect this to be fixed via the menu changes in v5, it's better mentioned than not.

**Comment by Dessyreqt** [comment]
This is addressed in v5
