### ISSUE TITLE
Feature request: Keep in RNG

### ISSUE THREAD

**Issue by simplyorange** [Dessyreqt/alttprandomizer#47]
This is quite fun to play, but a bunch of the game's natural mechanics are being lifted a bit.  Would it be possible to have a branch / switch to keep in RNG?

**Comment by KatDevsGames** [comment]
Personally I think this is a great idea as long as dessyreqt doesn't mind adding an RNG checkbox. It would probably have to add an R to the end of the seed number or something I'd imagine.

**Comment by simplyorange** [comment]
Small update: Please include things like Ag's blue balls (this is listed as a bug and it's not a bug), shovel drops (so shovel does NOT give items except at dig game) as part of this keep original mechanics / RNG-option.

**Comment by Dessyreqt** [comment]
I'm not interested in adding this to my randomizer. I'm not saying your preference is wrong here, but I don't really understand wanting to add randomness back into the game when it doesn't contribute in a skill-testing manner. Having to encode a preference like that into a seed is also not a good idea, that's reserved for difficulty. This randomizer is built to be a simple "roll it and play" and including an option like that goes against this philosophy.

**Comment by simplyorange** [comment]
I really cannot agree.  I didn't ask for a preference; I think it the game's RNG code shouldn't be altered.  That's not purely randomizing the items anymore, that's playing a game that isn't ALTTP anymore.  RNG is part of the game.

How is it not a 'skill-testing' manner?  Every action the player takes does actually effect how the RNG behaves.  The entire process of this 'run to x chests first unless you don't have y item'--how is that at all skill-based once you know the optimal pattern?  I really cannot buy your logic and I'm very fearful for the direction this project has gone as it's very close to me saying it's not even the same game anymore.

**Comment by KatDevsGames** [comment]
No
