### ISSUE TITLE
Ganon's Tower Key Lock

### ISSUE THREAD

**Issue by BlueViper85** [Dessyreqt/alttprandomizer#49]
It's possible to keylock yourself in Ganon's Tower in seed C6693181.  It appears that there may have been one too many keys on the right side of the tower.  By going down the left side and opening the door linking the first two basement rooms (the one requiring the red cane and the one with the bonk key) you are prevented from being able to get paste either the tile room or the door right before Moldorm 2.

Here's a link to a video to see this in action: https://www.twitch.tv/barnowl/v/81182475?t=02h53m56s

Suggest removing the door between the two first lower rooms (at least for casual) seems like the most plausible solution; however, adjusting the key logic to prevent too many keys from being on either side is also a fair solution.

**Comment by Dessyreqt** [comment]
Amusingly my wife found this issue a few hours ago, so this is already fixed, and will be available in v6.
