### ISSUE TITLE
[v5] Smithy follower update

### ISSUE THREAD

**Issue by Dessyreqt** [Dessyreqt/alttprandomizer#50]
Submitter: ChristosOwen
Email: ChristosOwen@hotmail.co.uk
Dwarf to not be removed when you s+q or die in the DW - instead to remain cursed if you spawn in DW (have defeated Agahnim and have mirror) or to revert to Smithy if you spawn in LW (have no mirror, regardless of defeating Agahnim). This allows Tempered Sword without mirror and removes any confusing behaviour with his status and all softlock potential. Have discussed with Karkat and it's the preferred solution.

**Comment by KatDevsGames** [comment]
Upon further discussion with ChristosOwen, decision has been made to remove follower upon deathwarping to the light world.

**Comment by KatDevsGames** [comment]
Fixed in trunk rom.
