### ISSUE TITLE
Weird light world waterfall fairy glitch

### ISSUE THREAD

**Issue by Dessyreqt** [Dessyreqt/alttprandomizer#51]
Submitter: Myramong on twitch
Email: 
Started a new game, file name リンク
Link's house chest, and all of Hyrule Castle chests.
I think I checked the tree item
Went to forest, checked shroom spot then the hole
Down to kakariko, I think i did the hole first, then the building with the leafy roof.  Went to the small building with a bombable wall to get some more bombs, then chicken house, bar, sick kid.
Checked library
Did maze race
Checked swamp dam thing, did chest first, then drained the water
Went east, did the place with 4 chests and the dude
Ice rod place
Swim to hobo
Swim to the whirlpool that goes to zoras
Go to fairy

The red sword is available to be throw into the water, despite not having the red sword.  Game crashes upon throwing it in.
Earlier today a friend (BlueCrystal004) told me he got the golden sword here (that's the only reason I went to check the fairy myself).

BlueCrystal also visited the hobo before the fairy, so I'm guessing the bug is related to the hobo.

Here's the rom, save state, and srm: http://puu.sh/qmUrz/2c1ab4ec69.rar

**Comment by KatDevsGames** [comment]
Fixed in trunk rom.
