### ISSUE TITLE
Game Crash in Money Making Game

### ISSUE THREAD

**Issue by pholtos** [Dessyreqt/alttprandomizer#54]
In the light world, in the lost woods, there's a money making game at the top side near the lumberjack entrance.

If you talk to the guy and choose to play then open a chest, talking to the guy again causes a crash, every time. Dunno why it happens but thought I'd report it.

**Comment by pholtos** [comment]
I'd like to add this seems to happen at other money making games also.

**Comment by KatDevsGames** [comment]
Cause is already known.

**Comment by KatDevsGames** [comment]
Fixed in trunk rom
