### ISSUE TITLE
Delay when using Quake for opening Mire

### ISSUE THREAD

**Issue by BlueViper85** [Dessyreqt/alttprandomizer#55]
When Quake was used to open Mire there was a noticeable delay between the end of the Quake animation and the beginning of the opening animation for Mire (where it comes out of the water).

Seed was C4365231

Video showing this as it happened: https://www.twitch.tv/christosowen/v/81470598?t=02h41m00s

**Comment by Dessyreqt** [comment]
Christos said this probably isn't an issue.

**Comment by KatDevsGames** [comment]
Timed with split timer. Entrance opening takes 14s consistently.
