### ISSUE TITLE
Feature Request: English Version?

### ISSUE THREAD

**Issue by meriwinkle** [Dessyreqt/alttprandomizer#57]
This is probably the wrong place to ask, but I spent a while searching for wherever the community lives and couldn't find them.

Could there ever be an English-language version, for people less familiar with the game? Maybe it would be too much work to do, but I'd love to be able to play it for myself. It looks incredible so far.

**Comment by Dessyreqt** [comment]
We are actually working to remove most of the text in this game. That doesn't exactly make it "English", but most of the text is fairly irrelevant to randomizer.

**Comment by meriwinkle** [comment]
How difficult a job do you think it would be for a beginning coder to try doing myself? I don't even know  what language it's written in but if it's straightforward enough and won't ever happen otherwise I could maybe give it a shot, at some point...

**Comment by KatDevsGames** [comment]
The text has been disabled in the various routines themselves in the randomizer base rom. It's not actually part of the randomizer software. Reenabling it would require a high level of proficiency in 65c816 assembly as well as intimate knowledge of the game's internals.

On August 4, 2016 5:50:20 PM EDT, meriwinkle notifications@github.com wrote:

> How difficult a job do you think it would be for a beginning coder to
> try doing myself? I don't even know  what language it's written in but
> if it's straightforward enough and won't ever happen otherwise I could
> maybe give it a shot, at some point...
> 
> ---
> 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/Dessyreqt/alttprandomizer/issues/57#issuecomment-237694483

## 

Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by meriwinkle** [comment]
Well. Shit.

Thanks anyway fellas. Best of luck with the rest.

**Comment by KatDevsGames** [comment]
Sorry I couldn't give better news. Unfortunately, the goals of randomizer are focused primarily on gameplay. Hope you still enjoy randomizer both now and in future revisions.
