### ISSUE TITLE
[V5] Potential Bad Seed

### ISSUE THREAD

**Issue by draguscloud** [Dessyreqt/alttprandomizer#58]
[ALttP Random - C1525995.sfc.spoilers.txt](https://github.com/Dessyreqt/alttprandomizer/files/400443/ALttP.Random.-.C1525995.sfc.spoilers.txt)
Unable to progress in seed. Progress is blocked by lack of power gloves and I have no other means to progress.

**Comment by KatDevsGames** [comment]
This seed appears solvable. Cape can be used to enter agahnim's tower, then player can proceed to broken bridge, jump in river, go up one screen to dock, South to the gap on the river wall, hookshot accross, walk to kakariko, proceed South, jump down behind arrow game house, walk around to Lake Hylia, jump in, and mirror to obtain Titan's mitts.

On August 3, 2016 6:56:41 PM EDT, Daniel Parker notifications@github.com wrote:

> [ALttP Random -
> C1525995.sfc.spoilers.txt](https://github.com/Dessyreqt/alttprandomizer/files/400443/ALttP.Random.-.C1525995.sfc.spoilers.txt)
> Unable to progress in seed. Progress is blocked by lack of power gloves
> and I have no other means to progress.
> 
> ---
> 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/Dessyreqt/alttprandomizer/issues/58

## 

Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by draguscloud** [comment]
How do I get to the cape (aka get on death mountain)?

**Comment by KatDevsGames** [comment]
Missed where the cape was. May actually be an invalid seed. Having someone verify.

On August 3, 2016 7:38:03 PM EDT, Daniel Parker notifications@github.com wrote:

> How do I get to the cape (aka get on death mountain)?
> 
> ---
> 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/Dessyreqt/alttprandomizer/issues/58#issuecomment-237408200

## 

Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by KatDevsGames** [comment]
Disregard other suggestion. Player can whirlpool from Lake Hylia below big Island to Zora river. Seed is solvable.

On August 3, 2016 7:38:03 PM EDT, Daniel Parker notifications@github.com wrote:

> How do I get to the cape (aka get on death mountain)?
> 
> ---
> 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/Dessyreqt/alttprandomizer/issues/58#issuecomment-237408200

## 

Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by draguscloud** [comment]
Thanks. I figured there was something I missed.
