### ISSUE TITLE
Mirror shield downgrade

### ISSUE THREAD

**Issue by darkmagician1184** [Dessyreqt/alttprandomizer#6]
Seed: c1301360

got the mirror shield (lvl3 shield) in first chest.  when got sword/shield from uncle, it downgraded to fighter shield (lvl1) but sprite doesn't reflect this until save+quit.

see image:
https://i.imgur.com/OK2NW6D.jpg

**Comment by Dessyreqt** [comment]
This and the Power Glove should no longer appear in the Link's House
