### ISSUE TITLE
Unable to progress (softlock?)

### ISSUE THREAD

**Issue by Hillshum** [Dessyreqt/alttprandomizer#63]
I'm not sure if this is an issue with the randomizer or if I'm just missing something gameplay-wise, so please correct me if needed.

I'm using seed C2902694, and, if my assumptions are correct, then I need to get the second pendant, which requires the Book of Mudora, which can be found where http://www.zeldadungeon.net/Zelda03-a-link-to-the-past-heart-pieces.php piece 23 is. Getting that requires the Moon Perl (to lift the big rock) which is piece 16 according to that same page. Getting that one requires defeating Agahnim the first time, which I can't do because I don't have all three pendants...

Again, if this is the wrong place for this submission, please let me know.

**Comment by churine** [comment]
You can enter Desert Palace from the Swamp of Evil, using the Mirror. This does not require the Moon Pearl.

**Comment by KatDevsGames** [comment]
Consider the following route:

0: Obtain Pegasus boots & Fire rod in escape and bow from chicken lady's 
house

1: Obtain Titan's Mitt from Sahasrala's hut rear room center chest

2: Obtain Hammer from Eastern Palace big chest

2a: Do eastern and this point if you want to save time on routing, 
obtaining pendant #1

3: Ascend death mountain and obtain Mirror from old man

4: Proceed to warp point near spectacle rock & mirror back to proceed to 
tower of hera

4a: Do hera at this point if you want to save time on routing, obtaining 
pendant #3

5: Go east past the hammer pegs

6: Obtain Flute in cave complex

7: Proceed to kakariko to activate flute

8: Flute to location #6

9: Lift right dark rock and enter warp to swamp of evil (misery mire)

10: Walk north from current location until the cliff juts westward

11: Stand in the gap made by the westward jut and mirror

12: Appear on upper ledge and proceed to desert 2nd segment

13: Defeat lanmolas and obtain pendant #2

14: Collect master sword & proceed to agahnim's tower

15: Defeat agahnim 1

16: Proceed to lumberjack tree and collect moon pearl

Let me know if any of these steps are unclear or if you think I made an 
error in routing.

**Comment by Hillshum** [comment]
I looked though the source code and found the location dependencies and pieced that out. I'm in the process of finding the Ocarina. It all sounds feasible.

As a side note, randomized items really stretches my knowledge of the game, and I love it!
