### ISSUE TITLE
[v5] Desert Palace Logic Update

### ISSUE THREAD

**Issue by Dessyreqt** [Dessyreqt/alttprandomizer#64]
[v5]

Just played a seed where Moon Pearl was in compass room of Desert and boots were in chest game in Dark World. The only way to proceed was to use the Desert Palace part 2 key to get to Moon Pearl. This is fine in itself. However some people chose to use the key to defeat Lanmolas' and then those people were stuck. They planned to get Master Sword to check Ether tablet. It's a pure 50/50 scenario.

Solution: Add a function  "if desert part 2 key is required to get an item in part 1, then that item can't be required in order to get boots"

This was an oversight on my part

**Comment by ChristosOwen** [comment]
This can be closed :)
