### ISSUE TITLE
Unbeatable seed? - C0000055

### ISSUE THREAD

**Issue by ghost** [Dessyreqt/alttprandomizer#65]
(Maze Race) Titan's Mitt <requires>
[cave-057-1F] Dark World Death Mountain - cave from top to bottom [bottom chest] Pegasus Boots <requires> mirror?
[cave-018] Graveyard - top right grave Magic Mirror requires Titan Mitts...

http://pastebin.com/L8R9U5fu

[dungeon-C-B1] Escape - final basement room [right chest].................................Bombos
No bombs by that point to open wall

**Comment by KatDevsGames** [comment]
I'm not seeing what the problem is here. Maze race can be completed in 8s without boots.

On August 5, 2016 1:02:08 AM EDT, Halvaard notifications@github.com wrote:

> (Maze Race) Titan's Mitt <requires>
> [cave-057-1F] Dark World Death Mountain - cave from top to bottom
> [bottom chest] Pegasus Boots <requires> mirror?
> [cave-018] Graveyard - top right grave Magic Mirror requires Titan
> Mitts...
> 
> http://pastebin.com/L8R9U5fu
> 
> ---
> 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/Dessyreqt/alttprandomizer/issues/65

## 

Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by ghost** [comment]
Ok, I was under the impression that the boots were needed. OOPS!
