### ISSUE TITLE
[v5] Desert Palace Logic Update 2

### ISSUE THREAD

**Issue by Dessyreqt** [Dessyreqt/alttprandomizer#66]
Submitter: ChristosOwen
Email: ChristosOwen@hotmail.co.uk
[v5]

Ignore previous message. I've thought more about it.

If you don't have boots it's always a 50/50 and you don't know the correct answer. Even if the logic states the item in compass/big key room doesn't require boots, then that means by definition that boots are readily available and you could therefore find them and get torch key instead. So it makes using part 2 key in part 1 redunant entirely. 

Solution:
1. Remove CanGetDesertKey function entirely.
2. Update Compass/Big Key Chests to CanEnterDesertPalace(have) && have.Contains(ItemType.PegasusBoots)
3. Update Big Chest to CanEnterDesertPalace(have) && (PegasusBoots || (LocationHasItem("[dungeon-L2-B1] Desert Palace - Map room", ItemType.BigKey))
4. CanEnterDesertPalace, CanEnterDesertPalace2 and CanDefeatDesertPalace are all fine. As is the Map Chest.

**Comment by ChristosOwen** [comment]
***Even if the logic states that the item in compass/big key room isn't required to get boots....

**Comment by Dessyreqt** [comment]
Implemented except the big chest stuff, which will be pushed to v7. Handled in design docs.
