### ISSUE TITLE
Picking up Mushroom Didn't Activate Switch Option

### ISSUE THREAD

**Issue by BlueViper85** [Dessyreqt/alttprandomizer#68]
Picking up the mushroom after having the powder didn't seem to activate the ability to switch between Powder and Mushroom.  Flippers were with the Witch/Potion Shop so the sead was technically not beatable.

Zarby tested this with some chests and it seemed OK, so this may just relate to the mushroom being picked up from the digging game. Zarby is testing that, so I'll update this once that's known. *\* Zarby didn't have any problems.  This may be emulator specific, as it was done on ZSNES.  I'm testing as a third option using the same order followed when it originally occurred.

Seed: C3011001
Video of the pick up, and showing the lack of the ability to switch when Powder is selected: https://www.twitch.tv/inthenameofdt/v/81845797?t=48m41s

Video showing explicitly the inability to switch, since the other video glosses over it: https://www.twitch.tv/inthenameofdt/v/81845797?t=02h13m30s

**Comment by KatDevsGames** [comment]
Did your route involve ANY dicking around at a fairy fountain?

**Comment by BlueViper85** [comment]
After following the original VoD explicitly along the way he did stop in the Fairy Fountain (using Fake Flippers no less) and tossed in the shadow pendant/menu object.  Once the fairy fountain issue is fixed this will be resolved.

As a side note, I went and picked up the mushroom before going up to the fairy fountain and the pendant/object were no longer tossable.  I had the shovel in my inventory, but no flute.

I'll leave this open, but if you see fit to close this, please feel free.

**Comment by KatDevsGames** [comment]
This is a fairy fountain glitch (#56 I believe?). Any side issues need their own bug entry if they're relevant.

**Comment by KatDevsGames** [comment]
Actually was #62.
