### ISSUE TITLE
[v5] No Bow C6013115

### ISSUE THREAD

**Issue by Dessyreqt** [Dessyreqt/alttprandomizer#69]
Submitter: Jack
Email: jacksonreinmuth@gmail.com
[v5]

I can't pass the first 3 dungeons because I don't have the book of mudora, bow, or power glove. I can only enter the first and make it until the red cyclops that opens the door when killed. Running around Hyrule gets me nowhere without the power glove since I can't go to the Desert Palace or Tower of Hera, the Zora's domain, waterfall of wishing, etc. and I've already found all of the chests (that I know of) . Maybe create a system that puts necessary items in the dungeon they are supposed to be in, but also a random chest or a place in Hyrule that can be reached at any time.

**Comment by KatDevsGames** [comment]
Without a seed number, this report isn't helpful.

**Comment by Dessyreqt** [comment]
Seed is C6013115 as listed in the title

**Comment by BlueViper85** [comment]
Bow is accessible in this seed, and the items to obtain them are accessible.  To avoid significant spoilers, obtaining the bow requires finding other items all of which are accessible after rescuing Zelda.  Specific spoilers can be included if requested.

**Comment by BlueViper85** [comment]
Reviewing the spoiler log further, the bow for this seed is accessible; however, it is a difficult find.  This one requires finding a few specific items in light world and then using a trick known as Super Bunny to get the Moon Pearl.  This trick requires falling down a hole as the bunny in Dark World.  In this case, this has to be done in the cave on the bottom of the west-side of Death Mountain in the dark world.

Specifically this cave: http://ian-albert.com/games/legend_of_zelda_a_link_to_the_past_maps/cave-057-1F.png

So while this seems to be a beatable seed, it is a difficult one.

**Comment by ChristosOwen** [comment]
The logic requiring knowledge of this super bunny 'glitch' will not be in future versions, so this situation should not arise again. This is beatable.
