### ISSUE TITLE
got 2 lanterns

### ISSUE THREAD

**Issue by darkmagician1184** [Dessyreqt/alttprandomizer#7]
Got a lantern in the escape and then the fisherman under the bridge also gave me a lantern.

seed: c9869664

**Comment by zilarch** [comment]
Similar issue: Got Quake from the ocarina boy, then got a repeat Quake from the catfish

C2499185

**Comment by churine** [comment]
got the kakariko scammer to sell me a second lantern for 100 rupees (original in castle secret entrance)

seed: C3415117

**Comment by Dessyreqt** [comment]
This is addressed in v4

**Comment by Dessyreqt** [comment]
This is not been fixed as previously expected. Reopening.

**Comment by Dessyreqt** [comment]
There is now only one lamp in the item pool.
