### ISSUE TITLE
Potentially Impossible Run

### ISSUE THREAD

**Issue by fillerbunny9** [Dessyreqt/alttprandomizer#70]
This item loadout appears to make the game impossible to complete. by having the location of both the Power Glove and Titans Mitt in the dark world (amusingly, in the same cave!) I believe that they are impossible to obtain, as you cannot reach this area of the dark world without at least one of them. 

[ALttP Random - unbeatable.sfc.spoilers.txt](https://github.com/Dessyreqt/alttprandomizer/files/404874/ALttP.Random.-.unbeatable.sfc.spoilers.txt)

**Comment by Jaylow7** [comment]
Looking at the spoiler file, I believe this is technically beatable? The solution I think I see would involve killing agahnim 1 (using cape to bypass the barrier) and using the whirlpool warps (after grabbing flippers out of dark palace) to access that section of the dark world without needing hammer and power glove to use the warp south of link's house.

Someone that knows the game better than I do can feel free to correct if I'm wrong.

**Comment by KatDevsGames** [comment]
I don't see a problem here. You can jump into the river right above the broken bridge, climb the dock and go back down to the broken bridge from the top. Hookshot accross the gap, walk the long way around and get the mitts. Seed is solvable.

On August 6, 2016 12:09:34 AM EDT, fillerbunny9 notifications@github.com wrote:

> This item loadout appears to make the game impossible to complete. by
> having the location of both the Power Glove and Titans Mitt in the dark
> world (amusingly, in the same cave!) I believe that they are impossible
> to obtain, as you cannot reach this area of the dark world without at
> least one of them. 
> 
> [ALttP Random -
> unbeatable.sfc.spoilers.txt](https://github.com/Dessyreqt/alttprandomizer/files/404874/ALttP.Random.-.unbeatable.sfc.spoilers.txt)
> 
> ---
> 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/Dessyreqt/alttprandomizer/issues/70

## 

Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by ChristosOwen** [comment]
Agreed, this is beatable.
