### ISSUE TITLE
[v5] Unbeatable Seed: C3753166

### ISSUE THREAD

**Issue by Dessyreqt** [Dessyreqt/alttprandomizer#71]
Submitter: MindWanderer
Email: MindWanderer@juno.com
[v5]

Seed C3753166 is unbeatable as far as I can tell.  The Moon Pearl is in the Desert Palace (need Book of Mudora or Magic Mirror to reach).  The Magic Mirror is in the Lumberjack Tree (which you can enter only after beating Aghanim 1, and thus all three medallions). The Book of Mudora is outside the Dark World Pyramid, which seems reachable because you can get the Titan's Mitt, but you can't leave the area around any of the portals you can access without being able to use your sword at least.

The hammer is also unattainable (needs Magic Mirror at least), but I don't think it would help anyway, same problem as the Titan's Mitt.  You also can't reach the Tower of Hera (need Magic Mirror or Hookshot and Hammer), but that doesn't help since you can't reach the Desert Palace either.

Also, a bug: It looks like if you trigger the new rule that shows your crystal progress when you're in the Dark World, in the Light World it then shows you've collected no medallions (both on the submenu and on the map).  Obviously I can't check this time around to see if that prevents you from getting the Master Sword....

**Comment by KatDevsGames** [comment]
Where is the cape? (I can't check the seed on mobile.)

On August 6, 2016 1:49:27 AM EDT, David Carroll notifications@github.com wrote:

> Submitter: MindWanderer
> Email: MindWanderer@juno.com
> [v5]
> 
> Seed C3753166 is unbeatable as far as I can tell.  The Moon Pearl is in
> the Desert Palace (need Book of Mudora or Magic Mirror to reach).  The
> Magic Mirror is in the Lumberjack Tree (which you can enter only after
> beating Aghanim 1, and thus all three medallions). The Book of Mudora
> is outside the Dark World Pyramid, which seems reachable because you
> can get the Titan's Mitt, but you can't leave the area around any of
> the portals you can access without being able to use your sword at
> least.
> 
> The hammer is also unattainable (needs Magic Mirror at least), but I
> don't think it would help anyway, same problem as the Titan's Mitt. 
> You also can't reach the Tower of Hera (need Magic Mirror or Hookshot
> and Hammer), but that doesn't help since you can't reach the Desert
> Palace either.
> 
> Also, a bug: It looks like if you trigger the new rule that shows your
> crystal progress when you're in the Dark World, in the Light World it
> then shows you've collected no medallions (both on the submenu and on
> the map).  Obviously I can't check this time around to see if that
> prevents you from getting the Master Sword....
> 
> ---
> 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/Dessyreqt/alttprandomizer/issues/71

## 

Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by BlueViper85** [comment]
The cape is available in Kakariko village, which can then be used to get past the barrier to Agahnim's Tower and beat him gaining one portal to the Dark World.  Pegasus Boots are in the same place, giving access to the tree in the Light World.

**Comment by ChristosOwen** [comment]
Agreed, this is beatable.
