### ISSUE TITLE
Don't pick up the Shovel...

### ISSUE THREAD

**Issue by Joki81** [Dessyreqt/alttprandomizer#72]
If you already have the Flute!

Seed: C7010288

Hard Lock preventing you from entering the dark world if you get the shovel after the flute. Potential for more trouble in the flowerbed where you dig up the flute in the regular game.

**Comment by ChristosOwen** [comment]
You can toggle between shovel/flute, boomerang/red boomerang and mushroom/powder by pressing Y in the menu. This also works for bottles (notice the bottles no longer auto open). It doesn't matter which order you obtain the items. Notice also the small circle icon attached to these item slots.

We will make it more obvious this feature has been added on the Github download page.

**Comment by KatDevsGames** [comment]
User failed to read documentation, not a bug.
