### ISSUE TITLE
Unbeatable seed C0191864

### ISSUE THREAD

**Issue by terrorcide** [Dessyreqt/alttprandomizer#73]
I think this may be unbeatable - I need to get either the titan's mitts or the power glove to proceed.

The power glove you need lifting to access Zora's River - so that only leaves the Mitts which are in the Dungeon C B1 escape room - which I didn't have Pegasus Boots / bombs to get the first time through.

I can't re-enter this area as I don't have heavy lifting to get access to the left grave.

Let me know if I've missed something - thanks.
## Generated Item Order

[cave-022-B1] Thief's hut [top right chest]...............................................Book of Mudora
[cave-022-B1] Thief's hut [bottom right chest]............................................Pegasus Boots
[cave-040] Link's House...................................................................Shovel
[cave-050] cave southwest of Lake Hylia [top right chest].................................Flippers
Piece of Heart (Zora's River).............................................................Power Glove
Piece of Heart (Spectacle Rock Cave)......................................................Bottle
King Zora.................................................................................Hookshot
[dungeon-C-B1] Escape - final basement room [right chest].................................Titan's Mitt
[cave-044] Aginah's cave..................................................................Bow
[cave-021] Kakariko well [bottom chest]...................................................Moon Pearl
[cave-062] C-shaped house.................................................................Magic Mirror
Old mountain man..........................................................................Bombos
Piece of Heart (Death Mountain - floating island).........................................Lamp
[cave-009-1F] Death Mountain - wall of caves - right cave [bottom chest]..................Hammer
[cave-018] Graveyard - top right grave....................................................Cape
[dungeon-D2-B1] Swamp Palace - big key room...............................................Fire Rod
Bombos....................................................................................Ether
Piece of Heart (Dark World blacksmith pegs)...............................................Mushroom
[dungeon-L3-2F] Tower of Hera - Entrance..................................................Ocarina
Piece of Heart (Graveyard)................................................................Cane of Somaria
Piece of Heart (Digging Game).............................................................Ice Rod

**Comment by ChristosOwen** [comment]
You can reach Zora's River using the whirpool just below the Wishing Well Faerie in Lake Hylia. Flippers are are obtainable in the cave southwest of Lake Hylia.

Everything else is obtainable thereafter. This seed is beatable.
