### ISSUE TITLE
[v5] Softlock 

### ISSUE THREAD

**Issue by Dessyreqt** [Dessyreqt/alttprandomizer#74]
Submitter: Aweglib
Email: aweglib@gmail.com
[v5]

C0316124 is the seed. I looked at the spoiler after being stuck without boots or moon pearl. Looking at the spoiler, the moon pearl is the lumberjack heart, which you need boots for. Likewise, the boots are in a dark world chest, which you need moon pearl for.

I'm not super familiar with all the tricks in this game so there might be something I'm missing, but I think I'm softlocked.

Thanks for looking into it,

Aweglib

**Comment by KatDevsGames** [comment]
Chests in the drop cave can be opened even with bunny link. The drops 
activate the superbunny state which can perform enough actions to obtain 
the items. This type of placement is being removed for casual seeds and 
will only be available in speedrunner seeds in later releases.
