### ISSUE TITLE
[v5] C2873016 Uncompletable seed

### ISSUE THREAD

**Issue by Dessyreqt** [Dessyreqt/alttprandomizer#76]
Submitter: Brad
Email: bam_321@hotmail.com
[v5]

The Pearl is in a location that requires the Mirror, and the Mirror is in a location that also seems to require the Mirror and possibly the Pearl.

The relevant spoiler lines:
[cave-057-1F] Dark World Death Mountain - cave from top to bottom [top chest].............Magic Mirror
Piece of Heart (Desert - northeast corner)................................................Moon Pearl

**Comment by KatDevsGames** [comment]
## The magic mirror can be obtained from those chests. Bunny link CAN open the chests in the drop cave. This fact is apparently obscure enough that we plan to remove it in future releases. That being said, the seed is quite solvable.

Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by KatDevsGames** [comment]
Closed / not a bug
