### ISSUE TITLE
 Arrows don't show the silver arrows

### ISSUE THREAD

**Issue by BlueViper85** [Dessyreqt/alttprandomizer#79]
The arrows in the in-game HUD don't reflect the Silver Arrows after they are being obtained. This seems to date back to at least v4.  I saved an SRM of this if needed. Here's a video from when I got the GS/SA in a V4 run and the HUD didn't update: https://www.twitch.tv/blueviper85/v/80387503?t=02h40m59s, but it just happened to me offline with v5 (i.e. no recording)

![2016-08-07 5](https://cloud.githubusercontent.com/assets/12190332/17464781/5422da40-5cac-11e6-9231-2596f6f8d1f2.png)

![2016-08-07 6](https://cloud.githubusercontent.com/assets/12190332/17464782/55c5f026-5cac-11e6-8f3f-49a504573244.png)

Picture of what it should look like for reference:

![silverarrowshud](https://cloud.githubusercontent.com/assets/12190332/17464835/bd09a2c2-5cad-11e6-8030-63b39d136116.PNG)

**Comment by churine** [comment]
It does, but it uses the wrong palette. The wooden arrows palette has the opposite colors (brown with grey fletching).
You can see the difference by watching the hud when getting/dropping them at the fountain.

![alttp random - c7314108000](https://cloud.githubusercontent.com/assets/19752470/17465503/1bdfa620-5cf9-11e6-9041-b8ac3204dd4f.png) ![alttp random - c7314108001](https://cloud.githubusercontent.com/assets/19752470/17465504/1bebfd76-5cf9-11e6-8846-63b29edbd68e.png)
(ignore the bszelda sprite)

as a blind guess, the part updating the palette to the white and red one may be targeting the old position of the arrows in the hud?

**Comment by ChristosOwen** [comment]
We're aware of this and it will be fixed in a future release.

**Comment by KatDevsGames** [comment]
Fixed in trunk rom.
