### ISSUE TITLE
[Very minor] Items in the mushroom location are not covered by the mist

### ISSUE THREAD

**Issue by BlueViper85** [Dessyreqt/alttprandomizer#80]
Items that are in the mushroom location in Light World Lost Woods look as though they are on top of the mist, as opposed to being covered by the mist.  Nothing is really broken by this except that the items look a little out of place.

This happens with heart pieces and bombs that I've definitely seen so far.  Screenshot is attached showing the bombs.

![lostwoodsmist](https://cloud.githubusercontent.com/assets/12190332/17464902/d7fdd390-5cae-11e6-87ec-476703ac6f8d.PNG)

**Comment by KatDevsGames** [comment]
Problem appears related to low palette ids (in this case most primarily red or blue items) not being subject to pixel math. Inherent to SNES design. Cannot be fixed without major engine rewrite.
