### ISSUE TITLE
Master Sword overwrote forged sword.

### ISSUE THREAD

**Issue by Omio** [Dessyreqt/alttprandomizer#81]
Seed replicated in: C2168912
I managed to get the tempered sword early, and then when I went to get the Master Sword, I lost the tempered sword. D:

Is this a potential soft-lock, or just a bug?

**Comment by KatDevsGames** [comment]
It's not a potential softlock necessarily.

1: There's a good chance that you can go back and get the sword retempered.
2: It's actually possible to defeat Ganon with just the master sword (24 spins per phase!).

That being said, this IS a bug and will be resolved for v6.

**Comment by churine** [comment]
You can _always_ temper the Master Sword or lower to get the Tempered Sword again.

I'm not sure I'd fix the oversight, it's very simple in the normal game and a lot of routing depends on tempering L1 to L3

**Comment by KatDevsGames** [comment]
Too late. Fixed in trunk rom already. I code fast.
