### ISSUE TITLE
[v5] Completely dark rooms

### ISSUE THREAD

**Issue by Dessyreqt** [Dessyreqt/alttprandomizer#84]
Submitter: MasterForce
Email: rafinha_flamenguista@hotmail.com
[v5]

Playing through seed  C8646013, I ran into a pretty heavy bug. 
In the Palace of Darkness and Misery Mire the dark rooms were COMPLETELY dark, meaning that Link didn't have that small ''flashlight'' effect in front of him, that makes those rooms pretty much impossible to navigate through.
It was working just fine until I got to the dark rooms of the the two dungeons mentioned above.

**Comment by greenham** [comment]
As far as I can tell, the Lamp is accessible in this seed before you would have to do either Palace of Darkness or Misery Mire. Once you get the Lamp, you'll have the "flashlight" effect for the dark rooms in the Dark World.

It's true that you have the flashlight effect in Light World regardless of if you have the Lamp or not, but this is only true in Light World, not Dark.

**Comment by ghost** [comment]
Thank you for the reply.
I was doing Misery Mire early cause I figured: ''I have the needed items to get through this dungeon and the Ice Palace, might as well do them right now so I can get the Golden Sword and Silver Arrows right away.'' but I didn't know about this Lamp thing.

I gonna go look for the Lamp then it has to be in one of the dungeons in the Dark World cause I think I cleared pretty much the entire map Light and Dark of its items.

**Comment by ChristosOwen** [comment]
Yeah, no dark navigation is required in the randomizer logic. Lamp should always be accessible without.

**Comment by KatDevsGames** [comment]
Not a bug.
