### ISSUE TITLE
[v5] Sword Downgrade

### ISSUE THREAD

**Issue by Dessyreqt** [Dessyreqt/alttprandomizer#86]
Submitter: Andrew Shutt
Email: ashutt92@yahoo.com
Not sure if this is something that needs to be addressed, but the sword gets downgraded if you obtain the Sword lv2, after getting Sword lv3 early. You can get it re tempered back to lv3 again, but I just thought say something. Really enjoying it! I'm on my 4th seed bug hunting.

**Comment by KatDevsGames** [comment]
Already fixed in trunk rom.
