### ISSUE TITLE
Odd alterations to the game

### ISSUE THREAD

**Issue by simplyorange** [Dessyreqt/alttprandomizer#87]
I hate to complain, but I felt my previous comment was rudely closed.

I feel we've reached a point where this project is turning such that this is no longer ALTTP anymore, but rather a specific mod with a specific mindset.

As I said before RNG should be in and I really question changes such as these:
(v6 changes)
The old man on Death Mountain also refills your magic.
The 3 pots in Link’s house have been changed from hearts to a full magic jar and 2 faeries.

There are plenty of places to find magic refills...it is incredibly skillful to know how to get them most efficiently.  Why are you editing the game in this way?

**Comment by KatDevsGames** [comment]
You will not get your way. If that is an issue, fork the project.

Not a bug/won't fix.
