### ISSUE TITLE
Unbeatable: [v6] C2474410 - can not get Bow

### ISSUE THREAD

**Issue by JingerTV** [Dessyreqt/alttprandomizer#90]
You get in PoD the big key in the first chest, than you need a small or the Bow to adavnce further in PoD

[dungeon-D1-B1] Dark Palace - shooter room................................................Big Key
[dungeon-D1-1F] Dark Palace - spike statue room...........................................Bow

**Comment by greenham** [comment]
This looks to be similar to the logic issue in #88.

**Comment by ChristosOwen** [comment]
Indeed. This is a duplicate of error logic as #88. My resolution is proposed in there so closing this one.
