### ISSUE TITLE
Seed C5865322 Unbeatable?

### ISSUE THREAD

**Issue by NagolStrache** [Dessyreqt/alttprandomizer#91]
The sick kid has the Titan's Mitt, but won't give them to the player. I figured that I might need the Power Glove for some reason, but it is located at Lake Hylia where the heart container used to be. Getting the flippers and magic mirror isn't an issue, what is an issue is that the moon pearl is stuck under the gravestone that requires the Titan's Mitt. Thus creating the scenario where you need the power glove to get the titan's mitt, which requires the moon pearl, which requires the titan's mitt. Since rabbit link can't swim this seed seems to be unbeatable, unless there is something I missed.

[ALttP Random - C5865322.sfc.spoilers.txt](https://github.com/Dessyreqt/alttprandomizer/files/419615/ALttP.Random.-.C5865322.sfc.spoilers.txt)

**Comment by Dessyreqt** [comment]
The sick kid requires you to have a bottle in your inventory.

**Comment by NagolStrache** [comment]
Thanks! I don't think I've ever actually seen the dialogue telling you to get a bottle in the normal game, so that's probably why this flew over my head.

**Comment by KatDevsGames** [comment]
Not a bug.
