### ISSUE TITLE
[v6] Fake Flippers Issue

### ISSUE THREAD

**Issue by It-s-Me** [Dessyreqt/alttprandomizer#92]
After doing the fake flippers glitch and then returning to dry land, you can instantly die if you take damage while jumping back into the water.  This condition persists after a save and quit as well.

This happened to me when I used the fake flippers to reach Zora's Waterfall.  While there, no longer using the fake flippers, I fell into the water on an enemy and instantly died.  I had a fairy in a bottle that was ignored.  I also tried using the fake flippers, saved and quit, then walked to Zora's Waterfall and died the same way. 

I assume this is related to the fake flippers softlock fix.

**Comment by It-s-Me** [comment]
Attached video

[fake_flippers.zip](https://github.com/Dessyreqt/alttprandomizer/files/423851/fake_flippers.zip)

**Comment by ChristosOwen** [comment]
Looks like you're right and this is related the the softlock fix. Personally since the logic does not align with the use of fake flippers, I believe races/playthroughs of this should be encouraged to not use fake flippers at all. If we go down this route, we should revert fake flippers behaviour back to default and remove the fix.

**Comment by KatDevsGames** [comment]
What's the decision on this? It could be fixed but do we want the ff softlock back in glitched randomizer or not? (It's already fixed but I could just take the whole thing out.)

**Comment by BlueViper85** [comment]
I, personally, am all for leaving the fix in, I don't see any harm in insta-killing instead of soft lock. But I don't know if that impacts the Glitched version at all.

**Comment by ChristosOwen** [comment]
I think we should fix the fix, so insta-dying works as originally intended to prevent softlocks (without removing faeries from bottles if possible). This doesn't affect glitched rando luckily!

**Comment by ChristosOwen** [comment]
This had been addressed and will be working correctly in v7.
