### ISSUE TITLE
[v6] Item Misplacement

### ISSUE THREAD

**Issue by Dessyreqt** [Dessyreqt/alttprandomizer#94]
Submitter: Seraphin
Email: seraphineveles@yahoo.com
Seed: C9645339
Per the spoiler log attached to the end, several items are not in the listed locations. Notably the Bow and Titan's Mitt, thus making the game impossible (as far as ive been able to tell so far, after several hours.)
## A Link to the Past Randomizer Log

Version: 6
Creation Date: 8/19/2016 2:26:10 AM
Seed: C9645339
## Generated Item Order

[dungeon-C-B1] Hyrule Castle - boomerang room.............................................Cape
Mushroom..................................................................................Moon Pearl
[cave-050] cave southwest of Lake Hylia [bottom left chest]...............................Bow
[cave-022-B1] Thief's hut [top left chest]................................................Mushroom
[cave-022-B1] Thief's hut [top chest].....................................................Ocarina
[dungeon-D1-1F] Dark Palace - compass room................................................Hammer
[cave-021] Kakariko well [bottom chest]...................................................Power Glove
Piece of Heart (Dark World - bumper cave).................................................Flippers
Sahasrahla................................................................................Bottle (Blue Potion)
[cave-021] Kakariko well [right chest row of 3]...........................................Hookshot
[cave-073] cave northeast of swamp palace [bottom middle chest]...........................Pegasus Boots
Piece of Heart (Dam)......................................................................Lamp
Catfish...................................................................................Magic Mirror
Sick Kid..................................................................................Titan's Mitt
[dungeon-D2-B2] Swamp Palace - flooded room [right chest].................................Bombos
[cave-071] Misery Mire west area [left chest].............................................Shovel
Piece of Heart (Dark World blacksmith pegs)...............................................Book of Mudora
[dungeon-D3-B1] Skull Woods - east of Fire Rod room.......................................Quake
[dungeon-D2-B2] Swamp Palace - hidden waterfall door room.................................Cane of Somaria
[dungeon-D5-B5] Ice Palace - b5 up staircase..............................................Fire Rod
[dungeon-C-B1] Hyrule Castle - map room...................................................Ice Rod
## Light World

[cave-009-1F] Death Mountain - wall of caves - right cave [bottom chest]..................Staff of Byrna
[cave-009-1F] Death Mountain - wall of caves - right cave [top left chest]................Bottle (Bee)
[cave-009-1F] Death Mountain - wall of caves - right cave [top left middle chest].........Piece of Heart
[cave-009-1F] Death Mountain - wall of caves - right cave [top right chest]...............3 Bombs
[cave-009-1F] Death Mountain - wall of caves - right cave [top right middle chest]........3 Bombs
[cave-009-B1] Death Mountain - wall of caves - right cave [left chest]....................20 Rupees
[cave-009-B1] Death Mountain - wall of caves - right cave [right chest]...................20 Rupees
[cave-012-1F] Death Mountain - wall of caves - left cave..................................Boomerang
[cave-013] Mimic cave (from Turtle Rock)..................................................3 Bombs
[cave-016] cave under rocks west of Santuary..............................................20 Rupees
[cave-018] Graveyard - top right grave....................................................100 Rupees
[cave-021] Kakariko well [bottom chest]...................................................Power Glove
[cave-021] Kakariko well [center chest row of 3]..........................................3 Bombs
[cave-021] Kakariko well [left chest row of 3]............................................20 Rupees
[cave-021] Kakariko well [right chest row of 3]...........................................Hookshot
[cave-021] Kakariko well [top chest]......................................................300 Rupees
[cave-022-B1] Thief's hut [bottom left chest].............................................3 Bombs
[cave-022-B1] Thief's hut [bottom right chest]............................................3 Bombs
[cave-022-B1] Thief's hut [top chest].....................................................Ocarina
[cave-022-B1] Thief's hut [top left chest]................................................Mushroom
[cave-022-B1] Thief's hut [top right chest]...............................................Piece of Heart
[cave-026] chicken house..................................................................Piece of Heart
[cave-031] Tavern.........................................................................Piece of Heart
[cave-034] Hyrule Castle secret entrance..................................................50 Rupees
[cave-035] Sahasrahla's Hut [center chest]................................................10 Arrows
[cave-035] Sahasrahla's Hut [left chest]..................................................Red Boomerang
[cave-035] Sahasrahla's Hut [right chest].................................................3 Bombs
[cave-040] Link's House...................................................................100 Rupees
[cave-044] Aginah's cave..................................................................Piece of Heart
[cave-047] Dam............................................................................20 Rupees
[cave-050] cave southwest of Lake Hylia - generous guy....................................Bottle (Bee)
[cave-050] cave southwest of Lake Hylia [bottom left chest]...............................Bow
[cave-050] cave southwest of Lake Hylia [bottom right chest]..............................20 Rupees
[cave-050] cave southwest of Lake Hylia [top left chest]..................................20 Rupees
[cave-050] cave southwest of Lake Hylia [top right chest].................................20 Rupees
[cave-051] Ice Cave.......................................................................100 Rupees
Bombos....................................................................................Piece of Heart
Bottle Vendor.............................................................................Bottle (Red Potion)
Ether.....................................................................................3 Bombs
Haunted Grove item........................................................................100 Rupees
Hobo......................................................................................20 Rupees
King Zora.................................................................................20 Rupees
Library...................................................................................Piece of Heart
Mushroom..................................................................................Moon Pearl
Old mountain man..........................................................................3 Bombs
Piece of Heart (Dam)......................................................................Lamp
Piece of Heart (Death Mountain - floating island).........................................20 Rupees
Piece of Heart (Desert - northeast corner)................................................10 Arrows
Piece of Heart (Desert - west side).......................................................10 Arrows
Piece of Heart (Graveyard)................................................................20 Rupees
Piece of Heart (Lake Hylia)...............................................................10 Arrows
Piece of Heart (Lumberjack Tree)..........................................................100 Rupees
Piece of Heart (Maze Race)................................................................3 Bombs
Piece of Heart (south of Haunted Grove)...................................................Piece of Heart
Piece of Heart (Spectacle Rock Cave)......................................................Piece of Heart
Piece of Heart (Spectacle Rock)...........................................................Piece of Heart
Piece of Heart (Thieves' Forest Hideout)..................................................Piece of Heart
Piece of Heart (Zora's River).............................................................Piece of Heart
Purple Chest..............................................................................Piece of Heart
Sahasrahla................................................................................Bottle (Blue Potion)
Sick Kid..................................................................................Titan's Mitt
Witch.....................................................................................1 Rupee
## Dark World

[cave-055] Spike cave.....................................................................10 Arrows
[cave-056] Dark World Death Mountain - cave under boulder [bottom left chest].............50 Rupees
[cave-056] Dark World Death Mountain - cave under boulder [bottom right chest]............50 Rupees
[cave-056] Dark World Death Mountain - cave under boulder [top left chest]................20 Rupees
[cave-056] Dark World Death Mountain - cave under boulder [top right chest]...............3 Bombs
[cave-057-1F] Dark World Death Mountain - cave from top to bottom [bottom chest]..........3 Bombs
[cave-057-1F] Dark World Death Mountain - cave from top to bottom [top chest].............10 Arrows
[cave-062] C-shaped house.................................................................Heart Container
[cave-063] doorless hut...................................................................Magic Powder
[cave-071] Misery Mire west area [left chest].............................................Shovel
[cave-071] Misery Mire west area [right chest]............................................100 Rupees
[cave-073] cave northeast of swamp palace - generous guy..................................Piece of Heart
[cave-073] cave northeast of swamp palace [bottom chest]..................................20 Rupees
[cave-073] cave northeast of swamp palace [bottom middle chest]...........................Pegasus Boots
[cave-073] cave northeast of swamp palace [top chest].....................................3 Bombs
[cave-073] cave northeast of swamp palace [top middle chest]..............................10 Arrows
Catfish...................................................................................Magic Mirror
Flute Boy.................................................................................Blue Mail
Piece of Heart (Dark World - bumper cave).................................................Flippers
Piece of Heart (Dark World blacksmith pegs)...............................................Book of Mudora
Piece of Heart (Digging Game).............................................................Piece of Heart
Piece of Heart (Pyramid)..................................................................Piece of Heart
Piece of Heart (Treasure Chest Game)......................................................Piece of Heart
## Hyrule Castle Escape

[dungeon-C-1F] Sanctuary..................................................................Piece of Heart
[dungeon-C-B1] Escape - final basement room [left chest]..................................20 Rupees
[dungeon-C-B1] Escape - final basement room [middle chest]................................Piece of Heart
[dungeon-C-B1] Escape - final basement room [right chest].................................Map
[dungeon-C-B1] Escape - first B1 room.....................................................Piece of Heart
[dungeon-C-B1] Hyrule Castle - boomerang room.............................................Cape
[dungeon-C-B1] Hyrule Castle - map room...................................................Ice Rod
[dungeon-C-B3] Hyrule Castle - next to Zelda..............................................Key
## Eastern Palace

[dungeon-L1-1F] Eastern Palace - big ball room............................................Piece of Heart
[dungeon-L1-1F] Eastern Palace - big chest................................................Red Shield
[dungeon-L1-1F] Eastern Palace - Big key..................................................Compass
[dungeon-L1-1F] Eastern Palace - compass room.............................................Map
[dungeon-L1-1F] Eastern Palace - map room.................................................Big Key
## Desert Palace

[dungeon-L2-B1] Desert Palace - big chest.................................................20 Rupees
[dungeon-L2-B1] Desert Palace - Big key room..............................................Map
[dungeon-L2-B1] Desert Palace - compass room..............................................Big Key
[dungeon-L2-B1] Desert Palace - Map room..................................................Compass
## Tower of Hera

[dungeon-L3-1F] Tower of Hera - first floor...............................................Big Key
[dungeon-L3-2F] Tower of Hera - Entrance..................................................Bug-Catching Net
[dungeon-L3-4F] Tower of Hera - 4F [small chest]..........................................Map
[dungeon-L3-4F] Tower of Hera - big chest.................................................Compass
## Hyrule Castle Tower

[dungeon-A1-2F] Hyrule Castle Tower - 2 knife guys room...................................Key
[dungeon-A1-3F] Hyrule Castle Tower - maze room...........................................Key
## Dark Palace

[dungeon-D1-1F] Dark Palace - big chest...................................................3 Bombs
[dungeon-D1-1F] Dark Palace - big key room................................................Key
[dungeon-D1-1F] Dark Palace - compass room................................................Hammer
[dungeon-D1-1F] Dark Palace - jump room [left chest]......................................Key
[dungeon-D1-1F] Dark Palace - jump room [right chest].....................................Key
[dungeon-D1-1F] Dark Palace - maze room [bottom chest]....................................Key
[dungeon-D1-1F] Dark Palace - maze room [top chest].......................................10 Arrows
[dungeon-D1-1F] Dark Palace - spike statue room...........................................Compass
[dungeon-D1-1F] Dark Palace - statue push room............................................Key
[dungeon-D1-B1] Dark Palace - room leading to Helmasaur [left chest]......................Big Key
[dungeon-D1-B1] Dark Palace - room leading to Helmasaur [right chest].....................Map
[dungeon-D1-B1] Dark Palace - shooter room................................................Piece of Heart
[dungeon-D1-B1] Dark Palace - turtle stalfos room.........................................Key
## Swamp Palace

[dungeon-D2-1F] Swamp Palace - first room.................................................Key
[dungeon-D2-B1] Swamp Palace - big chest..................................................Compass
[dungeon-D2-B1] Swamp Palace - big key room...............................................20 Rupees
[dungeon-D2-B1] Swamp Palace - map room...................................................10 Arrows
[dungeon-D2-B1] Swamp Palace - push 4 blocks room.........................................Map
[dungeon-D2-B1] Swamp Palace - south of hookshot room.....................................20 Rupees
[dungeon-D2-B2] Swamp Palace - flooded room [left chest]..................................Big Key
[dungeon-D2-B2] Swamp Palace - flooded room [right chest].................................Bombos
[dungeon-D2-B2] Swamp Palace - hidden waterfall door room.................................Cane of Somaria
## Skull Woods

[dungeon-D3-B1] Skull Woods - big chest...................................................Map
[dungeon-D3-B1] Skull Woods - Big Key room................................................Key
[dungeon-D3-B1] Skull Woods - Compass room................................................Compass
[dungeon-D3-B1] Skull Woods - east of Fire Rod room.......................................Quake
[dungeon-D3-B1] Skull Woods - Entrance to part 2..........................................Big Key
[dungeon-D3-B1] Skull Woods - Gibdo/Stalfos room..........................................Key
[dungeon-D3-B1] Skull Woods - south of Fire Rod room......................................Key
## Thieves Town

[dungeon-D4-1F] Thieves' Town - Room above boss...........................................20 Rupees
[dungeon-D4-B1] Thieves' Town - Bottom left of huge room [bottom right chest].............Key
[dungeon-D4-B1] Thieves' Town - Bottom left of huge room [top left chest].................Big Key
[dungeon-D4-B1] Thieves' Town - Bottom right of huge room.................................20 Rupees
[dungeon-D4-B1] Thieves' Town - Top left of huge room.....................................Piece of Heart
[dungeon-D4-B2] Thieves' Town - big chest.................................................Compass
[dungeon-D4-B2] Thieves' Town - next to Blind.............................................Map
## Ice Palace

[dungeon-D5-B1] Ice Palace - Big Key room.................................................Map
[dungeon-D5-B1] Ice Palace - compass room.................................................Key
[dungeon-D5-B2] Ice Palace - map room.....................................................Big Key
[dungeon-D5-B3] Ice Palace - spike room...................................................Key
[dungeon-D5-B4] Ice Palace - above Blue Mail room.........................................Compass
[dungeon-D5-B5] Ice Palace - b5 up staircase..............................................Fire Rod
[dungeon-D5-B5] Ice Palace - big chest....................................................1 Arrow
## Misery Mire

[dungeon-D6-B1] Misery Mire - big chest...................................................Compass
[dungeon-D6-B1] Misery Mire - big hub room................................................300 Rupees
[dungeon-D6-B1] Misery Mire - big key.....................................................Key
[dungeon-D6-B1] Misery Mire - compass.....................................................Map
[dungeon-D6-B1] Misery Mire - end of bridge...............................................Big Key
[dungeon-D6-B1] Misery Mire - map room....................................................Key
[dungeon-D6-B1] Misery Mire - spike room..................................................Key
## Turtle Rock

[dungeon-D7-1F] Turtle Rock - Chain chomp room............................................Big Key
[dungeon-D7-1F] Turtle Rock - compass room................................................50 Rupees
[dungeon-D7-1F] Turtle Rock - Map room [left chest].......................................Key
[dungeon-D7-1F] Turtle Rock - Map room [right chest]......................................Key
[dungeon-D7-B1] Turtle Rock - big chest...................................................300 Rupees
[dungeon-D7-B1] Turtle Rock - big key room................................................Key
[dungeon-D7-B1] Turtle Rock - Roller switch room..........................................5 Rupees
[dungeon-D7-B2] Turtle Rock - Eye bridge room [bottom left chest].........................Key
[dungeon-D7-B2] Turtle Rock - Eye bridge room [bottom right chest]........................Compass
[dungeon-D7-B2] Turtle Rock - Eye bridge room [top left chest]............................Map
[dungeon-D7-B2] Turtle Rock - Eye bridge room [top right chest]...........................20 Rupees
## Ganon's Tower

[dungeon-A2-1F] Ganon's Tower - above Armos...............................................Red Mail
[dungeon-A2-1F] Ganon's Tower - big chest.................................................1 Rupee
[dungeon-A2-1F] Ganon's Tower - compass room [bottom left chest]..........................Piece of Heart
[dungeon-A2-1F] Ganon's Tower - compass room [bottom right chest].........................Compass
[dungeon-A2-1F] Ganon's Tower - compass room [top left chest].............................50 Rupees
[dungeon-A2-1F] Ganon's Tower - compass room [top right chest]............................5 Rupees
[dungeon-A2-1F] Ganon's Tower - down right staircase from entrance [left chest]...........3 Bombs
[dungeon-A2-1F] Ganon's Tower - down right staircase from entrance [right chest]..........Map
[dungeon-A2-1F] Ganon's Tower - east of down right staircase from entrace.................3 Bombs
[dungeon-A2-1F] Ganon's Tower - map room..................................................300 Rupees
[dungeon-A2-1F] Ganon's Tower - north of gap room [bottom left chest].....................3 Bombs
[dungeon-A2-1F] Ganon's Tower - north of gap room [bottom right chest]....................10 Arrows
[dungeon-A2-1F] Ganon's Tower - north of gap room [top left chest]........................Key
[dungeon-A2-1F] Ganon's Tower - north of gap room [top right chest].......................10 Arrows
[dungeon-A2-1F] Ganon's Tower - north of teleport room....................................Key
[dungeon-A2-1F] Ganon's Tower - west of teleport room [bottom left chest].................20 Rupees
[dungeon-A2-1F] Ganon's Tower - west of teleport room [bottom right chest]................20 Rupees
[dungeon-A2-1F] Ganon's Tower - west of teleport room [top left chest]....................20 Rupees
[dungeon-A2-1F] Ganon's Tower - west of teleport room [top right chest]...................Big Key
[dungeon-A2-6F] Ganon's Tower - before Moldorm............................................Key
[dungeon-A2-6F] Ganon's Tower - Moldorm room..............................................50 Rupees
[dungeon-A2-6F] Ganon's Tower - north of falling floor four torches [top left chest]......Mirror Shield
[dungeon-A2-6F] Ganon's Tower - north of falling floor four torches [top right chest].....Ether
[dungeon-A2-B1] Ganon's Tower - north of Armos room [bottom chest]........................20 Rupees
[dungeon-A2-B1] Ganon's Tower - north of Armos room [left chest]..........................50 Rupees
[dungeon-A2-B1] Ganon's Tower - north of Armos room [right chest].........................20 Rupees
## Special Locations

Magic Bat.................................................................................1/2 Magic
Misery Mire Required Medallion............................................................Quake
Pyramid Bottle Item.......................................................................Bottle (Gold Bee)
Turtle Rock Required Medallion............................................................Bombos
Waterfall Bottle Item.....................................................................Bottle (Gold Bee)

**Comment by greenham** [comment]
Per #95 I believe this can be closed. I went ahead and checked this seed and confirmed the location of the bow and titan's mitts match up with the spoiler log.

**Comment by BlueViper85** [comment]
Having not seen the comment from Greenham until I already ran through some of this seed, I also checked the seed up through the Bow and Mitts and confirmed that the spoiler log is accurate on all chests opened from Escape, through the town and down to the cave east of Lake Hylia

**Comment by KatDevsGames** [comment]
Seed confirmed as correct by multiple people. Not a bug.

On August 21, 2016 7:13:43 PM EDT, BlueViper85 notifications@github.com wrote:

> Having not seen the comment from Greenham until I already ran through
> some of this seed, I also checked the seed up through the Bow and Mitts
> and confirmed that the spoiler log is accurate on all chests opened
> from Escape, through the town and down to the cave east of Lake Hylia
> 
> ## 
> 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/Dessyreqt/alttprandomizer/issues/94#issuecomment-241288424

## 

Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by KatDevsGames** [comment]
Not a bug.
