### ISSUE TITLE
[v6] Music glitch

### ISSUE THREAD

**Issue by Tanean** [Dessyreqt/alttprandomizer#97]
Not a big issue, but I found out that if you use the ocarina near the light world flute boy (when he's still there and playing) the flute boy music carry over in the overworld map. When you enter a cave it stop and goes back to normal, but after that when I got to the hobo and exit his area, the music completely stop as if "keeping" the hobo music, which is no music at all (I did pass by the Zora first if that change anything). Once again, entering a cave fix the bug temporary, but the bug is still effective if I trigger another "special" background music and not normal overworld/cave/dungeon music. The "special" music carry over and dosent stop until the "major" background music change.

I don't know if it's a bug from the randomizer or the actual game since I never got the ocarina with the fluteboy still there, but I thought might as well share the find :)

Seed : C1508722

**Comment by greenham** [comment]
Adding a supplemental report from another user:

> [10:22 AM] Satarack: Hey Mish, just ran into a bug in the LTTP randomizer
> [10:22 AM] Satarack: you know the ocarina kid playing music for the animals, well I had both the ocarina and the shovel
> [10:22 AM] Satarack: so I went in there to dig up the dirt, and then flew away with the ocarina
> [10:23 AM] Satarack: and the kid's music didn't stop playing until I entered the Eastern Palace (where I was planing on going next)
> [10:23 AM] Mishrak: ah yeah
> [10:23 AM] Satarack: BUT then I died and was revived by a fairy
> [10:23 AM] Mishrak: if you don't trigger the cutscene
> [10:23 AM] Satarack: and the song started playing again
> [10:23 AM] Satarack: in the middle of the Eastern Palace

**Comment by BlueViper85** [comment]
Inadvertently recreated this in v5 seed C7595523.  Got the flute and activated it, dug up the item in the grove and called the bird while the music was still playing (I never got close enough to activate him and have the cutscene play) and the music persisted through until I got to DW.  It played on top of existing overworld music.

**Comment by ChristosOwen** [comment]
Happened to me too, but since the Flute music is so badass I think this falls under the "improvements" category rather than "bugs". I'm kidding of course ;)

**Comment by ChristosOwen** [comment]
This issue has been addressed and v7 will resolve it.
